### PR TITLE
Fix handling of generics in tuple variants and refactor a bit

### LINKED ISSUE #860: Hovering over Some shows `fn Some<i32>(T) -> Option<[unknown]>`
```rust
let i = So<|>me(0);
```

Pops up `fn Some<i32>(T) -> Option<[unknown]>` which is a little weird since it's not a function.

### PR DESCRIPTION
**Pull request by flodiebold**
(The problem was that we created separate substitutions for the return value, so we lost the connection between the type arguments in the constructor call and the type arguments of the result.)

Also make them display a tiny bit nicer.

Fixes #860.

### CODE REVIEW

File: crates/ra_hir/src/generics.rs [hunk 1]
```diff
@@ -87,4 +87,17 @@ impl GenericParams {
         let parent_count = self.count_parent_params();
         parent_count + self.params.len()
     }
+
+    fn for_each_param<'a>(&'a self, f: &mut impl FnMut(&'a GenericParam)) {
```
Comment (matklad) [inline crates/ra_hir/src/generics.rs]: This can't be an impl Iterator because the type is recursive, right? I wonder if we need some kind of "InternalIterator" helper crate for such cases? I imagine API like this:

```rust
pub fn params_including_parent(&'a self) -> impl InternalIterator<&'a GenericParam> + 'a {
    internal_iter(|f| {
         ....
    })
}
```

I feel it might run into GADs though...

File: crates/ra_hir/src/ty.rs [hunk 2]
```diff
@@ -1353,6 +1347,36 @@ impl<'a, D: HirDatabase> InferenceContext<'a, D> {
...
+                        substs.push(ty);
+                    }
+                }
+            }
+        };
+        let supplied_params = substs.len();
+        for _ in supplied_params..parent_param_count + param_count {
+            substs.push(Ty::Unknown);
+        }
+        Substs(substs.into())
```
Comment (matklad) [inline crates/ra_hir/src/ty.rs]: might add `assert_eq(subst.len() == def_generics.len())`

File: crates/ra_hir/src/generics.rs (hunk 1 above)
Comment (matklad) [reply crates/ra_hir/src/generics.rs]: I've  wondere if we should make type strictly two-level. I think currently we could have at most two-level nesting, right? But I imagine extensions to the language which allow arbitrary nesting, so handling the general case seems better.

Comment (flodiebold) [reply crates/ra_hir/src/generics.rs]: Yes, the recursion is the problem... I'm hoping we'll be able to handle something like this with generators someday :smile:

**Comment by matklad** [comment]
r=me

**Comment by flodiebold** [comment]
bors r=matklad
