### PR TITLE
minor: Bump npm non-dev deps

### LINKED ISSUE #10407: Closing "A request has failed." notification opens output panel
In the VS Code plugin, if I close the "A request has failed." with the close button, or it gets automatically closed by a second identical message, it opens the output panel automatically. I expect it to only happen when I press the "Go to output" button.

As to how I'm getting so many crashes that it's becoming a nuisance... well, #10386.

I'm on VS Code plugin version v0.3.763.

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #10407

### CODE REVIEW

File: editors/code/src/main.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ async function tryActivate(context: vscode.ExtensionContext) {
     ctx.pushCleanup(configureLanguage());
 
     vscode.workspace.onDidChangeConfiguration(
-        _ => ctx?.client?.sendNotification('workspace/didChangeConfiguration', { settings: "" }),
+        _ => ctx?.client?.sendNotification('workspace/didChangeConfiguration', { settings: "" }).catch(log.error),
```
Comment (lnicola) [inline editors/code/src/main.ts:69]: I _think_ this is right, but I'm not actually sure.
