### PR TITLE
fix textedit range returned for completion when left token is a keyword

### LINKED ISSUE #4545: Wrong textedit range is returned
I've tried with the latest nightly build of `rust-analyzer` and notice the wrong textEdit range is returned.
Here is the test snippet with `|` is where cursor is.
``` rust
pub fn test() {
    for index in 0..3 {
        let t = in|
    }
}
```

The log:
```
[Trace - 10:59:05 AM] Sending request 'textDocument/completion - (225)'.
Params: {
  "textDocument": {
    "uri": "file:///c%3A/Data/projects/rust/playground/c15/src/lib.rs"
  },
  "position": {
    "line": 2,
    "character": 18
  },
  "context": {
    "triggerKind": 1
  }
}

[Trace - 10:59:05 AM] Received response 'textDocument/completion - (225)' in 36ms.
Result: [
...
  {
    "textEdit": {
      "range": {
        "start": {
          "line": 2,
          "character": 18
        },
        "end": {
          "line": 2,
          "character": 18
        }
      },
      "newText": "index"
    },
    "label": "index",
    "kind": 6,
    "insertTextFormat": 1,
    "filterText": "index",
    "deprecated": null,
    "additionalTextEdits": []
  },
...
]
```
The range should be `start : {line: 2, character: 16}, end: {line:2, character: 18}` instead. With current range, it will just insert `index` right after `in` and we get `inindex` with previous test snippet.

Here is the full log [rust-analyzer.log](https://github.com/rust-analyzer/rust-analyzer/files/4660252/rust-analyzer.log)

### PR DESCRIPTION
**Pull request by bnjjj**
close #4545

### CODE REVIEW

File: crates/ra_ide/src/completion/completion_context.rs [hunk 1]
```diff
@@ -169,7 +169,16 @@ impl<'a> CompletionContext<'a> {
         match self.token.kind() {
             // workaroud when completion is triggered by trigger characters.
             IDENT => self.original_token.text_range(),
-            _ => TextRange::empty(self.offset),
+            _ => {
+                // If we haven't characters between keyword and our cursor we take the keyword start range to edit
+                if self.token.kind().is_keyword()
+                    && self.offset == self.original_token.text_range().end()
+                {
+                    TextRange::empty(self.original_token.text_range().start())
```
Comment (matklad) [inline crates/ra_ide/src/completion/completion_context.rs:177]: Let's add a `mark::hit` here and a `mark::test` for the test. Otherwise, lgtm

bors d+

File: crates/ra_hir/src/code_model.rs [hunk 2]
```diff
@@ -1363,6 +1363,7 @@ impl HirDisplay for Type {
 }
 
 /// For IDE only
+#[derive(Debug)]
```
Comment (matklad) [inline crates/ra_hir/src/code_model.rs:1366]: :+1:
