### PR TITLE
Items case quick fix (snake_case / UPPER_SNAKE_CASE / CamelCase)

### LINKED ISSUE #4598: QuickFix: Rename to snake case
rust-analyzer shows me a warning but doesn't provide a quick-fix for it.

1. Rename to snake case
2. Rename all references

rust-analyzer
Screen Shot 2020-05-25 at 2 19 28

IntelliJ Rust
Screen Shot 2020-05-25 at 2 21 18

### PR DESCRIPTION
**Pull request by popzxc**
Resolves #4598.

After a third try, it finally works. Boy, it appeared tougher than it seemed.

Initially I thought like "Ha, `rustc` already tells us where idents are named incorrectly. It shouldn't be that hard, should it?".

Well, the problems with the information provided by `rustc` appeared shortly:

- `rustc` warnings are `flycheck` warnings, which are slightly aside from our diagnostics with fixes.
  When we map flycheck diagnostic to LSP, we can convert it into a fix, but only if it's marked as `Applicability::MachineApplicable`.
  Name case fix is marked `Applicability::MaybeIncorrect`, and for a reason: it only suggest to rename symbol under cursor, without tracking any references.
- Warning spawned by `rustc` are identified by string labels rather than enum. It means that if one day the diagnostic will be renamed in `rustc`, `rust-analyzer` code will still compile, but won't find the required diagnostic by name anymore. If by chance this will happen when some unlucky guy will decide to create their first pull request, they'll be confused by suddenly failing tests  (likely) not related to their changes.
- Even if we'll try to build fixes atop of `rustc` warnings, we'll have to do it in the `rust_analyzer::diagnostics::to_proto` module, which is far less
  convenient for that matter than `ide` crate.

That's why I decided that it's worth a separate `rust-analyzer` diagnostic, which will implement `DiagnosticWithFix` trait.

After that, I discovered that currently `hir_ty::diagnostics` only check `DefWithBody` types, like function bodies. I had to add support for diagnostics
which look at any `ModuleDef`.

And of course, since I'd added a lot of new functionality, it required extensive testing.

That explains why the diff is so big for a (looking) relatively small feature.

I hope that this PR doesn't only add a small feature, but also creates a base for building another features.

## Example:

case_quick_fix

P.S. My eyes were bleeding when I had to write the code for the example...

### CODE REVIEW

File: crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs [hunk 1]
```diff
@@ -0,0 +1,196 @@
...
+        // While we didn't detect the correct case at the beginning, there
+        // may be special cases: e.g. `A` is both valid CamelCase and UPPER_SNAKE_CASE.
+        None
+    } else {
+        Some(output)
+    }
+}
+
+/// Converts an identifier to a lower_snake_case form.
+/// Returns `None` if the string is already is lower_snake_case.
```
Comment (Veykril) [inline crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs:105]:
```suggestion
/// Returns `None` if the string is already in lower_snake_case.
```

File: crates/stdx/src/lib.rs [hunk 2]
```diff
@@ -32,8 +32,12 @@ pub fn to_lower_snake_case(s: &str) -> String {
     let mut buf = String::with_capacity(s.len());
     let mut prev = false;
     for c in s.chars() {
+        // `&& prev` is required to not insert `_` before the first symbol.
         if c.is_ascii_uppercase() && prev {
-            buf.push('_')
+            // This check is required to not translate `Weird_Case` into `weird__case`.
+            if buf.chars().last() != Some('_') {
```
Comment (Veykril) [inline crates/stdx/src/lib.rs:38]:
```suggestion
            if !buf.ends_with('_') {
```

File: crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+    UpperCamelCase,
+    LowerSnakeCase,
+    UpperSnakeCase,
+    Unknown,
+}
+
+fn detect_case(ident: &str) -> DetectedCase {
+    let trimmed_ident = ident.trim_matches('_');
+    let first_lowercase =
+        trimmed_ident.chars().next().map(|chr| chr.is_ascii_lowercase()).unwrap_or(false);
```
Comment (Veykril) [inline crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs:16]:
```suggestion
        trimmed_ident.starts_with(|chr| chr.is_ascii_lowercase());
```

**Review by Veykril — COMMENTED** [review]
small nitpicks

**Comment by matklad** [comment]
>I hope that this PR doesn't only add a small feature, but also creates a base for building another features.

:heart_eyes:

File: crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+        DetectedCase::UpperSnakeCase => return None,
+        DetectedCase::LowerSnakeCase => {
+            return Some(ident.chars().map(|chr| chr.to_ascii_uppercase()).collect())
+        }
+        _ => {}
+    }
+
+    // Normalize the string from whatever form it's in currently, and then just make it uppercase.
+    let upper_snake_case =
+        stdx::to_lower_snake_case(ident).chars().map(|c| c.to_ascii_uppercase()).collect();
```
Comment (matklad) [inline crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs:140]: maybe just add `to_upper_snake_case` to stdx?

File: crates/syntax/src/ptr.rs [hunk 5]
```diff
@@ -21,6 +21,10 @@ impl SyntaxNodePtr {
         SyntaxNodePtr { range: node.text_range(), kind: node.kind() }
     }
 
+    pub fn text_range(&self) -> TextRange {
+        self.range.clone()
+    }
```
Comment (matklad) [inline crates/syntax/src/ptr.rs:26]: this should be kept private, we want to be able to experiemtn with other ptr representations, for exapmle, "node's number in dfs order".

File: crates/ide/src/diagnostics.rs [hunk 6]
```diff
@@ -253,6 +265,37 @@ mod tests {
...
+            for edit in fix.source_change.source_file_edits.iter().rev() {
+                edit.edit.apply(&mut actual);
+            }
+            actual
+        };
+
+        assert_eq_text!(&after, &actual);
+        assert!(
+            fix.fix_trigger_range.start() <= file_position.offset
+                && fix.fix_trigger_range.end() >= file_position.offset,
```
Comment (matklad) [inline crates/ide/src/diagnostics.rs:292]:
```suggestion
            fix.fix_trigger_range.start() <= file_position.offset
                && file_position.offset <= fix.fix_trigger_range.end(),
```

to give this a better visual intuition

Comment (matklad) [reply crates/ide/src/diagnostics.rs:292]: Isn't this `TextRange::contains_inclusive`?

File: crates/ide/src/diagnostics.rs [hunk 7]
```diff
@@ -253,6 +265,37 @@ mod tests {
...
+        let fix = diagnostic.fix.unwrap();
+        let target_file_contents = analysis.file_text(file_position.file_id).unwrap();
+        let actual = {
+            let mut actual = target_file_contents.to_string();
+            // Go from the last one to the first one, so that ranges won't be affected by previous edits.
+            for edit in fix.source_change.source_file_edits.iter().rev() {
+                edit.edit.apply(&mut actual);
+            }
+            actual
+        };
```
Comment (matklad) [inline crates/ide/src/diagnostics.rs:287]: :+1:

File: crates/hir_ty/src/diagnostics/decl_check.rs [hunk 8]
```diff
@@ -0,0 +1,821 @@
...
+//!
+//! - variable bindings (e.g. `let x = foo();`)
+//! - struct fields (e.g. `struct Foo { field: u8 }`)
+//! - enum variants (e.g. `enum Foo { Variant { field: u8 } }`)
+//! - function/method arguments (e.g. `fn foo(arg: u8)`)
+//! - constants (e.g. `const FOO: u8 = 10;`)
+//! - static items (e.g. `static FOO: u8 = 10;`)
+//! - match arm bindings (e.g. `foo @ Some(_)`)
+
+mod str_helpers;
```
Comment (matklad) [inline crates/hir_ty/src/diagnostics/decl_check.rs:13]: `mod case_conv` ?

File: crates/hir_ty/src/diagnostics/decl_check.rs [hunk 9]
```diff
@@ -0,0 +1,821 @@
...
+                name
+            } else {
+                // We don't want rust-analyzer to panic over this, but it is definitely some kind of error in the logic.
+                log::error!(
+                    "Replacement ({:?}) was generated for a function without a name: {:?}",
+                    replacement,
+                    fn_src
+                );
+                return;
+            };
```
Comment (matklad) [inline crates/hir_ty/src/diagnostics/decl_check.rs:184]: `match` should be shorter here

File: crates/hir_ty/src/diagnostics/decl_check.rs [hunk 10]
```diff
@@ -0,0 +1,821 @@
...
+    ast::{self, NameOwner},
+    AstNode, AstPtr,
+};
+
+use crate::{
+    db::HirDatabase,
+    diagnostics::{decl_check::str_helpers::*, CaseType, IncorrectCase},
+};
+
+pub(super) struct DeclValidator<'a, 'b: 'a> {
```
Comment (matklad) [inline crates/hir_ty/src/diagnostics/decl_check.rs:35]: This doesn't handle `allow()`  attributes, right?  I think this is fine for an experimental diagnostics, but we'll get a lot of reports for this nontheless :)

Comment (popzxc) [reply crates/hir_ty/src/diagnostics/decl_check.rs:35]: Well, we can selectively disable diagnostics. Fellows that aren't interested in this feature can just add a `"incorrect-ident-case"` into the list of disabled diagnostics.

Isn't it enough? I think, parsing the crate attributes (especially given the fact that there are at least three different ones for this matter, and they may appear in different places) may become a burden.

Comment (matklad) [reply crates/hir_ty/src/diagnostics/decl_check.rs:35]: Well, it's a burden we'll have to carry anyway, at the end :-) It probably doesn't make to handle this in this PR, as it paves quite a bit of path already

File: crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs (hunk 4 above)
Comment (popzxc) [reply crates/hir_ty/src/diagnostics/decl_check/str_helpers.rs:140]: I was a bit hesitant to add a function which is (currently) is only used in one place into a dependency crate, but surely it will fit there better :)

File: crates/ide/src/diagnostics.rs (hunk 6 above)
Comment (popzxc) [reply crates/ide/src/diagnostics.rs:292]: It was copy-pasted from `check_fix`. Fixed in both places now.

**Comment by matklad** [comment]
Has a merge conflict

**Comment by popzxc** [comment]
Fixed. Compilation for MacOS failed though, not sure if it's because of me.

**Comment by matklad** [comment]
bors r+

Yeah, build failure is being investigated in #6202
