### PR TITLE
Fix double comma when merge imports on second line

### LINKED ISSUE #3832: Merge import double comma
Hey, I think I found a bug using merge imports. 
_Example:_
```
use hyper::service::make_service_fn;
use hyper::{
    StatusCode,
};
```
Merge imports on **line 2**.
```
use hyper::{
    StatusCode,
, service::make_service_fn};
```
There should only be one comma.
Correct behaviour on Merge imports on line 1 though.
vscode rust-analyzer version 0.2.108

### PR DESCRIPTION
**Pull request by IceSentry**
This fixes the bug when merging imports from the second line when it already has a comma it would previously insert a comma.

There's probably a better way to check for a COMMA. 

This also ends up with a weird indentation, but rust-fmt can easily deal with it so I'm not sure how to resolve that.

Closes #3832

### CODE REVIEW

File: crates/ra_assists/src/handlers/merge_imports.rs [hunk 1]
```diff
@@ -72,9 +72,24 @@ fn try_merge_trees(old: &ast::UseTree, new: &ast::UseTree) -> Option<ast::UseTre
...
+        .last_child()
+        .and_then(|child| child.children().last())
+        .and_then(|last| last.next_sibling_or_token())
+        .map(|next_sibling| {
+            // FIXME: there's probably a better way to check if it's a COMMA
+            if let NodeOrToken::Token(maybe_comma) = next_sibling {
+                should_insert_comma = maybe_comma.to_string() != ",";
+            }
+        });
+
```
Comment (edwin0cheng) [inline crates/ra_assists/src/handlers/merge_imports.rs:87]:
```

    let should_insert_comma = lhs
        .syntax()
        .last_child()
        .and_then(|child| child.children().last())
        .and_then(|last| last.next_sibling_or_token())
        .map(|it| it.kind() != T![,])
        .unwrap_or(true);
```

Comment (edwin0cheng) [reply crates/ra_assists/src/handlers/merge_imports.rs:87]: And here is a more correct one which skip white spaces properly :
```rust
let should_insert_comma = lhs
    .use_tree_list()?
    .r_curly_token()
    .and_then(|it| skip_trivia_token(it.prev_token()?, Direction::Prev))
    .map(|it| it.kind() != T![,])
    .unwrap_or(true);
```

Comment (IceSentry) [reply crates/ra_assists/src/handlers/merge_imports.rs]: Thanks, this is much better!

**Comment by edwin0cheng** [comment]
bors r+

Thanks!
