### PR TITLE
fix: make the logs line buffered

### LINKED ISSUE #9432: Make sure logs are at least line-buffered
Heh, another thing. Some logging in rust-analyzer might benefit from buffering. It's emitting tiiiny syscall writes right now:
image

_Originally posted by @HalfVoxel in https://github.com/rust-analyzer/rust-analyzer/issues/9384#issuecomment-866779684_

### PR DESCRIPTION
**Pull request by mahdi-frms**
fixes #9432
Not quite sure if that's what you want, but storing the log message in buffers eliminated the tiny write syscalls for me.
I just changed the Logger struct.

### CODE REVIEW

**Comment by lnicola** [comment]
Oh, I didn't even realize that was our logging sink. I'm surprised it behaves like this, since it's already using a `BufWriter`.

Anyway, #9274 will probably get rid or replace that code.

**Comment by lnicola** [comment]
Oh, it's `stderr` that's not buffered.

**Comment by mahdi-frms** [comment]
Yeah, I actually checked stderr, I think that's the main issue.

**Comment by matklad** [comment]
TIL: https://github.com/rust-lang/rust/issues/64413

Let's just quickly fix this by formatting the string to memory with `format`, and then writing the whole thing to stderr in one go.

**Comment by lnicola** [comment]
Can we wrap stderr in a `LineWriter` or `BufWriter` and stick it in `self`?

**Comment by mahdi-frms** [comment]
> Let's just quickly fix this by formatting the string to memory with `format`, and then writing the whole thing to stderr in one go.

I've done the same for the Logger in this PR. or you mean for the whole source code?

File: crates/rust-analyzer/src/bin/logger.rs [hunk 1]
```diff
@@ -50,22 +50,23 @@ impl Log for Logger {
 
         let should_flush = match &self.file {
             Some(w) => {
-                let _ = writeln!(
-                    w.lock(),
-                    "[{} {}] {}",
+                let message = format!(
```
[the remark this answers is not in the document]
Comment (mahdi-frms) [reply crates/rust-analyzer/src/bin/logger.rs]: Ok, did it.

File: crates/rust-analyzer/src/bin/logger.rs [hunk 2]
```diff
@@ -57,22 +57,21 @@ impl Log for Logger {
                     record.module_path().unwrap_or_default(),
                     record.args(),
                 );
-                self.no_buffering
+
+                if self.no_buffering {
+                    self.flush();
```
Comment (lnicola) [inline crates/rust-analyzer/src/bin/logger.rs:62]:
```suggestion
                    w.lock().flush();
```

(or hoist that to a local).

Then `flush` is dead code.

Comment (mahdi-frms) [reply crates/rust-analyzer/src/bin/logger.rs:62]: Well we can't remove flush as it's part of Log trait.
Instead, I will put the actual flush inside of it.

Comment (lnicola) [reply crates/rust-analyzer/src/bin/logger.rs:62]: Ah, sorry, I missed that.

Comment (lnicola) [reply crates/rust-analyzer/src/bin/logger.rs:62]: Not to be too nit-picky, but this feels strange -- what if `log` calls `flush` internally?

I would have left `flush` unchanged, moved `w.lock()` to a variable, then called `flush` on that in this branch.

Comment (mahdi-frms) [reply crates/rust-analyzer/src/bin/logger.rs:62]: I guess what you're suggesting makes sense, that way we had to acquire the lock twice.

File: crates/rust-analyzer/src/bin/logger.rs [hunk 3]
```diff
@@ -48,31 +48,31 @@ impl Log for Logger {
...
+                    writer,
                     "[{} {}] {}",
                     record.level(),
                     record.module_path().unwrap_or_default(),
                     record.args(),
                 );
-                self.no_buffering
+
+                if self.no_buffering {
+                    writer.flush().unwrap();
```
Comment (lnicola) [inline crates/rust-analyzer/src/bin/logger.rs:63]: Maybe

```suggestion
                    let _ = writer.flush();
```

But I'm not sure how I feel about it. This might cause some spurious panics when we're run by another program and it closes our `stderr`.

Comment (mahdi-frms) [reply crates/rust-analyzer/src/bin/logger.rs:63]: Yeah, I only put the unwrap() to get rid of the warning. thanks for mentioning.

Comment (lnicola) [reply crates/rust-analyzer/src/bin/logger.rs:63]: Yeah, then maybe let's ignore the errors here.
