### PR TITLE
Extract function assist will add async if required

### LINKED ISSUE #8232: Extract into function assist should generate `async fn` if the selected code contains a `.await`
Currently, using `extract into function` on some `async` code including a `.await` point generates a regular non-`async` fn, which the obviously fails because of the missing async context. ra should generate an `async fn` instead.

### PR DESCRIPTION
**Pull request by JamieCunliffe**
The extract function assist will check for an AWAIT_EXPR or AWAIT_KW in the body and if found, will add async to the generated function.

closes #8232

### CODE REVIEW

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 1]
```diff
@@ -643,6 +643,16 @@ fn vars_used_in_body(ctx: &AssistContext, body: &FunctionBody) -> Vec<Local> {
...
 
+fn body_contains_await(body: &FunctionBody) -> bool {
+    body.descendants()
+        .find(|d| {
+            d.descendants_with_tokens()
+                .find(|d| matches!(d.kind(), SyntaxKind::AWAIT_EXPR | SyntaxKind::AWAIT_KW))
+                .is_some()
+        })
+        .is_some()
+}
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/extract_function.rs:654]: This won't work properly for macros. Assuming a macro that generates an expression using `.await` this will still return false, likewise a macro that gets `await` passed into it without emitting an actual await expression will incorrectly return true.
I don't think we have something like `Semantics::descendants_with_macros` though to look for await expressions 🤔

Comment (JamieCunliffe) [reply crates/ide_assists/src/handlers/extract_function.rs:654]: I couldn't see something like that, I have attempted to write one iterating over the descendants and when encountering a  `MacroCall` expanding it with `Semantics::expand` into the tree although I haven't got that to work yet. I'll carry on looking at that as I feel I'm getting more familiar with the code now.

Comment (Veykril) [reply crates/ide_assists/src/handlers/extract_function.rs:654]: @matklad maybe you got an idea here?

Comment (flodiebold) [reply crates/ide_assists/src/handlers/extract_function.rs:654]: It does seem like this kind of thing should be done on the HIR, but we need a HIR for expressions for that (independently of #8713).

**Comment by Veykril** [comment]
@JamieCunliffe so given the comments I think its fine if we just look for await expressions in the body ignoring macros and the await keyword for the time being.

**Comment by JamieCunliffe** [comment]
@Veykril I have pushed a change to only look for await expressions.

**Comment by Veykril** [comment]
Thanks!
bors r+
