### PR TITLE
Show dbg remove assist on empty contents

### LINKED ISSUE #8185: Remove dbg! assist does not work on empty args
MWE:

```rust
dbg!();  // No assist 
dbg!("12345");  // With assist
```

### PR DESCRIPTION
**Pull request by ivan770**
Closes #8185

### CODE REVIEW

**Comment by ivan770** [comment]
Hmm, this leads to kinda unexpected results if `dbg` call is used as value for assignment. Might need to replace it with `()` in this case.

**Comment by Veykril** [comment]
As an heuristic, it might make sense to remove the entire EXPR_STMT parent node(including the semicolon) if the macro call is the sole child of it, otherwise replace it with `()`?

**Comment by flodiebold** [comment]
Why would someone use it in an assignment? More importantly, I think we'd want to remove the whole statement including `;` and newline.

File: crates/ide_assists/src/handlers/remove_dbg.rs [hunk 1]
```diff
@@ -24,7 +24,22 @@ pub(crate) fn remove_dbg(acc: &mut Assists, ctx: &AssistContext) -> Option<()> {
...
+
+        let start = parent
+            .prev_sibling_or_token()
+            .and_then(|el| {
+                Some(el.into_token().and_then(ast::Whitespace::cast)?.syntax().text_range().start())
+            })
+            .unwrap_or(parent.text_range().start());
+        let end = parent.text_range().end();
+
+        TextRange::new(start, end)
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/remove_dbg.rs:38]: This straight up removes the parent if I see this right, which seems suboptimal if someone had a dbg! call as the tail expression
```rust
{
	/* some more code */
	dbg!()
}
```
if I'm not mistaken this would remove the entire block

Comment (ivan770) [reply crates/ide_assists/src/handlers/remove_dbg.rs]: Fixed it, and added replacing `dbg` call with `()` in `LetExpr`

File: crates/ide_assists/src/handlers/remove_dbg.rs [hunk 2]
```diff
@@ -415,6 +454,50 @@ fn main() {
...
+    fn test_remove_empty_dbg() {
+        check_assist(remove_dbg, r#"fn foo() { $0dbg!(); }"#, r#"fn foo() { }"#);
+        check_assist(
+            remove_dbg,
+            r#"fn foo() {
+$0dbg!();
+}"#,
+            r#"fn foo() {
+}"#,
+        );
```
Comment (matklad) [inline crates/ide_assists/src/handlers/remove_dbg.rs:471]: Let's use standard test style

```suggestion
            r#"
fn foo() {
    $0dbg!();
}
"#,
            r#"
fn foo() {
}
"#,
        );
```

Although, maybe just write this as a single line.

Comment (ivan770) [reply crates/ide_assists/src/handlers/remove_dbg.rs:471]: I guess multiline test shows better, than newline before dbg is removed

**Comment by edwin0cheng** [comment]
LGTM

bors r+

**Comment by lnicola** [comment]
changelog fix offer "Remove `dbg!`" assist on empty calls
