### PR TITLE
ra_cargo_watch: log errors

### LINKED ISSUE #3631: `cargo watch` integration no longer works for workspaces
VS Code version: 1.43.0
rust-analyzer version: 0.1.20200316

I just upgraded to the latest version of rust-analyzer, and I'm not getting any error messages or warnings from `cargo watch` in the top-level directory of my workspace anymore. Note that `cargo check` from the top-level directory works fine. I do get error messages if I run vscode from one of the crates inside the workspace.

Here is a git repo I put together demonstrating it not working: https://github.com/mikeyhew/rust-analyzer-broken-cargo-watch

to reproduce:

```
git clone https://github.com/mikeyhew/rust-analyzer-broken-cargo-watch
cd rust-analyzer-broken-cargo-watch
cargo check
```

Notice how `cargo check` outputs an error message, in this case an ICE.

Now open the workspace in VS Code:

```
code .
```

and open the file `yolo/src/main.rs`, and save the file. You should be getting the same error message, but nothing happens.

If you don't like how `break rust` causes an ICE, you can change it to something else, e.g. `does_not_exist()`. It still won't output any error messages.

### PR DESCRIPTION
**Pull request by Veetaha**
Until this moment we totally ignored all the errors from cargo process. Though this is still true, but we
now try to log ones that are critical (i.e. misconfiguration errors and ignore compile errors).

This fixes #3631, and gives us a better error message to more gracefully handle the #3265
image

Though I think that outputting this only to `Output` channel is not enough. We should somehow warn the user that he passed wrong arguments to `cargo-watch.args`. I didn't bother looking for how to do this now, but this PR at least gives us something.

*cc* @kiljacken @matklad

### CODE REVIEW

File: crates/ra_cargo_watch/src/lib.rs [hunk 1]
```diff
@@ -316,6 +316,8 @@ impl WatchThread {
             args.push("--all-targets".to_string());
         }
         args.extend(options.args.iter().cloned());
+        args.sort();
+        args.dedup();
```
Comment (matklad) [inline crates/ra_cargo_watch/src/lib.rs]: I don't think we should dedup flags. Dedupe flag is an error, it should cause a failure.

File: crates/ra_cargo_watch/src/lib.rs [hunk 2]
```diff
@@ -316,6 +316,8 @@ impl WatchThread {
             args.push("--all-targets".to_string());
         }
         args.extend(options.args.iter().cloned());
+        args.sort();
```
Comment (matklad) [inline crates/ra_cargo_watch/src/lib.rs]: This will mess up `--package foo`, we should not sort flags. In general, a good rule of thumb is to use input things as is. For example, `cargo` deliberately avoids canonicalizing and/or normalizing paths received from user.

File: crates/ra_cargo_watch/src/lib.rs (hunk 1 above)
Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: So do we remove the deduplication at all?

**Comment by Veetaha** [comment]
Removed the dedup, left only error logging.

File: crates/ra_cargo_watch/src/lib.rs [hunk 3]
```diff
@@ -352,8 +352,21 @@ impl WatchThread {
...
-                let _ = child.wait();
+                // Again, we are resilient to errors, so we don't try to panic here
+                match child.wait_with_output() {
+                    Ok(output) => match output.status.code() {
+                        Some(0) | None => {}
+                        Some(exit_code) => {
+                            let output =
+                                std::str::from_utf8(&output.stderr).unwrap_or("<bad utf8 output>");
+
+                            if !output.contains("could not compile") {
```
Comment (matklad) [inline crates/ra_cargo_watch/src/lib.rs]: let's rather check that exit code is equal to zero. Cargo uses `1` to mean "cli is wrong", and `101` for other errors  (like a wrong dependency). The are errors which we want to ignore, which are not "cound not compile".

Also, it seems like we should move waiting for the child into `run_cargo` function.

File: crates/ra_cargo_watch/src/lib.rs [hunk 4]
```diff
@@ -259,7 +259,7 @@ pub fn run_cargo(
     let mut child = command
         .args(args)
         .stdout(Stdio::piped())
-        .stderr(Stdio::null())
+        .stderr(Stdio::piped())
```
Comment (matklad) [inline crates/ra_cargo_watch/src/lib.rs]: This I believe is technically wrong, as process pipes are of bounded capacity, and if Cargo to write a lot of output to stderr, it'll block. Hm, now that I think about it, we might actually hit this case, if some proc macro writes something to stderr (because, for example, RUST_LOG env variable is set)....

Ideally, we should use `select` here to drain both pipes, but that seems like a lot of work. What if we just check the exit status, and, if it is `1`, we log the command line? I think that should be enough to diagnose the issues.

Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: The 1 would not be enough. In the example screenshot, I provided the status is 101...

Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: The problem is that we lack the general error handling infrastructure for the cargo watcher...

Comment (matklad) [reply crates/ra_cargo_watch/src/lib.rs]: Hm, indeed. I guess the right heuristic here is "the set of messages is empty, but the return code is non-zero".

Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: Hm, right, I think this is a good criterion because the only successful outcome for us will be the metadata output. However, it's bad that we cannot log the actual `stderr` contents right away. Might I ask you to give a pointer to which particular `select` you referred just for my curiosity?

Comment (bjorn3) [reply crates/ra_cargo_watch/src/lib.rs]: compiletest uses this: https://github.com/rust-lang/rust/blob/f4c675c476c18b1a11041193f2f59d695b126bc8/src/tools/compiletest/src/read2.rs. Maybe copy it somewhere yet another time. Or just make a crate to be shared between all users of a copy of this code.

File: crates/ra_cargo_watch/src/lib.rs (hunk 3 above)
Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: @matklad 
If I move waiting for the child to `run_cargo()`, then we will send `CheckEvent::End` only after the child is released, or won't it be a problem?

File: crates/ra_cargo_watch/src/lib.rs (hunk 4 above)
Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: Thanks bjorn, that is a good source of knowledge. I'd like to avoid copying that to `rust-analyzer` repo. Maybe to `ra_vfs`?

Comment (bjorn3) [reply crates/ra_cargo_watch/src/lib.rs]: > Or just make a crate to be shared between all users of a copy of this code.

I think this would be the best.

Comment (Veetaha) [reply crates/ra_cargo_watch/src/lib.rs]: Yeah, it would be great, though I don't feel strong enough on this topic... Unless anyone else does it :D !
For this use case, we can just use a simple solution of not reading the stderr here for now.

**Comment by Veetaha** [comment]
Changed `run_cargo()` to return `Result<(), CargoError>`, added some comments on better error handling in cargo watcher thread and `run_cargo()` reading `stderr`

File: crates/ra_cargo_watch/src/lib.rs [hunk 5]
```diff
@@ -291,12 +304,27 @@ pub fn run_cargo(
...
 
-    child
+    // It is okay to ignore the result, as it only errors if the process is already dead
+    let _ = child.kill();
+
+    let err_msg = match child.wait() {
+        Ok(exit_code) if !exit_code.success() && !read_at_least_one_message => {
+            // FIXME: Read the stderr to display the reason, see `read2()` reference in PR comment:
+            // https://github.com/rust-analyzer/rust-analyzer/pull/3632#discussion_r395605298
+            format!("the command produced no valid metadata:\n cargo {}", args.join(" "))
```
Comment (Veetaha) [inline crates/ra_cargo_watch/src/lib.rs]:
```suggestion
            format!("the command produced no valid metadata: cargo {}", args.join(" "))
```

File: crates/ra_project_model/src/cargo_workspace.rs [hunk 6]
```diff
@@ -263,19 +263,15 @@ pub fn load_out_dirs(
         // FIXME: `NoDefaultFeatures` is mutual exclusive with `SomeFeatures`
         // https://github.com/oli-obk/cargo_metadata/issues/79
         args.push("--no-default-features".to_string());
-    } else if !cargo_features.features.is_empty() {
-        for feature in &cargo_features.features {
-            args.push(feature.clone());
-        }
+    } else {
+        args.extend(cargo_features.features.iter().cloned());
```
Comment (matklad) [inline crates/ra_project_model/src/cargo_workspace.rs]: :+1:
