### PR TITLE
fix(assist): Drop generic args in path before insert use in `replace_qualified_name_with_use`

### LINKED ISSUE #11505: "Replace qualified path with use" using turbofish
**rust-analyzer version**: 02904e99a 2022-02-14 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

Using replace qualified path with use on:

```rust
std::mem::size_of::<String>()
```
results in:

```rust
use std::mem::size_of::<;
```

### PR DESCRIPTION
**Pull request by tysg**
Fixes #11505. also removed an unnecessary `clone_for_update` call.

### CODE REVIEW

File: crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs [hunk 1]
```diff
@@ -84,7 +84,8 @@ pub(crate) fn replace_qualified_name_with_use(
                 ImportScope::Module(it) => ImportScope::Module(builder.make_mut(it)),
                 ImportScope::Block(it) => ImportScope::Block(builder.make_mut(it)),
             };
-            shorten_paths(scope.as_syntax_node(), &path.clone_for_update());
+            shorten_paths(scope.as_syntax_node(), &path);
```
Comment (tysg) [inline crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs:87]: It seems like only `scope` is mutated. `path` is only used in `path_eq_no_generics` in an immutable fashion.

**Comment by Veykril** [comment]
Thanks!
bors r+
