### PR TITLE
fix #2520: change expand_repeat loop stop condition

### LINKED ISSUE #2520: Complex macro_rules error
I've a big (500 lines recursive) macro_rules that generate a strictly typed keyvalue store database types.
Since about a week, using this macro generate a tons of errors (Missing structure fields) with the wrong position in the file. The macro is perfectly working with rustc.

Sadly, I can't share the macro, but I might be able to track down the root cause myself. 

Before spending some time on this, are macro_rules implementation complete and this is a bug, or is there a missing feature that might cause this?

### PR DESCRIPTION
**Pull request by Speedy37**
This changes the loop stop condition in expand_repeat by marking each nesting stack level if they are at end and if they were hit (it is possible to have a `$var` inside a macro which is not bound).

The previous way of stopping the loop was by checking if any variable was used.

### CODE REVIEW

**Comment by Speedy37** [comment]
A few note about what I saw while doing this:

- There is no distinction between a macro eval error and a rule matching error.
- There is no check if a variable is bound to the same nested block.
- Errors in repeat are silent.

File: crates/ra_mbe/src/mbe_expander/transcriber.rs [hunk 1]
```diff
@@ -14,21 +14,24 @@ impl Bindings {
...
         })?;
-        for &idx in nesting.iter() {
+        for s in nesting.iter_mut() {
+            s.hit = true;
             b = match b {
                 Binding::Fragment(_) => break,
-                Binding::Nested(bs) => bs.get(idx).ok_or_else(|| {
+                Binding::Nested(bs) => bs.get(s.idx).ok_or_else(|| {
+                    s.at_end = true;
                     ExpandError::BindingError(format!("could not find nested binding `{}`", name))
```
Comment (edwin0cheng) [inline crates/ra_mbe/src/mbe_expander/transcriber.rs]: So `at_end` is an error state for nested binding, right ?,  Maybe we could introduce `ExpandError::NestedError` and recover it later? Although I am okay for current approach but I just leave a record here for the alternative solution.

File: crates/ra_mbe/src/mbe_expander/transcriber.rs [hunk 2]
```diff
@@ -51,15 +54,21 @@ pub(super) fn transcribe(
...
     assert!(template.delimiter == None);
-    let mut ctx = ExpandCtx { bindings: &bindings, nesting: Vec::new(), var_expanded: false };
+    let mut ctx = ExpandCtx { bindings: &bindings, nesting: Vec::new() };
     expand_subtree(&mut ctx, template)
 }
 
+#[derive(Debug)]
+struct NestingState {
+    idx: usize,
+    hit: bool,
```
Comment (edwin0cheng) [inline crates/ra_mbe/src/mbe_expander/transcriber.rs]: OTOH, would you mind add some comment about `s.hit` ?

File: crates/ra_mbe/src/mbe_expander/transcriber.rs [hunk 3]
```diff
@@ -121,8 +130,7 @@ fn expand_var(ctx: &mut ExpandCtx, v: &SmolStr) -> Result<Fragment, ExpandError>
         .into();
         Fragment::Tokens(tt)
     } else {
-        let fragment = ctx.bindings.get(&v, &ctx.nesting)?.clone();
-        ctx.var_expanded = true;
+        let fragment = ctx.bindings.get(&v, &mut ctx.nesting)?.clone();
```
Comment (edwin0cheng) [inline crates/ra_mbe/src/mbe_expander/transcriber.rs]: We could just remove `let fragment` here, since `ctx.var_expaned` is removed.

File: crates/ra_mbe/src/mbe_expander/transcriber.rs (hunk 1 above)
Comment (Speedy37) [reply crates/ra_mbe/src/mbe_expander/transcriber.rs]: Well at_end, is a marker to tell the loop it can stop now.
I did try to add a new ExpandError::AtEnd, recover from it in expand_repeat, but I hit a wall as only returning an Error (or even None) doesn't provide any information back about which nested level is at_end.

File: crates/ra_mbe/src/mbe_expander/transcriber.rs (hunk 2 above)
Comment (Speedy37) [reply crates/ra_mbe/src/mbe_expander/transcriber.rs]: `hit` is also a marker like `at_end`, it's present to mark the use of a given nested level (i.e. prevent an infinite loop if there is no variable in a repetition).

File: crates/ra_mbe/src/mbe_expander/transcriber.rs (hunk 1 above)
Comment (edwin0cheng) [reply crates/ra_mbe/src/mbe_expander/transcriber.rs]: Will `ExpandError::AtEnd(usize)`  do the trick here ? But anyway, I am okay for current approach.

Comment (Speedy37) [reply crates/ra_mbe/src/mbe_expander/transcriber.rs]: Probably. But imo it would only be worth it if the `hit` marker is also removed and replaced with a proper solution.

**Comment by Speedy37** [comment]
It should be a bit better now.

**Comment by edwin0cheng** [comment]
I think that issue is not related to this PR, let's merge it. Thanks.

bors r+

**Comment by edwin0cheng** [comment]
bors cancel

**Comment by matklad** [comment]
bors is acting up again, merging manually!
