### PR TITLE
editors/code: fix nixos detection

### LINKED ISSUE #11695: Binary is not being patched on NixOS in the latest nightly
@lnicola This is cursed, and should never have been accepted:
https://github.com/rust-analyzer/rust-analyzer/blob/0182f7451600e1700873549c324f7d13585547f4/editors/code/src/main.ts#L272
```
cat /etc/os-release
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.05.20220305.062a0c5"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID="nixos"
LOGO="nix-snowflake"
NAME="NixOS"
PRETTY_NAME="NixOS 22.05 (Quokka)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.05 (Quokka)"
VERSION_CODENAME="quokka"
```

This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

### PR DESCRIPTION
**Pull request by cab404**
Problem: NixOS started using quotes around it's id field in /etc/os-release
Solution: Parially parsing os-release, and detecting, whether `nixos` appears anywhere in "ID=" field\
See https://github.com/rust-analyzer/rust-analyzer/issues/11695

Closes #11695

### CODE REVIEW

File: editors/code/src/main.ts [hunk 1]
```diff
@@ -269,7 +269,8 @@ function serverPath(config: Config): string | null {
 async function isNixOs(): Promise<boolean> {
     try {
         const contents = (await vscode.workspace.fs.readFile(vscode.Uri.file("/etc/os-release"))).toString();
-        return contents.indexOf("ID=nixos") !== -1;
+        const idString = contents.split('\n').find((a) => a.startsWith("ID="));
+        return idString?.toLowerCase()?.indexOf("nixos") !== -1;
```
Comment (lnicola) [inline editors/code/src/main.ts:273]: I think a `contents.indexOf("nixos") !== -1` would have worked just as well (while being less allocation-heavy), but oh well.

Comment (cab404) [reply editors/code/src/main.ts:273]: just in case they decide to do strange stuff with ids
you are probably right that won't be ever necessary

**Comment by lnicola** [comment]
changelog fix detect NixOS when `/etc/os-release` includes quotes

**Comment by cab404** [comment]
ohhh, okay, found several other projects using the same checks. gonna fix it in nixpkgs before all the weird bugs start surfacing

(turns out, having `"` in your ID field is not even legal :D)

**Comment by lnicola** [comment]
> The file /etc/os-release takes precedence over /usr/lib/os-release. Applications should check for the former, and exclusively use its data if it exists, and only fall back to /usr/lib/os-release if it is missing.

Uh, TIL.
