### PR TITLE
fix: correct version string to contain hash, build date and channel

### LINKED ISSUE #8571: Version strings are still wrong
We use `git describe` to get a version string, but the release is tagged only after uploading the artifacts to GitHub. This means that we make a version string using the previous release name.

One way to fix this would be to force a certain version string in the workflow for non-nightly releases, but it feels a bit hacky.

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

closes #8571

### CODE REVIEW

File: crates/rust-analyzer/build.rs [hunk 1]
```diff
@@ -18,29 +15,52 @@ fn set_rerun() {
...
+
+    "???????".to_string()
+}
+
+fn commit_hash() -> Option<String> {
+    output_to_string("git rev-parse --short HEAD")
+}
+
+fn build_date() -> Option<String> {
+    output_to_string("date --iso --utc")
```
Comment (matklad) [inline crates/rust-analyzer/build.rs:58]: Not sure if this'll work for all hosts, but we are doing a similar thing in dist anyways, so, somehow, it seems to work?
