### PR TITLE
fix: visibility in impl items and pub(crate) to pub in extract_module

### LINKED ISSUE #11007: Extract Module assist adds invalid visibility modifiers to trait method implementations
When using the "Extract Module" assist, it adds invalid visibility modifiers to the methods of trait implementations, causing errors.

## Steps to reproduce
1. Create new project, open with rust-analyzer (I use vscode)
2. Paste this code into it:
```rust
pub struct Bla;

pub trait Trait {
    fn blub() -> Self;
}

impl Trait for Bla {
    fn blub() -> Self {
        Bla
    }
}

impl Default for Bla {
    fn default() -> Self {
        Bla
    }
}
```
3. Select it all and run the "Extract Module" assist.

## Current behavior
The trait implementations (though not the trait definitions) get an invalid visibility modifier in the extracted module, like this:
```rust
    impl Trait for Bla {
        pub(crate) fn blub() -> Self {
            Bla
        }
    }

    impl Default for Bla {
        pub(crate) fn default() -> Self {
            Bla
        }
    }
```
which immediately causes rust-analyzer to show an "unnecessary visibility modifier" error and the code to fail to compile.

## Expected behavior
Extracted trait implementations should not have visibility modifiers.

## Version information

**rust-analyzer version**: rust-analyzer version: db2a7087b 2021-12-13 stable
**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

### PR DESCRIPTION
**Pull request by feniljain**
Should fix #11007 and #11443

Makes following changes:

- Removes visiblity modifiers from trait items
- Respect user given visibility
- Updated tests for the same

### CODE REVIEW

**Comment by feniljain** [comment]
Hey @Veykril, would you like to have a look, it's not a complicated PR, shouldn't occupy a lot of your time 😄

File: crates/ide_assists/src/handlers/extract_module.rs [hunk 1]
```diff
@@ -958,21 +935,21 @@ fn bar() -> i32 {
...
 
-    pub(crate) struct PrivateStruct1 {
-        pub(crate) inner: i32,
+    pub struct PrivateStruct1 {
+        pub inner: i32,
     }
 
     impl PrivateStruct {
-        pub(crate) fn new() -> Self {
+        fn new() -> Self {
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/extract_module.rs:947]: This should keep that new visibility I think? The issue was mainly about trait items/trait impls, since associated items for traits and trait impls are not allowed to have visibility modifiers.

File: crates/ide_assists/src/handlers/extract_module.rs [hunk 2]
```diff
@@ -825,18 +806,14 @@ fn add_change_vis(
     vis: Option<ast::Visibility>,
     node_or_token_opt: Option<syntax::SyntaxElement>,
 ) -> Option<()> {
-    if let Some(vis) = vis {
-        if vis.syntax().text() == "pub" {
-            ted::replace(vis.syntax(), make::visibility_pub_crate().syntax().clone_for_update());
-        }
-    } else {
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/extract_module.rs:832]: Just removing this should be fine right? Keeping `pub(crate)` as the default visibility modifier after extraction sounds correct to me, the issue was mainly talking about `pub` items being extracted having their visibility reduced to `pub(crate)` before which this branch did.

File: crates/ide_assists/src/handlers/extract_module.rs (hunk 1 above)
Comment (feniljain) [reply crates/ide_assists/src/handlers/extract_module.rs]: yeah, I guess I presumed it wrong

File: crates/ide_assists/src/handlers/extract_module.rs [hunk 3]
```diff
@@ -779,7 +779,12 @@ fn get_replacements_for_visibilty_change(
             ast::Item::Enum(it) => replacements.push((it.visibility(), it.syntax().clone())),
             ast::Item::ExternCrate(it) => replacements.push((it.visibility(), it.syntax().clone())),
             ast::Item::Fn(it) => replacements.push((it.visibility(), it.syntax().clone())),
-            ast::Item::Impl(it) => impls.push(it),
+            ast::Item::Impl(it) => {
+                //Associated item's visibility should not be changed
+                if let None = it.for_token() {
+                    impls.push(it);
+                }
+            }
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/extract_module.rs:787]:
```suggestion
            //Associated item's visibility should not be changed
            ast::Item::Impl(it) if it.for_token().is_none() => impls.push(it),
```
Can be written like this a bit more succinct

**Review by Veykril — COMMENTED** [review]
Thanks! One small nit.
bors d+
