### PR TITLE
Fix non-latin characters doc comment in mbe expansion

### LINKED ISSUE #7781: Chinese characters are shown as Unicode other than glyph when the doc comment included in a macro.
Chinese characters are shown as Unicode other than glyph when the doc comment included in a macro.
image

But English doc comment will be OK.
image

The file's encoding is UTF-8.

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fixes #7781

Peek 2021-02-28 13-47

Off-topic: A [beautiful poem](http://chinesepoetryinenglishverse.blogspot.com/2013/12/blog-post_4784.html) from by Li Shangyin.

bors r+

### CODE REVIEW

File: crates/mbe/src/tests.rs [hunk 1]
```diff
@@ -969,6 +969,29 @@ fn test_meta_doc_comments() {
...
+                fn bar() {}
+            )
+        }
+"#,
+    ).
+    assert_expand_items(
+        r#"foo! {
+            /// 錦瑟無端五十弦，一弦一柱思華年。
+            /**
+                莊生曉夢迷蝴蝶，望帝春心託杜鵑。
```
Comment (matklad) [inline crates/mbe/src/tests.rs:988]: Хорошо!
