### PR TITLE
gen_assists_docs skip hidden files

### LINKED ISSUE #3670: `cargo test cli::generated_assists` fails when assist file open
This is a meta-issue related to development of assists. 

Running `cargo test cli::generated_assists` fails when any assist files are open. The cause of this issue is that my editor (vim) creates a temp file in the assists directory, which is picked up [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/src/codegen/gen_assists_docs.rs#L49) and then fails to read as UTF-8 [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/src/codegen/gen_assists_docs.rs#L60).

Potential fixes:

* Ignore gitignore'd files
  * This seems to be the most appropriate solution, but potentially would involve adding a dependency?
* Ignore files starting with `.`
  * This solves the problem for vim, but I'm not sure about other editors
* Provide a more descriptive error message including the file path that failed to be read as UTF-8
  * This doesn't solve the problem, but would likely provide enough information to allow the user to figure out how to move forward (likely just close the file in their editor)
* Any other options? 

I'd be happy to implement a fix, but I just wanted to discuss the options before making a PR with a particular solution.

### PR DESCRIPTION
**Pull request by JoshMcguigan**
Fixes #3670 

Skips hidden files when generating assist docs, which fixes an issue where the tests would fail while an editor has created a temp file in the assists directory.

There is similar logic [here](https://github.com/rust-analyzer/rust-analyzer/blob/2720e2374be951bb762ff2815dd67c7ffe3419b7/xtask/tests/tidy-tests/main.rs#L157), although in that case the `DirEntry` is a `walkdir::DirEntry` rather than a `fs::DirEntry`. Also, it's not immediately clear that it is worth moving this functionality to somewhere accessible from both of these places and creating dependencies in this way. Let me know if this is off the mark.

### CODE REVIEW

**Comment by matklad** [comment]
Could we share the code by adding `fn is_hidden(path: &Path)`?

**Comment by JoshMcguigan** [comment]
I pushed a change which re-uses the entire `rust_files` function. Let me know your thoughts on that.

File: xtask/src/codegen/gen_assists_docs.rs [hunk 1]
```diff
@@ -46,9 +46,7 @@ fn reveal_hash_comments(text: &str) -> String {
 
 fn collect_assists() -> Result<Vec<Assist>> {
     let mut res = Vec::new();
-    for entry in fs::read_dir(project_root().join(codegen::ASSISTS_DIR))? {
-        let entry = entry?;
-        let path = entry.path();
+    for path in rust_files(&project_root().join(codegen::ASSISTS_DIR)) {
         if path.is_file() {
```
Comment (matklad) [inline xtask/src/codegen/gen_assists_docs.rs]: I think we can now remove this if? Otherwise, r=me

bors d+

Comment (JoshMcguigan) [reply xtask/src/codegen/gen_assists_docs.rs]: Good catch, I've removed this `if`.
