### PR TITLE
Fix broken link in intra-doc

### LINKED ISSUE #5546: vscode links in the documentation pop-up do not work
Windows, latest vscode and rust versions:

`rustc 1.45.0 (5c1f21c3b 2020-07-13)`

Clicking on links to local documentation:

Capture

Links that open in the browser show this:

### PR DESCRIPTION
**Pull request by sasurau4**
Fix #5546 
The intra-doc link doesn't work fine for trait associated method.

### CODE REVIEW

File: crates/hir_def/src/resolver.rs [hunk 1]
```diff
@@ -145,6 +145,22 @@ impl Resolver {
...
     }
 
+    pub fn resolve_module_path_in_trait_items(
+        &self,
+        db: &dyn DefDatabase,
+        path: &ModPath,
+    ) -> Option<TraitId> {
+        let (item_map, module) = match self.module_scope() {
+            Some(it) => it,
+            None => return None,
```
Comment (edwin0cheng) [inline crates/hir_def/src/resolver.rs:155]:
```suggestion
        let (item_map, module) = self.module_scope()?;
```

**Comment by edwin0cheng** [comment]
Thanks!

bors r+
