### PR TITLE
Fix completion of Default struct update syntax

### LINKED ISSUE #6969: `..Default::default()` completion resolves to `...Default::default()` which is invalid
# Code to reproduce

```rust
struct Foo { x: usize }

fn main() {
  Foo {
    .   // right here
  }
}
```

RA suggests `..Default::default()`, but when clicked it resolves to `...Default::default()` which is syntactically invalid.

I looked at issues to see if this was already reported, apologies if i missed it 😄

### PR DESCRIPTION
**Pull request by nick96**
Previously the inserted text was always `..Default::default()` which ends up as `...Default::default()`
if `.` was typed. Now  checks if the current token is `.` and inserts `.Default::default()`
if it is, so `..Default::default()` is correctly completed.

I think there's probably a better way to implement this context aware completion because I've seen it in other parts of rust-analyzer as a user but I'm not sure how to do it.

Fixes #6969

### CODE REVIEW

File: crates/completion/src/completions/record.rs [hunk 1]
```diff
@@ -20,13 +20,18 @@ pub(crate) fn complete_record(acc: &mut Completions, ctx: &CompletionContext) ->
 
             let missing_fields = ctx.sema.record_literal_missing_fields(record_lit);
             if impl_default_trait && !missing_fields.is_empty() {
+                let completion_text = if ctx.token.to_string() == "." {
+                    ".Default::default()"
+                } else {
+                    "..Default::default()"
+                };
```
Comment (Veykril) [inline crates/completion/src/completions/record.rs:27]:
```suggestion
                let completion_text = "..Default::default()";
                let completion_text = completion_text.strip_prefix(ctx.token.text().as_str()).unwrap_or(completion_text);
```
This way we don't have to repeat the text twice

**Comment by Veykril** [comment]
It would probably nice to have a small test for this as well in regards to it properly inserting the snippet, by using `check_edit`, you can see how to use it in some other tests in the completions module.

**Comment by Veykril** [comment]
It would probably be nice to have a small test for this as well in regards to it properly inserting the snippet, by using `check_edit`, you can see how to use it in some other tests in the completions module. You can wrap it to make use of FamousDefs since the test requires knowledge about the `Default` trait, something like this should work:
```rust
    fn check_edit(what: &str, ra_fixture_before: &str, ra_fixture_after: &str) {
        test_utils::check_edit(
            what,
            &format!(
                "//- /main.rs crate:main deps:core\n{}\n{}",
                ra_fixture_before,
                FamousDefs::FIXTURE
            ),
            ra_fixture_after,
        );
    }
```
When you call it `what` would be `"..Default::default()"` then.

**Comment by Veykril** [comment]
Thanks!

bors r+
