### PR TITLE
Fix rename argument in macro call 

### LINKED ISSUE #3622: Fail to rename argument in macro call
Doing Rename Symbol/F2 in VS Code in argument of macro call show `The element can't be renamed` :

```rust
macro_rules! m {
    ($foo:ident) => {$foo}
}
fn main() {
    let foo = 1234;
    let _ = m!(fo<|>o);
}
```

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR fixes rename argument in macro call bug stated in #3622 and adds more helper functions related to `descend_into_macro` in `Semantic`.

Fixes #3622

### CODE REVIEW

File: crates/ra_hir/src/semantics.rs [hunk 1]
```diff
@@ -129,6 +141,8 @@ impl<'db, DB: HirDatabase> Semantics<'db, DB> {
             .kmerge_by(|node1, node2| node1.text_range().len() < node2.text_range().len())
     }
 
+    /// Find a AstNode by offset inside SyntaxNode, if it is inside *Macrofile*,
+    /// search up until it is target AstNode type
```
Comment (Veetaha) [inline crates/ra_hir/src/semantics.rs]:
```suggestion
    /// search up until it is of the target AstNode type
```

**Comment by matklad** [comment]
not sre what's up with bors this time
