### PR TITLE
Postfix completions like ifl now works with references

### LINKED ISSUE #7230: `ifl` postfix doesn't work on expressions with type `&Option<_>`

### PR DESCRIPTION
**Pull request by Maan2003**
Closes #7230

### CODE REVIEW

File: crates/completion/src/completions/postfix.rs [hunk 1]
```diff
@@ -30,11 +30,17 @@ pub(crate) fn complete_postfix(acc: &mut Completions, ctx: &CompletionContext) {
...
+    let mut receiver_ty = match ctx.sema.type_of_expr(&dot_receiver) {
         Some(it) => it,
         None => return,
     };
 
+    let mut ref_removed = false;
+    if let Some(removed) = receiver_ty.remove_ref() {
+        receiver_ty = removed;
+        ref_removed = true;
+    }
```
Comment (Veykril) [inline crates/completion/src/completions/postfix.rs:42]: We can get rid of this bool by just saving the ref stripped type in a different named variable, also this only removes one ref but we want to ideally remove all refs. Unwrapping here is fine since we always have a value at the start. Something like this:
```suggestion
    let no_ref_receiver_ty = std::iter::successors(Some(receiver_ty.clone()), |ty| ty.remove_ref()).unwrap();
```

**Review by Veykril — CHANGES_REQUESTED** [review]

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
bors r+
