### PR TITLE
Fix path resolution for module and function with same name

### LINKED ISSUE #3970: Use statement conflates module and function with the same name
image
Here `warp::reply` refers to both a function and a module. It is being used as a module in this case but hovering/semantic highlighting think that it is the function.

### PR DESCRIPTION
**Pull request by hasali19**
This fixes #3970 and also fixes completion for the same issue.

### CODE REVIEW

File: crates/ra_hir/src/semantics.rs [hunk 1]
```diff
@@ -451,6 +451,10 @@ impl<'a, DB: HirDatabase> SemanticsScope<'a, DB> {
     pub fn resolve_hir_path(&self, path: &Path) -> Option<PathResolution> {
         resolve_hir_path(self.db, &self.resolver, path)
     }
+
+    pub fn resolve_hir_path_qualifier(&self, path: &Path) -> Option<PathResolution> {
```
Comment (flodiebold) [inline crates/ra_hir/src/semantics.rs:455]: could you add a doc comment here? something like the one for the function in `source_analyzer`.
