### PR TITLE
fix: add for keyword in completion #7588

### LINKED ISSUE #7588: Add for keyword in completion
The `for` keyword isn't included in completion, I couldn't find any related issue for this.

### PR DESCRIPTION
**Pull request by gowrizrh**
Fixes #7588
bors r+

### CODE REVIEW

File: crates/completion/src/completions/keyword.rs [hunk 1]
```diff
@@ -88,6 +88,7 @@ pub(crate) fn complete_expr_keyword(acc: &mut Completions, ctx: &CompletionConte
         add_keyword(ctx, acc, "loop", "loop {$0}");
         add_keyword(ctx, acc, "if", "if $0 {}");
         add_keyword(ctx, acc, "if let", "if let $1 = $0 {}");
+        add_keyword(ctx, acc, "for", "for $0 in $1 {}");
```
Comment (Veykril) [inline crates/completion/src/completions/keyword.rs:91]:
```suggestion
        add_keyword(ctx, acc, "for", "for $1 in $0 {}");
```
We want the order swapped here, `$0` is always the last cursor position

Comment (gowrizrh) [reply crates/completion/src/completions/keyword.rs]: I've changed it, thank you for the suggestion 🙂!
