### PR TITLE
fix: Detect even a second change to `Cargo.toml`

### LINKED ISSUE #9546: Detect Cargo.toml changes from `cargo add`
**platform:** Windows 10 / VSCode 1.58.0 / RA v0.2.662

I like to use the command `cargo add` from cargo-edit to add dependencies to my projects but still need to manually touch the Cargo.toml file for RA to load its symbols. It would be nice if RA could detect those changes automatically.

### PR DESCRIPTION
**Pull request by lnicola**
Maybe fixes #9546

### CODE REVIEW

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/9546#issuecomment-877651681 and https://github.com/rust-analyzer/rust-analyzer/issues/9546#issuecomment-877803300 for motivation, though I don't recall the details very well :confused:.

**Comment by lnicola** [comment]
That's a fun CI error..

**Comment by lnicola** [comment]
bors try

File: crates/rust-analyzer/src/global_state.rs [hunk 1]
```diff
@@ -186,11 +186,9 @@ impl GlobalState {
             }
 
             for file in changed_files {
-                if file.is_created_or_deleted() {
-                    if let Some(path) = vfs.file_path(file.file_id).as_path() {
-                        fs_changes.push((path.to_path_buf(), file.change_kind));
-                        has_fs_changes = true;
```
Comment (matklad) [inline crates/rust-analyzer/src/global_state.rs:192]: I think this is not correct, or rather, doesn’t match the way this code indents do work.

fs_changes refers to changes to the file system itself, that is, addition or deletion of files. Changes to just file contents are not fs_changes.

motivation example here is that we should run cargo metadata when a new file is added to examples, but we shouldn’t re-run on every typing in this new file

Comment (lnicola) [reply crates/rust-analyzer/src/global_state.rs:192]: Reloading when editing `main.rs` doesn't happen in practice with this PR because of [this check](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/reload.rs#L85-L87) in `maybe_refresh`. And without this PR, a second edit to `Cargo.toml` is ignored, because the file is already in the VFS and the change doesn't get to `fs_changes`.

If the workspace reload is triggered by `maybe_refresh`, we need to get the `Cargo.toml` edit in there.

**Comment by lnicola** [comment]
r? @matklad

The first commit is the actual change, the second one moves some code around to avoid allocating a `Vec` (which probably isn't worth it TBH).

**Review by matklad — COMMENTED** [review]
Yup, the logic low looks reasonable!

**Comment by matklad** [comment]
r+ on the first commit -- the second one feels like it makes the code a bit weird. No strong oppinion though !

**Comment by lnicola** [comment]
I removed that function, so maybe it's a bit simpler now. Unfortunately, we can't trigger the refresh while holding the `vfs`.

bors r+
