### PR TITLE
Get some more array lengths!

### LINKED ISSUE #2922: "Insert explicit type" suggestion produces invalid code for array
For arrays, ra produces an invalid suggestion to insert `[T;_]`, where `T` is a concrete type, but `_` is literally an underscore, which is not valid in that position.

Example:

```rust
let x = [0.0; 3];
```

produces a suggestion that when applied results in

```rust
let x: [f64;_] = [0.0; 3];
```

which leads to the error message

```
error: expected expression, found reserved identifier `_`
   --> src/file.rs:line:col
    |
col |             let x: [f64;_] = [0.0; 3];
    |                 -       ^ expected expression
    |                 |
    |                 while parsing the type for `x`
```

### PR DESCRIPTION
**Pull request by lf-**
This is built on #8799 and thus contains its changes. I'll rebase it onto master when that one gets merged. It adds support for r-a understanding the length of:

* `let a: [u8; 2] = ...`
* `let a = b"aaa"`
* `let a = [0u8; 4]`

I have added support for getting the values of byte strings, which was not previously there. I am least confident in the correctness of this part and it probably needs some more tests, as we currently have only one test that exercised that part (!).

Fixes #2922.

### CODE REVIEW

**Comment by lf-** [comment]
I've force pushed a rebase of this onto the latest master and added some more examples to the test for byte strings. I now am more confident it's right. Ready for review :)

**Comment by Veykril** [comment]
I think after merging this we can also close #2922? Given that's not really an issue with the assist but just the fact that we have been ignoring const generics completely so far

**Comment by lf-** [comment]
> I think after merging this we can also close #2922? Given that's not really an issue with the assist but just the fact that we have been ignoring const generics completely so far

I'm not sure! We should write a test for that bug. It probably would, given r-a now *does* understand most arrays now, assuming there's not something like `[0u8; 2+2]`.

File: crates/hir_def/src/type_ref.rs [hunk 1]
```diff
@@ -79,7 +80,7 @@ pub enum TypeRef {
     Path(Path),
     RawPtr(Box<TypeRef>, Mutability),
     Reference(Box<TypeRef>, Option<LifetimeRef>, Mutability),
-    Array(Box<TypeRef> /*, Expr*/),
+    Array(Box<TypeRef>, ConstScalar),
```
Comment (flodiebold) [inline crates/hir_def/src/type_ref.rs:83]: well, this is quite hacky. I guess it's fine for now since it doesn't prevent us from making progress, but obviously we really should be lowering the array size expression properly. Can you add a FIXME comment that makes clear that this is a temporary solution?

File: crates/hir_def/src/type_ref.rs [hunk 2]
```diff
@@ -298,3 +304,44 @@ impl TypeBound {
         }
     }
 }
+
+/// A concrete constant value
```
Comment (flodiebold) [inline crates/hir_def/src/type_ref.rs:308]: when we implement array sizes more 'properly', we'll want to move this back to hir_ty or into its own crate. So maybe it makes sense to introduce a temporary type here that gets transformed to `ConstScalar` in hir_ty, like `ConstExpr` :thinking:

**Comment by flodiebold** [comment]
Can you check analysis-stats again? I'm a bit worried that this will lead to a regression because we don't support const generics yet, so now trait impls for arrays won't work anymore (inherent impls probably still will, due to the fact that our own unification algorithm doesn't care about the consts...)

**Comment by flodiebold** [comment]
(We probably don't have tests for things like `impl<T, const N: usize> AsRef<[T]> for [T; N] {}` because we don't support const generics, but the fact that we currently ignore array sizes makes these impls work anyway. Some tests for this might be good to add. Similarly `impl<T, const N: usize> [T; N] {}` itself, though there additionally it's also our unification at work, so it 'works' anyway.)

**Comment by lf-** [comment]
> Can you check analysis-stats again? I'm a bit worried that this will lead to a regression because we don't support const generics yet, so now trait impls for arrays won't work anymore (inherent impls probably still will, due to the fact that our own unification algorithm doesn't care about the consts...)

I did, it was not perceptibly changed...

> (We probably don't have tests for things like `impl<T, const N: usize> AsRef<[T]> for [T; N] {}` because we don't support const generics, but the fact that we currently ignore array sizes makes these impls work anyway. Some tests for this might be good to add. Similarly `impl<T, const N: usize> [T; N] {}` itself, though there additionally it's also our unification at work, so it 'works' anyway.)
> 
> A very hacky way of working around this for now might be to continue lowering array sizes to `Unknown` only in impls...
> 
> Edit: Ah wait, these sizes will be `Unknown` anyway, never mind... man_facepalming

OH WAIT, is *this* what the deciding that all unknown constants are equal for the purposes of chalk is accomplishing? 🤦🏻‍♀️  oh my.....

However, we're probably (?) getting the right trait more of the time now... Thankfully, since we're an IDE, we have more leeway to do stuff wrong 😆

I shall have to look at the rustc chalk code again to try to understand how they're handling concrete constants.

**Comment by flodiebold** [comment]
> I shall have to look at the rustc chalk code again to try to understand how they're handling concrete constants.

So, from the discussion in Zulip, it seems that Chalk is missing a piece to handle unevaluated constants. So `ConcreteConst` is really just an actualy value, and unevaluated / unevaluatable constants would be represented differently. I think for us, we'll need to keep `ConstValue::Unknown` at least for now, and hope that the fact that our `const_eq` isn't transitive won't pose too many problems. Once we can handle Const inference variables, we can probably use them in many cases to handle expressions that we can't evaluate yet, but that won't help in type definitions or impls.

File: crates/hir_def/src/type_ref.rs (hunk 1 above)
Comment (lf-) [reply crates/hir_def/src/type_ref.rs:85]: Added.

File: crates/hir_def/src/type_ref.rs (hunk 2 above)
Comment (lf-) [reply crates/hir_def/src/type_ref.rs:314]: Yeah. I've added some comments around the place. I see what you mean by it being not really ideal that we have any const evaluation in hir_def. I think that we can reuse the lowering code for arrays, but currently I'm unsure if we can get the right state into that spot to be able to do expression evaluation/lowering.

File: crates/hir_ty/src/infer/expr.rs [hunk 3]
```diff
@@ -758,11 +769,18 @@ impl<'a> InferenceContext<'a> {
                     TyKind::Ref(Mutability::Not, static_lifetime(), TyKind::Str.intern(&Interner))
                         .intern(&Interner)
                 }
-                Literal::ByteString(..) => {
+                Literal::ByteString(bs) => {
                     let byte_type = TyKind::Scalar(Scalar::Uint(UintTy::U8)).intern(&Interner);
 
-                    let array_type =
-                        TyKind::Array(byte_type, dummy_usize_const()).intern(&Interner);
+                    let len = ConstData {
```
[the remark this answers is not in the document]
Comment (lf-) [reply crates/hir_ty/src/infer/expr.rs]: Done.

File: crates/hir_ty/src/infer/expr.rs [hunk 4]
```diff
@@ -737,16 +741,23 @@ impl<'a> InferenceContext<'a> {
                                 TyKind::Scalar(Scalar::Uint(UintTy::Usize)).intern(&Interner),
                             ),
                         );
-                        // FIXME: support length for Repeat array expressions
-                        None
+
+                        let repeat_expr = &self.body.exprs[*repeat];
+                        match repeat_expr {
```
[the remark this answers is not in the document]
Comment (lf-) [reply crates/hir_ty/src/infer/expr.rs]: Done.

File: crates/hir_ty/src/lower.rs [hunk 5]
```diff
@@ -172,11 +173,16 @@ impl<'a> TyLoweringContext<'a> {
...
                 let inner_ty = self.lower_ty(inner);
-                // FIXME: we don't have length info here because we don't store an expression for
-                // the length
-                TyKind::Array(inner_ty, dummy_usize_const()).intern(&Interner)
+
+                let const_len = ConstData {
+                    ty: TyKind::Scalar(Scalar::Uint(UintTy::Usize)).intern(&Interner),
+                    value: ConstValue::Concrete(chalk_ir::ConcreteConst { interned: *len }),
+                }
+                .intern(&Interner);
```
Comment (flodiebold) [inline crates/hir_ty/src/lower.rs:183]: this can be a call to `usize_const`?

File: crates/hir_ty/src/consteval.rs [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+use hir_def::{
+    builtin_type::BuiltinUint,
+    expr::{Expr, Literal},
+    type_ref::ConstScalar,
+};
+
+use crate::{Const, ConstData, ConstValue, Interner, TyKind};
+
+/// Extension trait for [`Const`]
+pub trait ConstExtension {
```
Comment (flodiebold) [inline crates/hir_ty/src/consteval.rs:14]: I think usually we'd call this `ConstExt`

File: crates/hir_ty/src/consteval.rs [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+            _ => {
+                log::error!("is_unknown was called on a non-concrete constant value! {:?}", self);
+                true
+            }
+        }
+    }
+}
+
+/// Extension trait for [`Expr`]
+pub trait ExprEval {
```
Comment (flodiebold) [inline crates/hir_ty/src/consteval.rs:39]: I'm not sure why this needs to be an extension trait, as opposed to just a function?

**Comment by flodiebold** [comment]
bors d+
