### PR TITLE
Fix error when using "extern crate self as"

### LINKED ISSUE #6957: Unresolved import when using "extern crate self as"
I created new project using `cargo init --lib`, and wrote following code in `src/lib.rs`

```rs
extern crate self as x;
pub struct A;
pub use x::A as B;
pub use crate::A as C;
```

Then an unresolved import error occurred at line 3.

### PR DESCRIPTION
**Pull request by kazatsuyu**
Fix #6957

### CODE REVIEW

File: crates/hir_def/src/nameres/path_resolution.rs [hunk 1]
```diff
@@ -63,6 +64,12 @@ impl ResolvePathResult {
 
 impl DefMap {
     pub(super) fn resolve_name_in_extern_prelude(&self, name: &Name) -> PerNs {
+        if name == &name!(self) {
+            return PerNs::types(
```
Comment (matklad) [inline crates/hir_def/src/nameres/path_resolution.rs:68]: let's add `mark::hit!(extern_crate_self_as)` here: https://github.com/rust-analyzer/rust-analyzer/blob/e54a398bfbe864223e20e8a1f526b434e1c89164/docs/dev/style.md#marked-tests

bors d+
