### PR TITLE
Draft: Show reason for failed rename refactoring

### LINKED ISSUE #3981: Invalid renames should say why they failed
Invalid renames are already rejected, but if possible they should say why, too.

Currently, for VSCode at least, an info box saying "No result." pops up, and thats it. I was unintentionally trying to rename something to a keyword, but it took a few minutes to figure out that I was doing something wrong, not rust-analyzer.

### PR DESCRIPTION
**Pull request by rherrmann**
Return an error with a meaningful message for requests to
`textDocument/rename` if the operation cannot be performed.
Pass errors, raised by rename handling code to the LSP runtime.

As a consequence, the VS Code client shows and logs the request
as if a server-side programming error occured.
Screenshot of a rename error showing in VS Code
invalid-rename-ui

I would kindly ask to get feedback from the maintainers if they can spare the time:
* Is the general direction of the proposed changes acceptable?
* I'm new to Rust. The code feels clumsy and redundant, please suggest improvements
if you find the time for. E.g. is there a simple replacement for `RenameError`?
* Should presenting the error with proper severity (i.e. not as a programming error) be part of this change or in a followup change?

See https://github.com/rust-analyzer/rust-analyzer/issues/3981

### CODE REVIEW

File: crates/ide/src/lib.rs [hunk 1]
```diff
@@ -479,7 +479,7 @@ impl Analysis {
         &self,
         position: FilePosition,
         new_name: &str,
-    ) -> Cancelable<Option<RangeInfo<SourceChange>>> {
+    ) -> Cancelable<Result<Option<RangeInfo<SourceChange>>, Box<dyn Error + Send + Sync>>> {
```
Comment (matklad) [inline crates/ide/src/lib.rs:482]: I think the right signature here should be 

```rust
Cancelable<Result<RangeInfo<SourceChange>, RenameError>>
```

that is,

* use concrete type for an error
* fold `None` into one variant of `Error`

File: crates/ide/src/references/rename.rs [hunk 2]
```diff
@@ -20,29 +20,66 @@ use crate::{
     SourceChange, SourceFileEdit, TextRange, TextSize,
 };
 
+#[derive(Debug)]
+pub(crate) struct RenameError(pub(crate) String);
+
+impl RenameError {
+    pub(crate) fn new<T: Into<String>>(message: T) -> RenameError {
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:27]: This can be private, and I think doesn't need `Into` polymorphism: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#avoid-monomorphization

File: crates/ide/src/references/rename.rs [hunk 3]
```diff
@@ -20,29 +20,66 @@ use crate::{
...
+        RenameError(message.into())
+    }
+}
+
+impl std::fmt::Display for RenameError {
+    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
+        write!(f, "{}", self.0)
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:34]: I usually write this as `fmt::Display::fmt(&self.0, f)`, to makes sure that all formatter flags are properly forwarded.

File: crates/ide/src/references/rename.rs [hunk 4]
```diff
@@ -280,7 +317,10 @@ mod tests {
     fn check(new_name: &str, ra_fixture_before: &str, ra_fixture_after: &str) {
         let ra_fixture_after = &trim_indent(ra_fixture_after);
         let (analysis, position) = analysis_and_position(ra_fixture_before);
-        let source_change = analysis.rename(position, new_name).unwrap();
+        let source_change = match analysis.rename(position, new_name) {
+            Ok(source_change) => source_change.unwrap(),
+            Err(err) => panic!("Rename to '{}' failed unexpectedly: {}", new_name, err),
+        };
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:323]: This could use `.unwrap_or_else(|err| panic!())`

**Review by matklad — COMMENTED** [review]
Yup, the general direction seems right to me, left a couple of comments.

File: crates/ide/src/lib.rs (hunk 1 above)
Comment (rherrmann) [reply crates/ide/src/lib.rs:482]: I've applied your proposal and turned `None` into errors. A few open questions remain, though. I left corresponding TODO comments in the latest commit.

File: crates/ide/src/references/rename.rs [hunk 5]
```diff
@@ -246,26 +291,30 @@ fn rename_self_to_param(
...
+        None => return Err(RenameError::new("No reference found to rename")),
+    };
 
     let edit = refs
         .into_iter()
         .map(|reference| source_edit_from_reference(reference, new_name))
         .collect::<Vec<_>>();
 
+    // TODO Can this ever happen? When does `find_all_refs` return an empty `refs.into_iter()`?
     if edit.is_empty() {
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:313]: I think for cases like

```rust
let _ = unresovled_references;
```

you won't get any usages or declarations.

File: crates/ide/src/references/rename.rs [hunk 6]
```diff
@@ -313,11 +366,36 @@ mod tests {
...
+            "Invalid name 'multiple tokens': not an identifier",
+            source_change.err().unwrap().to_string()
+        );
+    }
+
+    #[test]
+    fn test_rename_to_invalid_identifier3() {
+        let (analysis, position) = analysis_and_position(r#"fn main() { let i<|> = 1; }"#);
+        let new_name = "let";
+        let source_change = analysis.rename(position, new_name).unwrap();
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:394]: Instead of doing all this manually, let's extend the `check` function to errors as well:

```rust
check("let", r"
fn main() { let i<|> = 1; }
", "
error: Invalid name `let`: not an identifier
")
```

File: crates/ide/src/references/rename.rs [hunk 7]
```diff
@@ -313,11 +366,36 @@ mod tests {
...
+        assert_eq!(
+            "Invalid name 'let': not an identifier",
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:396]:
```suggestion
            "Invalid name `let`: not an identifier",
```

we use backticks to surround code.

File: crates/rust-analyzer/src/handlers.rs [hunk 8]
```diff
@@ -621,14 +621,17 @@ pub(crate) fn handle_prepare_rename(
...
-    let range = match optional_change {
-        None => return Ok(None),
-        Some(it) => it.range,
+    let change = match snap.analysis.rename(position, "dummy")? {
+        Ok(optional_change) => optional_change,
+        Err(err) => {
+            return Ok(Some(PrepareRenameResponse::RangeWithPlaceholder {
+                range: Range::default(),
+                placeholder: err.to_string(),
+            }))
```
Comment (matklad) [inline crates/rust-analyzer/src/handlers.rs:630]: I think we should return an `Err` response here, according to the protocol?

https://microsoft.github.io/language-server-protocol/specification#textDocument_prepareRename

> error: code and message set in case the element can’t be renamed. Clients should show the information in their user interface.

File: crates/ide/src/references/rename.rs [hunk 9]
```diff
@@ -125,51 +160,59 @@ fn rename_mod(
...
     if params.self_param().is_some() {
-        return None; // method already has self param
+        return Err(RenameError::new("Method already has a self parameter"));
     }
-    let first_param = params.params().next()?;
+    let first_param = params
+        .params()
+        .next()
+        // TODO How to avoid duplicate error messages? Using an enum?
+        .ok_or_else(|| RenameError::new("Method has no parameters"))?;
```
[the remark this answers is not in the document]
Comment (rherrmann) [reply crates/ide/src/references/rename.rs:200]: I'm struggling with this: 

The struct is currently defined as `RenameError(pub(crate) String)`. How should it look like to be used like `RenameError("Method has no parameters")`? Or should callers write `RenameError("Method has no parameters".into())`?

I tried `RenameError(pub(crate) &str)` but ended up adding lifetime parameters everywhere.

[the remark this answers is not in the document]
Comment (lnicola) [reply crates/ide/src/references/rename.rs:200]: You could use `&'static str` like it's done other places, but it doesn't lead to great error reporting IMHO.

[the remark this answers is not in the document]
Comment (rherrmann) [reply crates/ide/src/references/rename.rs:200]: Though, in most environments, globally static things should be avoided, I don't feel versed enough in Rust to make this decision. Should I leave it at `RenameError::new("...")` for now? It seems as verbose as `RenameError("...".into())`.

[the remark this answers is not in the document]
Comment (lnicola) [reply crates/ide/src/references/rename.rs:200]: That's not really a global static value, it's a reference to a string slice that lives for the full duration of the program. They're almost always string literals (e.g. `"foo"`).

**Comment by kjeremy** [comment]
FWIW The dart implementation defines a custom [LSP error code](https://github.com/dart-lang/sdk/blob/a7cb764aa457cedf07f7a0e73b86d34bcc6d2e5a/pkg/analysis_server/lib/src/lsp/constants.dart#L92) for a failed rename operation. You can see their rename method [here](https://github.com/dart-lang/sdk/blob/a7cb764aa457cedf07f7a0e73b86d34bcc6d2e5a/pkg/analysis_server/lib/src/lsp/handlers/handler_rename.dart#L83-L169).

File: crates/ide/src/references/rename.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (rherrmann) [reply crates/ide/src/references/rename.rs]: I've pushed a new version of this PR. It should resolve all pending comments (please reopen if I missed something or introduced a new issue), except this one.

Here I'm still struggling with a few occurrences like this: `RenameError::new(format!("Invalid name `{}`: not an identifier", new_name).as_str())`. 
After applying the changes to conform with the declaration of `RenameError(pub(crate) &'static str)`, I see compile errors like `temporary value dropped while borrowed` and `does not live long enough`. How should I turn the result of `format` into a `&'static str`?

File: crates/ide/src/references/rename.rs [hunk 10]
```diff
@@ -20,17 +20,51 @@ use crate::{
     SourceChange, SourceFileEdit, TextRange, TextSize,
 };
 
+#[derive(Debug)]
+pub struct RenameError(pub(crate) String);
+
+impl RenameError {
+    fn new(message: &str) -> RenameError {
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:27]: As per https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#premature-pessimization, this should be `message: String`. But given that would be just `RenameError()`, I think we should just remove the `new` function.

File: crates/ide/src/references/rename.rs [hunk 11]
```diff
@@ -20,17 +20,51 @@ use crate::{
...
+        RenameError(String::from(message))
+    }
+}
+
+impl Display for RenameError {
+    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
```
Comment (matklad) [inline crates/ide/src/references/rename.rs:33]: Minor, but we generally import `fmt`: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#import-style

**Review by matklad — COMMENTED** [review]
LGTM, left just a copule of non-essential nits. Removing the `RenameError::new` function and just fixing the call-sites should resolve the `&'static str` discussion

bors d+

**Comment by matklad** [comment]
Thanks @rherrmann !

**Comment by jyn514** [comment]
This looks awesome, thanks so much! I've wanted this a few times but never got around to opening an issue.
