### PR TITLE
Fix EnumVariants not showing properly when hovering

### LINKED ISSUE #950: Hover on EnumVariant doesn't show documentation
```rust
enum Option<T> {
    /// The Some Variant
    Some(T)
}

fn main() {
    Option::So<|>me(0);
}
```

Currently "The Some Variant" does not show up on hover.

### PR DESCRIPTION
**Pull request by vipentti**
This fixes #950 

This also fixes hovering over the name of an EnumVariant.

Additionally this changes the way enum variants are shown, now instead of the `Some<T>... -> Option` you just get `Some`. I'm not sure what would be the optimal display for enum variants in this case.

### CODE REVIEW

File: crates/ra_ide_api/src/hover.rs [hunk 1]
```diff
@@ -240,6 +241,7 @@ impl NavigationTarget {
             .visit(|node: &ast::ConstDef| visit_ascribed_node(node, "const "))
             .visit(|node: &ast::StaticDef| visit_ascribed_node(node, "static "))
             .visit(|node: &ast::NamedFieldDef| visit_ascribed_node(node, ""))
+            .visit(|node: &ast::EnumVariant| Some(node.name()?.syntax().text().to_string()))
```
Comment (matklad) [inline crates/ra_ide_api/src/hover.rs]: There's `text` method directly on `ast::Name`:

```
impl Name {
    pub fn text(&self) -> &SmolStr {
        let ident = self.syntax().first_child().unwrap();
        ident.leaf_text().unwrap()
    }
}
```
