### PR TITLE
Fix fill_match_arms not working with references

### LINKED ISSUE #881: fill match arm should see through references
The following works (there's "fill match arm" in code action list, and it fills variants):

```
    fn convert_tt(&mut self, tt: &tt::TokenTree) {
        match *tt {

        }
    }
```

This does not work (no intention is available):

```
fn convert_tt(&mut self, tt: &tt::TokenTree) {
        match tt {

        }
    }
```

The second case should work just the first one, due to match ergonomics. 

I think in this line we should peel off all references: 

https://github.com/rust-analyzer/rust-analyzer/blob/38add103c3f30493e336a37827a76f48a6e7c584/crates/ra_assists/src/fill_match_arms.rs#L29-L32

### PR DESCRIPTION
**Pull request by vipentti**
This fixes #881

### CODE REVIEW

File: crates/ra_assists/src/fill_match_arms.rs [hunk 1]
```diff
@@ -119,6 +123,105 @@ mod tests {
...
+    fn test_fill_match_arm_refs() {
+        check_assist(
+            fill_match_arms,
+            r#"
+            enum A {
+                As,
+                Bs,
+                Cs(String),
+                Ds(String, String),
+                Es{x: usize, y: usize}
```
Comment (matklad) [inline crates/ra_assists/src/fill_match_arms.rs]: Let's use enum with just one variant for this test? Match ergonomics should be orthogonal to variants generation, and having smaller tests is useful!

**Comment by matklad** [comment]
bors r+

Thanks!
