### PR TITLE
decl_check: consider outer scopes' allows

### LINKED ISSUE #8417: incorrect-ident-case doesn't look at #[allow()]s of parent scopes
Example: set the crate attribute or module attribute of `#![allow(non_upper_case_globals)]` and put an associated const on a trait, RA will report incorrect-ident-case, which it should not, as it does actually consider `non_upper_case_globals` (see `decl_check.rs`), just not recursively upwards.

```rust
#![allow(non_upper_case_globals)]
fn a() {
trait F {
    const haha_im_bad: bool = true;
}
}
```

### PR DESCRIPTION
**Pull request by lf-**
Fix #8417. Also makes it less noisy about no_mangle annotated stuff the
user can do nothing about.

Note: this still is broken with bitfield! macros. A repro in an ignore
test is included here. I believe this bug is elsewhere, and I don't
think I can work around it here.

I would like help filing the remaining bug, as it does actually affect
users, but I don't know how to describe the behaviour (or even if it
is unintended).

### CODE REVIEW

File: crates/hir_ty/src/diagnostics/decl_check.rs [hunk 1]
```diff
@@ -888,6 +946,60 @@ fn main() {
...
+        // * validate_func on `a` recursing into modules
+        // * then it finds the trait and then the function while iterating
+        //   through modules
+        // * then validate_func is called on Dirty
+        // * ... which then proceeds to look at some unknown module taking no
+        //   attrs from either the impl or the fn a, and then finally to the root
+        //   module
+        //
+        // It should find the attribute on the trait, but it *doesn't even see
+        // the trait* as far as I can tell.
```
Comment (jonas-schievink) [inline crates/hir_ty/src/diagnostics/decl_check.rs:980]: Ah, this is probably because we don't really support function-local traits and impls yet

File: crates/hir_ty/src/diagnostics/decl_check.rs [hunk 2]
```diff
@@ -869,10 +901,36 @@ fn main() {
...
+
+    mod F {
+        #![allow(non_snake_case)]
+        fn CheckItWorksWithModAttr(BAD_NAME_HI: u8) {}
+    }
+
+    trait BAD_TRAIT {
+        fn BAD_FUNCTION();
+        fn BadFunction();
+    }
```
Comment (jonas-schievink) [inline crates/hir_ty/src/diagnostics/decl_check.rs:932]: Why don't we report anything here? Was this preexisting?

Comment (lf-) [reply crates/hir_ty/src/diagnostics/decl_check.rs:932]: As far as I know, yes. It's because the trait isn't visited in the pass that picks up the items, which I haven't changed. I put it there more to document the current behaviour but I probably should move it to make it clear it's not intentional and should not be preserved.

File: crates/hir_ty/src/diagnostics/decl_check.rs (hunk 1 above)
Comment (lf-) [reply crates/hir_ty/src/diagnostics/decl_check.rs:980]: I almost wonder if we should delete the part of this lint that recurses into functions to pick up items then, because we generate unavoidable warnings on bitfield macro output, that rustc ignores appropriately but we don't. It's unclear to me what a module is, in the terminology of the RA program representation, so I'm unsure what it's even trying to pick up by doing this recursion.

File: crates/hir_ty/src/diagnostics/decl_check.rs (hunk 2 above)
Comment (jonas-schievink) [reply crates/hir_ty/src/diagnostics/decl_check.rs:932]: Yeah, if you could add a FIXME comment that'd be great

File: crates/hir_ty/src/diagnostics/decl_check.rs (hunk 1 above)
Comment (jonas-schievink) [reply crates/hir_ty/src/diagnostics/decl_check.rs:980]: I think it shouldn't be very hard to fix this, which we should do anyways (so we get IDE functionality in local impls). Though I haven't gotten a chance to look into that yet.

**Comment by lf-** [comment]
@jonas-schievink ready for re-review

**Comment by jonas-schievink** [comment]
Thanks!

bors r+
