### PR TITLE
fix: don't discard formatting of `use` lines

### LINKED ISSUE #9013: Rewrite import merging to use mutable syntax trees
Our improt merging logic currently takes two import trees and recursively zips together a new one from them, this causes us to completely discard the previous two trees including any kind of order of the imports inside of them, which might be unwanted by the user.

Now that we got mutable trees though we should be able to reimplement that while also getting rid of some rather complex and difficult to read code.

Relevant code to replace/rewrite:
https://github.com/rust-analyzer/rust-analyzer/blob/bb1c7fc0cfe24a8477d943faa932992b9cd48957/crates/ide_db/src/helpers/merge_imports.rs#L74-L181

### LINKED ISSUE #9361: Autoimport discards formatting of `use` lines
Consider a file that looks like this:

```rust
use std::{
    collections::HashMap,
    convert::TryFrom,
    ffi::OsStr,
    fmt::Display,
    fs::File,
    io::{self, BufReader, Write},
};

fn main() {
    let a = Ordering::Less;
}
```

The `Ordering` type in main isn't imported, so RA provides the option to automatically import it.  If you allow rust-analyzer to import `Ordering`, it will rewrite the first line to look like:

```rust
use std::{cmp::Ordering, collections::HashMap, convert::TryFrom, ffi::OsStr, fmt::Display, fs::File, io::{self, BufReader, Write}};
```
Which removes the original formatting.  In this particular case, the original formatting can be restored by running rustfmt, but the fact that RA doesn't respect the original formatting can be annoying when looking at diffs, and is a minor papercut

### PR DESCRIPTION
**Pull request by iDawer**
Use mutable syntax trees in `merge_imports`, `split_imports`. This tries to resolve #9013. But I haven't much managed to simplify code of merging.

Also resolve #9361. It reuses a use tree under the cursor so that comments+indentation are preserved. Merged trees are just appended to the end.

This touches bunch of tests. I removed the sorting of use trees as it needs a proper implementation that takes into account comments and line wrapping. I think it is rustfmt's job or at least until we get a close implementation.

### CODE REVIEW

File: crates/ide_db/src/helpers/merge_imports.rs [hunk 1]
```diff
@@ -56,57 +56,49 @@ pub fn try_merge_trees(
...
         // We use Option here to early return from this function(this is not the
         // same as a `filter` op).
-        .map(|tree| match merge.is_tree_allowed(&tree) {
-            true => Some(tree),
-            false => None,
-        })
-        .collect::<Option<Vec<_>>>()?;
+        .map(|tree| merge.is_tree_allowed(&tree).then(|| tree))
+        .collect::<Option<_>>()?;
     use_trees.sort_unstable_by(|a, b| path_cmp_for_sort(a.path(), b.path()));
```
Comment (Veykril) [inline crates/ide_db/src/helpers/merge_imports.rs:92]: Do we even need the sort(+ binary search later) now? Since we don't insert in a sorted manner anyways I don't think its needed anymore

Comment (iDawer) [reply crates/ide_db/src/helpers/merge_imports.rs:92]: My thinking was to keep sensible lookup performance in extreme cases

Comment (iDawer) [reply crates/ide_db/src/helpers/merge_imports.rs:92]: I've reread the question :smile: We need to lookup `lhs` subtrees to find an already present one to recurse into.
