### PR TITLE
fix: Remove incorrectly filtering VS Code cargo task execution resolution by scope

### LINKED ISSUE #9093: 'There is no task provider registered for tasks of type "cargo".' in VS Code code-workspaces
In version 0.2.620 & 0.2.621 Cargo tasks configured using a VS Code `.code-workspace` file appear to not be working; rolling back to 0.2.612 does not have this issue. The workspace does have multiple root folders.

When attempting to run one I get an error notification stating: `There is no task provider registered for tasks of type "cargo".`
the following is shown also shown in the 'Tasks' output:

```
Error: The cargo task detection didn't contribute a task for the following configuration:
{
    "type": "cargo",
    "command": "build",
    "problemMatcher": [
        "$rustc"
    ],
    "group": "build",
    "label": "in .code-workspace"
}
The task will be ignored.
```

`.code-workspace` configured as such:
```json
{
  "tasks": {
    "version": "2.0.0",
    "tasks": [
      {
        "type": "cargo",
        "command": "build",
        "problemMatcher": [
          "$rustc"
        ],
        "group": "build",
        "label": "in .code-workspace"
      }
    ]
  }
}
```

Strangely tasks work fine from a `tasks.json` file though.
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "cargo",
      "command": "build",
      "problemMatcher": [
        "$rustc"
      ],
      "group": "build",
      "label": "in tasks.json"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by oeed**
This fixes #9093 ​introduced by #8995.

A filter was present on the function that adds the execution definition to Cargo tasks. This would mean Cargo tasks defined in workspaces (i.e. `.code-workspace` files) would not be given an execution, leading to a `There is no task provider registered for tasks of type "cargo".` error as descibed in #9093. I have made a minimum reproduction setup [here](https://github.com/oeed/ra-workspace).

This PR essentially removes that check. The `if (scope) { ... }` is to handle the case where `task.scope === undefined` using a deprecated constructor. I'm not sure if that is ever likely to occur and can remove if not needed.

There is some discussion about whether it's necessary to filter the tasks before building them. From my understanding, it shouldn't be needed as we should provide an execution for all `cargo` tasks; but I'm not overly familiar with VS Code internals so I could be wrong. For more info please see [the discussion](https://github.com/rust-analyzer/rust-analyzer/pull/8995#issuecomment-908920395) on #8995

### CODE REVIEW

**Comment by oeed** [comment]
It's worth noting that I've never touched VS Code extensions before; so take these changes with an huge grain of salt. There's definitely an issue, but maybe `isWorkspaceFolder` just needs to account for workspace scopes instead? I'm not familiar enough to know.

File: editors/code/src/tasks.ts [hunk 1]
```diff
@@ -115,14 +109,26 @@ export async function buildCargoTask(
...
+            scope,
+            name,
+            TASK_SOURCE,
+            exec,
+            ['$rustc']
+        );
+    }
+    else {
+        // if the original task did not provide a scope retain the original lack of scope
+        return new vscode.Task(
```
Comment (SomeoneToIgnore) [inline editors/code/src/tasks.ts:124]: This constructor is considered deprecated: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts#L6743

> * @deprecated Use the new constructors that allow specifying a scope for the task.

So looks like VSCode forces everybody to explicitly define a workspace folder for every task.

I'm not entirely thrilled to start using deprecated APIs, so would personally concentrate on deriving the folder instead.
Seems unfair to block you too, so if somebody else feels fine, he can merge the PR.

**Comment by SomeoneToIgnore** [comment]
I've tried to elaborate more on the changes that caused this: https://github.com/rust-analyzer/rust-analyzer/pull/8995#issuecomment-909040741

So looks like VSCode pushes everybody to explicitly specify the workspace folder for every task the plugins create (as it seems from the constructor deprecation mentioned above).

With this requirement, for user defined rust tasks and multiworkspace project, we have to default to some workspace folder, either picking the first (which effectively negates part of the https://github.com/rust-analyzer/rust-analyzer/pull/8995 reason behind described in https://github.com/rust-analyzer/rust-analyzer/pull/8955#discussion_r637848017) or find a better way to get that folder somehow.

File: editors/code/src/tasks.ts (hunk 1 above)
Comment (oeed) [reply editors/code/src/tasks.ts:124]: Ah I see, so was your comment [here](https://github.com/rust-analyzer/rust-analyzer/pull/8995#issuecomment-909040741):
> Now, the biggest task is to determine the folder that should apply for your custom configuration since I did not take such cases into account.

about how to handle `scope === undefined`?

In that case I assumed that it should simply 'add on' the necessary parts to the task, and if the original task didn't have a scope then simply leave it undefined. From what I've seen, the function doesn't need to use the scope and so if it doesn't have one it just passes that lack of scope onwards. But once again, I've little understanding of what's going on here.

Alternatively could the check instead be `if (scope === undefined)`?

Comment (SomeoneToIgnore) [reply editors/code/src/tasks.ts:124]: You've got the idea right: it's all about the `scope === undefined` for tasks that come from user configurations (in your case).

The fix logic can be anything that fixes things for you and preferrably is not deprecated/super hacky 🙂 
I see that the scope can be `scope: WorkspaceFolder | TaskScope.Global | TaskScope.Workspace` so I wonder, if the `TaskScope.Workspace` variant a right thing to fix your issues?

Comment (oeed) [reply editors/code/src/tasks.ts:124]: `TaskScope.Workspace` is indeed the scope that the tasks are given, the comments on `TaskScope.Global` seem to imply it's not used currently.

**Comment by oeed** [comment]
Any further thoughts on this one? Happy to modify to skip tasks that have an undefined scope if that's the right path?

**Comment by matklad** [comment]
Not dug deep into this, but here's what I'd do:

* return `undefined` if the scope is undefined, as per `resolveTask` docs
* if that causes real problems, raise vscode issue asking why VS Code calls us with undefined scopes at all. 

Alternatively, *why* we are returning a new task here? Can't we just set the fields of the task we are given?

**Comment by oeed** [comment]
My intention with using the deprecated constructor was to essentially just modify the task as is.

That's a great point though, there's no reason the function can't just set the exec on the existing task to my eyes. Can change it to do that if in agreement.

**Comment by matklad** [comment]
We definitely should not call deprecated functions. Other than that —
whatever gets the job done!

**Comment by oeed** [comment]
Setting `task.execution` [clears the scope](https://github.com/microsoft/vscode/blob/b699fab482cb58beb9b0ac4a84a702fc8cbb7166/src/vs/workbench/api/common/extHostTypes.ts#L2211) and results in the same error.

The [official docs](https://code.visualstudio.com/api/extension-guides/task-provider#task-provider) on the subject explicitly make a new task rather and use `task.scope ?? vscode.TaskScope.Workspace` to compensate for an undefined scope. I've implemented this in the above commit and from my testing works correctly without needing deprecated functions.

So this should be good for a final check I believe.

**Comment by SomeoneToIgnore** [comment]
So, looks like we've ended up with pretty much what was suggested in https://github.com/rust-analyzer/rust-analyzer/pull/10093#discussion_r699140675 , great that it was as simple as expected.

Thank you for looking into that.
One last thing, if you want to: we can add a comment somewhere around `buildCargoTask` function to explain what is happening with the scope and why we set it so (your case may not so clear for people who had never dealt with predefined configs, better warn them before they twist the logic on the next refactoring)

But this is minor, feel free to `r+` and merge the current changes if you've had enough of this already.


bors d+

**Comment by lnicola** [comment]
changelog fix (first contribution) fix cargo task filtering in Code workspaces
