### PR TITLE
fix: Refactor & improve handling of overloaded binary operators

### LINKED ISSUE #9971: Normalization issue with operators or `Deref`
CC #8961

```rust
let s = String::new() + &String::new(); // s is <String as Add<String>>::Output
```

### PR DESCRIPTION
**Pull request by flodiebold**
Fixes #9971. Also records them as method resolutions, which we could use later.

### CODE REVIEW

File: crates/hir_ty/src/infer/expr.rs [hunk 1]
```diff
@@ -669,34 +672,21 @@ impl<'a> InferenceContext<'a> {
...
+                    self.infer_expr_coerce(*rhs, &Expectation::has_type(lhs_ty));
+                    self.result.standard_types.unit.clone()
+                }
+                Some(BinaryOp::LogicOp(_)) => {
+                    let bool_ty = self.result.standard_types.bool_.clone();
+                    self.infer_expr_coerce(*lhs, &Expectation::HasType(bool_ty.clone()));
+                    let lhs_diverges = self.diverges;
+                    self.infer_expr_coerce(*rhs, &Expectation::HasType(bool_ty.clone()));
+                    // Depending on the LHS' value, the RHS can never execute.
+                    self.diverges = lhs_diverges;
```
Comment (lnicola) [inline crates/hir_ty/src/infer/expr.rs:686]: Should this be `self.diverges &= lhs_diverges;`? For cases like `true && loop {}`.

Comment (flodiebold) [reply crates/hir_ty/src/infer/expr.rs:686]: No, that would still only 'maybe' diverge.
