### PR TITLE
Fix generic type substitution in impl trait with assoc type

### LINKED ISSUE #11045: "Implement missing members" generates trait name instead of associated types if these have the same name
In this code:

```rust
pub trait Foo {}

pub trait Types {
    // Associated type with the same as a trait in the scope.
    type Foo;
}

pub trait Behavior<T: Types> {
    // Using associated type as a parameter.
    fn reproduce(&self, foo: T::Foo);
}

pub struct Impl;

impl<T: Types> Behavior<T> for Impl {}
```

when I use "implement missing members" assist on the last line, this gets generated:

```rust
impl<T: Types> Behavior<T> for Impl {
    fn reproduce(&self, foo: Foo) {
        todo!()
    }
}
```

That is, the trait `Foo` is used in place where `T::Foo` should be used.

Interestingly, the assist "implement the missing item: `fn reproduce(`..." generates this (after formatting):

```rust
impl<T: Types> Behavior<T> for Impl {
    fn reproduce(&self, _: <T as Types>::Foo) {
        todo!()
    }
}
```
which is correct, although I would prefer using `T::Foo` directly, because it is valid in the trait definition, but I may be unaware of cases where the this short version would break.

---

**rust-analyzer version**: 7f28b4975 2021-12-18 nightly

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

### PR DESCRIPTION
**Pull request by pnevyk**
Fixes #11045 

The path transform now detects if a type parameter that is being substituted has an associated type. In that case it is necessary (or safe in general case) to fully qualify the substitution with a trait which the associated type belongs to.

This PR also fixes the previous wrong behavior of the substitution that could create an invalid tree `PATH_TYPE -> PATH_TYPE -> ...`.

### CODE REVIEW

File: crates/ide_db/src/path_transform.rs [hunk 1]
```diff
@@ -145,10 +151,60 @@ impl<'a> Ctx<'a> {
         match resolution {
             hir::PathResolution::TypeParam(tp) => {
                 if let Some(subst) = self.substs.get(&tp) {
-                    ted::replace(path.syntax(), subst.clone_subtree().clone_for_update().syntax())
+                    let parent = path.syntax().parent()?;
+                    if let Some(parent) = ast::Path::cast(parent.clone()) {
```
Comment (pnevyk) [inline crates/ide_db/src/path_transform.rs:155]: Is there a more reliable (or nicer) way how to check if the substituted parameter has an associated type?

File: crates/ide_db/src/path_transform.rs [hunk 2]
```diff
@@ -145,10 +151,60 @@ impl<'a> Ctx<'a> {
...
+                        let qualified =
+                            ast::make::path_from_segments(std::iter::once(segment), false);
+                        ted::replace(path.syntax(), qualified.clone_for_update().syntax());
+                    } else if let Some(path_ty) = ast::PathType::cast(parent) {
+                        ted::replace(
+                            path_ty.syntax(),
+                            subst.clone_subtree().clone_for_update().syntax(),
+                        );
+                    } else {
+                        ted::replace(
```
Comment (pnevyk) [inline crates/ide_db/src/path_transform.rs:190]: Even without this `else` branch, all tests pass. I am wondering in which scenarios is this code executed and if that's what is desired.

File: crates/ide_db/src/path_transform.rs [hunk 3]
```diff
@@ -145,10 +151,60 @@ impl<'a> Ctx<'a> {
...
             hir::PathResolution::Def(def) => {
+                if let hir::ModuleDef::Trait(_) = def {
+                    if matches!(path.segment()?.kind()?, ast::PathSegmentKind::Type { .. }) {
+                        // `speculative_resolve` resolves segments like `<T as
+                        // Trait>` into `Trait`, but just the trait name should
+                        // not be used as the replacement of the original
+                        // segment.
+                        return None;
+                    }
+                }
```
Comment (pnevyk) [inline crates/ide_db/src/path_transform.rs:206]: This feels hacky. But without this exception, the following ting happens:

```rust
pub trait Behavior<T: Types> {
    fn reproduce(&self, foo: <T as Types>::Foo);
}

pub struct Impl;

impl Behavior<u32> for Impl { $0 }

// -->

impl Behavior<u32> for Impl {
    fn reproduce(&self, foo: Types::Foo) {
        ${0:todo!()}
    }
}
```

File: crates/syntax/src/ast/make.rs [hunk 4]
```diff
@@ -196,9 +204,9 @@ pub fn path_from_segments(
 ) -> ast::Path {
     let segments = segments.into_iter().map(|it| it.syntax().clone()).join("::");
     ast_from_text(&if is_abs {
-        format!("use ::{};", segments)
+        format!("fn f(x: ::{}) {{}}", segments)
```
Comment (pnevyk) [inline crates/syntax/src/ast/make.rs:207]: I need to change this to preserve `<T as Trait>` type of paths. Is this fine? Shouldn't all path-related constructors this approach instead of `use {}`?

File: crates/ide_db/src/path_transform.rs (hunk 1 above)
Comment (Veykril) [reply crates/ide_db/src/path_transform.rs:155]: Don't think so, at least not with how things are currently structured here

File: crates/ide_db/src/path_transform.rs (hunk 2 above)
Comment (Veykril) [reply crates/ide_db/src/path_transform.rs:190]: The only case where I can see this happening is in Patterns using the path I believe, so `PathPat`, or the path in `TupleStructPat` etc, might be good to check that.

File: crates/syntax/src/ast/make.rs (hunk 4 above)
Comment (Veykril) [reply crates/syntax/src/ast/make.rs:207]: Ye this change is good, otherwise you could easily panic by feeding non use-tree path segments in there.

File: crates/ide_db/src/path_transform.rs (hunk 2 above)
Comment (pnevyk) [reply crates/ide_db/src/path_transform.rs:190]: I couldn't come up with a code snippet that would exercise this branch. It would need to:

* use a generic type parameter, because this part of code deals with `hir::PathResolution::TypeParam(tp)` substitution
* must not use associated type/constant, because this case is handled by `if let Some(parent) = ast::Path::cast(parent.clone())` above
* must be in a pattern or path expression

Therefore, as far as I can tell, the path here will always be a type (having `PathType` as parent) or will have an associated type/constant (having `Path` as parent). And so this `else` branch seems unreachable to me and can be removed.

Nevertheless, thanks to playing with path patterns and expressions, I discovered that handling associated *constants* was missing in my fix. It works now (d9b3242bcd5f4208fad707a30907633ccf081056).

Comment (Veykril) [reply crates/ide_db/src/path_transform.rs:190]: Can't hurt leaving the branch either so I think keeping it is fine, either way works.

PR lgtm then, thanks!
bors d+
