### PR TITLE
Install rustfmt if needed during formatting request

### LINKED ISSUE #4249: if rustfmt is not installed, formatting silently fails
If `rustfmt` isn't installed, then there is no error upon executing the `Format Document` command.  However, nothing happens.  Installing `rustfmt` via `rustup component add rustfmt` fixes the issue.

It would have been helpful to have an error dialog of some kind explaining what went wrong and how to fix it, or even something which offers to install `rustfmt` for the user!

Hopefully an easy fix!

Also, could possibly also be the root cause of #1955, maybe others?

### LINKED ISSUE #6052: Format on save fails quietly if rustfmt is not installed for the current toolchain
System: Ubuntu 18.04 with VS-Code
**Observed**: format on save does not work when rustfmt is not installed for the current toolchain
**Expected**: Either some kind of (additional) feedback that formatting failed (e.g. a pop up in vs-code) or an automatically triggered installation of rustfmt

Actually the log of the language server already prints a message that rustfmt is not installed for the current toolchain. But I would argue that an additional pop-up would be a better solution, since the first impulse (meaning my first impulse^^) is to check the settings (followed by confusion and resignation) instead of checking the log.

### PR DESCRIPTION
**Pull request by kinnison**
In order to fix #6052 and to fix #4249 this PR installs `rustfmt` using `rustup` if `rustfmt --help` fails.

In theory we ought to memoise the attempts (both the `--help` and the installation) so that we don't keep retrying something which will fail (e.g. if nightly is missing rustfmt), but this is a first-pass for opinions.

In order to make it possible to notify the user of what happened, I added a facility for `GlobalStateSnapshot` to send *messages* to the client indicating what happened.  There may be a cleaner way to do this as well but I wasn't sure exactly what might be best given this is my first time in this codebase.

It may be worth, longer term, working with `rustup` to provide a way to detect a missing component binary since `rustup` returns `1` if `rustfmt` is not installed, which is not ideal.

### CODE REVIEW

File: crates/rust-analyzer/src/handlers.rs [hunk 1]
```diff
@@ -844,6 +844,21 @@ pub(crate) fn handle_formatting(
...
         RustfmtConfig::Rustfmt { extra_args } => {
+            let mut cmd = process::Command::new(toolchain::rustfmt());
+            cmd.arg("--help");
+            let try_cmd_result = cmd.stdin(Stdio::null()).stdout(Stdio::null()).output()?;
+            if !try_cmd_result.status.success() {
+                let mut rustup = process::Command::new(toolchain::rustup());
+                rustup.args(&["component", "add", "rustfmt"]);
+                let out = rustup.output()?;
+                if !out.status.success() {
+                    snap.user_error("Cannot run rustfmt, cannot install it either".into());
```
Comment (bjorn3) [inline crates/rust-analyzer/src/handlers.rs:855]: Can you show the actual install error?

Comment (kinnison) [reply crates/rust-analyzer/src/handlers.rs:855]: Yes, I could capture that and include it in the message.  Do you know if multi-line messages render as plain text, or is it markdown or what?

Comment (bjorn3) [reply crates/rust-analyzer/src/handlers.rs:855]: I don't know. To test it you could use a toolchain for which you can't install rustfmt like a locally build rust install, an install using rustup-toolchain-install-master or a nightly version that has rustfmt missing.

Comment (kinnison) [reply crates/rust-analyzer/src/handlers.rs]: I've put in the stderr and stdout from calling rustup if it fails (and tested that it comes through using a system toolchain without rustfmt) but sadly vscode's notifications don't support newlines at this time, so it's a bit run-together - at least the info is there though.

**Comment by bjorn3** [comment]
I don't see any obvious problems, but I am not familiar enough with this part of rust-analyzer to know if there are any problems with it like breaking an abstraction that was deliberately added.

**Comment by matklad** [comment]
Hm, while I certainly agree with the problem, this solution gives me a pause: installing rustfmt silently feels a bit invasive.

I feel that maybe just displaing the error message here would do the trick? Not sure why is it swallowed... Aha, we fail to distinguish between `-1` return code from rustfmt and `-1` return code of rustup here:

https://github.com/rust-analyzer/rust-analyzer/blob/efc76e2c886a0c121b014a587123e2854c5f57df/crates/rust-analyzer/src/handlers.rs#L882-L893

Lets grep stderr for the "not installed" and avoid silencing the failure

**Comment by matklad** [comment]
(that is, the branch *above* is wrongly taken)

**Comment by kinnison** [comment]
Nominally we could use a message with an "install rustfmt" action and then respond to that action, but I wasn't sure what infrastructure (if any) there was for that kind of thing.

**Comment by kinnison** [comment]
Also I'm slightly averse to parsing message output from rustup because it's *not stable* as an API, then again there is nothing better at this point :/

**Comment by kinnison** [comment]
@matklad I've redone this as a detect-and-report approach only as you suggested.  This leaves a dead-code warning active since now `user_info()` isn't called, but my gut feeling there is to add `user_warning()` to that and possibly to allow(dead_code) on it.

How do you feel?

**Comment by matklad** [comment]
I think there's a simpler implementation still: *just* detect this extra error condition, without changing any of the surrounding code?

File: crates/rust-analyzer/src/handlers.rs [hunk 2]
```diff
@@ -871,6 +872,22 @@ pub(crate) fn handle_formatting(
     if !output.status.success() {
         match output.status.code() {
             Some(1) => {
+                // If `rustfmt` is a `rustup` proxy then it may exit 1 to indicate that the
```
Comment (matklad) [inline crates/rust-analyzer/src/handlers.rs:875]:
```suggestion
            Some(1) if !String::from_utf8(output.stderr).unwrap_or_default().contains("not installed") => {
                // If `rustfmt` is a `rustup` proxy then it may exit 1 to indicate that the
```

**Comment by kinnison** [comment]
> I think there's a simpler implementation still: _just_ detect this extra error condition, without changing any of the surrounding code?

In what sense, detect it and report it like now, or detect it and swallow it?  Silently swallowing the issue does mean we wouldn't need the change to permit the handler to send a message to the client, but it'd also result once again in silent lack of formatting.  Pretty much all other extensions I've used will warn you if their formatting tool is missing when you try and format a file.

File: crates/rust-analyzer/src/handlers.rs (hunk 2 above)
Comment (kinnison) [reply crates/rust-analyzer/src/handlers.rs:875]: Right now that'd prevent the silent swallowing of formatting errors

**Comment by matklad** [comment]
>In what sense, detect it and report it like now, or detect it and swallow it?

Only skip the existing `Some(1)` branch it the error message is from rustup. This will:

* correctly swallow `1` errors from rustfmt
* display non-1 rustfmt errors to the user
* use the same code path to display the "not installed" error to the user

**Comment by kinnison** [comment]
That approach certainly simplifies the code since it removes the need for the show_message infrastructure I introduced, let's give it a go.  Personally I find the "give the user important feedback via the lsp communication log" a bit messy, but since the ideal would be an interactive message suggesting they install which we then honour, it's no worse I guess.

**Comment by matklad** [comment]
Yeah, I think the best strategy here is to stick to a simple "try&report error" strategy on the server, and leave optional user interaction to the client

bors r+

**Comment by kinnison** [comment]
It's worth noting for changelog reasons that this PR as-merged does not install rustfmt, simply detects the not-installed error and lets it get reported instead.
