### PR TITLE
fix(rename): Use text range of a mod name after macro expansion

### LINKED ISSUE #11417: file/module rename mangles the starting text of the file declaring the module.
So I have a `main.rs` like this:
```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// ...

submodule!(defer);
```

In this case the `submodule!` macro just takes a module name once and then spits out the `mod` as well as the `pub use`:
```rust
#[macro_export]
macro_rules! submodule {
  ($sub_module_vis:vis $sub_module_name:ident) => {
    $sub_module_vis mod $sub_module_name;
    pub use $sub_module_name::*;
  }
}
```

Okay, so given all that, if I use the "rename" feature to change the name of the `defer` module to something like `defertest`, then the identifier in the macro use gets changed properly, and the file on disk is renamed properly, but *also* part of the top line of the `main.rs` file is mangled to have the new module name in it:
```rust
#![defertestttr(not(debug_assertions), windows_subsystem = "windows")]
```

### PR DESCRIPTION
**Pull request by tysg**
Fixes #11417.

### CODE REVIEW

File: crates/ide_db/src/rename.rs [hunk 1]
```diff
@@ -188,16 +187,16 @@ fn rename_mod(
...
+    if let Some(InFile { file_id, value: _ }) = module.declaration_source(sema.db) {
         let file_id = file_id.original_file(sema.db);
-        match decl_source.name() {
-            Some(name) => source_change.insert_source_edit(
+        if let Some(file_range) = Definition::Module(module).range_for_rename(sema) {
+            source_change.insert_source_edit(
                 file_id,
-                TextEdit::replace(name.syntax().text_range(), new_name.to_string()),
-            ),
-            _ => never!("Module source node is missing a name"),
```
Comment (Veykril) [inline crates/ide_db/src/rename.rs:198]: Any reason the `never!` is gone now?

Comment (tysg) [reply crates/ide_db/src/rename.rs:198]: Added back the `never`

**Comment by Veykril** [comment]
Thanks!
bors r+
