### PR TITLE
Fix mbe fail to pass expr with attr

### LINKED ISSUE #5896: Infinite loop when using expr attributes inside macro expansion
Reproduction using `lazy_static`:

```rust
lazy_static::lazy_static! {
    static ref FOO: () = #[allow(missing_docs)]
    ();
}
```

I’m trying to further minimize the testcase.

I get the following with `RA_LOG`:

```
[WARN hir_expand::db] fail on macro_parse: (reason: BindingError("expected subtree") macro_call: __lazy_static_internal!(@MAKETY, ,(), $N);) parents: __lazy_static_internal!(@TAIL, $N: : = =);
__lazy_static_internal!(@TAIL, $N:()= $);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(@TAIL, $N:()= $);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(@TAIL, $N:()= $);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(@MAKETY, ,(), $N);
__lazy_static_internal!(()staticref$N: $T= $e;);
lazy_static!((););
__lazy_static_internal!(()staticrefFOO:()= # ;(););
lazy_static::lazy_static! {
    static ref FOO: () = #[allow(missing_docs)]
    ();
}
```

the log message changes a bit, but its just looping there.

### PR DESCRIPTION
**Pull request by edwin0cheng**
bors r+

Fixes #5896

### CODE REVIEW

File: crates/hir_def/src/nameres/tests/macros.rs [hunk 1]
```diff
@@ -677,7 +677,7 @@ fn macro_expansion_overflow() {
         r#"
 macro_rules! a {
     ($e:expr; $($t:tt)*) => {
-        b!($($t)*);
```
Comment (edwin0cheng) [inline crates/hir_def/src/nameres/tests/macros.rs:680]: The old test actually is almost valid, it was not working because of the bug in #5896

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2820790f7dfd3a70ead75d60d067145a)
