### PR TITLE
 editors/code: fix crash due to missing ID= field

### LINKED ISSUE #11709: rust-analyzer crashes on startup
This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

https://github.com/rust-analyzer/rust-analyzer/commit/ce4b61003d8eb5383c4e759d919cdc72a137bc11 introduced a startup crash if the /etc/os-release file exists and doesn't contain a line that starts with `ID=`

For example, a file with the contents:
```
VERSION_ID=11
```

Will hit a crash (because isNixOs() incorrectly returns true and then it tries to run nix-build to patch the elf file).

idk typescript or I'd send a fix myself, but I confirmed that that is almost certainly the problem in this [repl](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJWSXFg9UarZjFFWycESp1+XG8DlHi8AG9FCUSqgyMWV2ud2jKTQKQptsJeQADRQAYlAxCQ1aQdcUAA0AJIAEW5AEYP6vdyVTwBuH9fxldJuGIDcK15Q8UVQQQAkEBZ5CVSMAB1OEjHUAmSDJuCVFUdR5AA+MR4LzMhYPAXYlT5N9uT5HUdUA38SicVB8S8CgwIgzhmAAfgCdBnngKQyAAYQYTNp34nC1mTZJqM4cd4CDAiAEJuV5UoPyYtcAF9RlQDRQG3ZjWPYnEGGgTMdJKXTFDs6VGlleVFSVIQxwnKcGKAA)

### PR DESCRIPTION
**Pull request by cab404**
Assuming ID=linux by default.
Also removed toLowerCase — it really shouldn't be needed.
Fixes #11709

### CODE REVIEW

**Comment by cab404** [comment]
@lnicola I did goofed :sweat_smile:

File: editors/code/src/main.ts [hunk 1]
```diff
@@ -269,8 +269,8 @@ function serverPath(config: Config): string | null {
 async function isNixOs(): Promise<boolean> {
     try {
         const contents = (await vscode.workspace.fs.readFile(vscode.Uri.file("/etc/os-release"))).toString();
-        const idString = contents.split('\n').find((a) => a.startsWith("ID="));
-        return idString?.toLowerCase()?.indexOf("nixos") !== -1;
+        const idString = contents.split('\n').find((a) => a.startsWith("ID=")) || "ID=linux";
+        return idString.indexOf("nixos") !== -1;
```
Comment (lnicola) [inline editors/code/src/main.ts:273]: Are you still sure you don't want this :smile:?

```suggestion
        return contents.indexOf("nixos") !== -1;
```

Comment (cab404) [reply editors/code/src/main.ts:273]: I still kinda am — almost sure two-three years from now someone will find a way to trigger it accidentally :D
