### PR TITLE
Fix extract_function with macro arg

### LINKED ISSUE #9266: Extract into function fails to add parameters for variables only used as formatting arguments
I tried to extract some code containing a `format!` call into a function and RA failed to add all the necessary parameters, probably due to not "understanding" `format!`. Small reproduction:

```rust
fn send_some_http_request() {
    let path = "foo/bar";
    let body = vec![1, 2, 3];
    let response = do_request(&format!("https://service.tld/{}", path)).json(&body);
}
```

extracting the expression that's assigned to `response` into a new function yields:

```rust
fn fun_name(body: Vec<i32>) -> () {
    do_request(&format!("https://service.tld/{}", path)).json(&body)
}
```

without a `path` parameter.

### PR DESCRIPTION
**Pull request by sasurau4**
## Overview

Fix #9266

### CODE REVIEW

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 1]
```diff
@@ -9,16 +9,7 @@ use ide_db::{
...
-    ast::{
-        self,
-        edit::{AstNodeEdit, IndentLevel},
-        AstNode,
-    },
-    ted,
-    SyntaxKind::{self, BLOCK_EXPR, BREAK_EXPR, COMMENT, PATH_EXPR, RETURN_EXPR},
-    SyntaxNode, SyntaxToken, TextRange, TextSize, TokenAtOffset, WalkEvent, T,
-};
+use syntax::{SyntaxKind::{self, BLOCK_EXPR, BREAK_EXPR, COMMENT, PATH_EXPR, RETURN_EXPR}, SyntaxNode, SyntaxToken, T, TextRange, TextSize, TokenAtOffset, WalkEvent, ast::{self, AstNode, edit::{AstNodeEdit, IndentLevel}}, ted};
```
Comment (lnicola) [inline crates/ide_assists/src/handlers/extract_function.rs:12]: Strange. My (stable) `rustfmt` reformats this, but I don't see the CI failing.

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 2]
```diff
@@ -71,7 +64,7 @@ pub(crate) fn extract_function(acc: &mut Assists, ctx: &AssistContext) -> Option
     let vars_used_in_body = vars_used_in_body(ctx, &body);
     let self_param = self_param_from_usages(ctx, &body, &vars_used_in_body);
 
-    let anchor = if self_param.is_some() { Anchor::Method } else { Anchor::Freestanding };
+                        let anchor = if self_param.is_some() { Anchor::Method } else { Anchor::Freestanding };
```
Comment (lnicola) [inline crates/ide_assists/src/handlers/extract_function.rs:67]: Some tabs happened here.

**Review by lnicola — APPROVED** [review]

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 3]
```diff
@@ -634,7 +627,22 @@ fn extraction_target(node: &SyntaxNode, selection_range: TextRange) -> Option<Fu
...
+        .map(|name_kind| match name_kind {
+            NameRefClass::Definition(def) => def,
+            NameRefClass::FieldShorthand { local_ref, field_ref: _ } => {
+                Definition::Local(local_ref)
+            }
+        })
+        .filter_map(|definition| match definition {
+            Definition::Local(local) => Some(local),
+            _ => None,
+        });
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/extract_function.rs:645]: Does `sema.expand` expand all underlying macros for an invocation or only one level? I think it only goes one level deep right? In which case this doesn't fully fix the problem.

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 4]
```diff
@@ -10,15 +10,8 @@ use ide_db::{
...
-        self,
-        edit::{AstNodeEdit, IndentLevel},
-        AstNode,
-    },
-    ted,
-    SyntaxKind::{self, BLOCK_EXPR, BREAK_EXPR, COMMENT, PATH_EXPR, RETURN_EXPR},
-    SyntaxNode, SyntaxToken, TextRange, TextSize, TokenAtOffset, WalkEvent, T,
-};
+    ast::{self, AstNode, edit::{AstNodeEdit, IndentLevel}},
+    SyntaxKind::{self, BLOCK_EXPR, BREAK_EXPR, COMMENT, PATH_EXPR, RETURN_EXPR}, SyntaxNode, SyntaxToken, T, TextRange, TextSize, TokenAtOffset, WalkEvent, ted};
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/extract_function.rs:14]: Aren't we checking formatting on CI? How is this not failing here? 😅

Comment (flodiebold) [reply crates/ide_assists/src/handlers/extract_function.rs:14]: `cargo fmt` seems to be fine with this formatting.

Comment (Veykril) [reply crates/ide_assists/src/handlers/extract_function.rs:14]: Oh is this one of those cases were rustfmt just accepts the files and ignores processing it? .... Not the first time I encountered this...

Comment (Veykril) [reply crates/ide_assists/src/handlers/extract_function.rs:14]: Actually, it might be a macro call in the file that's longer than the max char per line setting where it doesn't know how to format it, I think thats usually what causes it to just bail out

Comment (flodiebold) [reply crates/ide_assists/src/handlers/extract_function.rs:14]: Yeah, apparently `cargo +stable fmt` completely ignores all files in `ide_assists/src/handlers` and `ide_diagnostics/src/handlers`. Maybe it's something about the way these modules are declared? It seems to be fixed in current nightly though, so I guess we'll just have to wait until the fix becomes stable...
