### PR TITLE
Store proc-macro result in salsa db

### LINKED ISSUE #4315: RA is broken for #[actix_rt::main] with proc macros enabled
Cargo.toml:
```toml
[package]
name = "zzz"
version = "0.0.1"
edition = "2018"

[dependencies]
actix-rt = "1.1"
actix-web = "2.0"
```

main.rs:
```rust
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let test = test();
    dbg!(test);
    println!("Hello, world!");
    Ok(())
}

#[derive(Debug)]
struct Test {
    test: i32,
}

fn test() -> Test {
    Test { test: 2 }
}
```

Enable proc macro and `loadOutDirsFromCheck` settings.

Expected: inlay hints present, highlighting works, completions proposed
Actual: very few RA features such as code lens are present, the rest is not working **across the whole project**

Here's how it looks with disabled proc macros:
image

Notice the hint and the highlighting.
When I toggle the proc macro checkbox and reload the server, I get this:
Screenshot 2020-05-05 at 13 09 06

This happens in the code of a whole project, not only in the `main.rs`, making RA pretty useless.
Another interesting thing to notice that RA works fine with tokio:
image

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fixed #4315

### CODE REVIEW

File: crates/ra_hir_expand/src/db.rs [hunk 1]
```diff
@@ -75,6 +88,8 @@ pub trait AstDatabase: SourceDatabase {
 
     #[salsa::interned]
     fn intern_eager_expansion(&self, eager: EagerCallLoc) -> EagerMacroId;
+
+    fn expand_proc_macro(&self, call: ProcMacroCall) -> Result<tt::Subtree, mbe::ExpandError>;
```
Comment (matklad) [inline crates/ra_hir_expand/src/db.rs:92]: Hm, so this stores `TokenMap` as a **key**, and that's why we need all those `Hash` impls. I think we don't want to do this, because we'll efectively have a separate key for each change to the derive-annotated code, and then we'll need to gc it....

It should be sufficient to use `MacroCallId` or something similar as they key.

Comment (edwin0cheng) [reply crates/ra_hir_expand/src/db.rs]: Agreed and fixed. And please note that we currently don't gc `hir::db::macro_arg` such that the `TokenMap` is not gc too. But I agreed we should do it in the future.
