### PR TITLE
Don't mess with messy temp dir and just download into extension dir

### LINKED ISSUE #5019: vscode extension fails to bootstrap on windows
Extension fails to bootstrap on windows since release 2020-06-22

`await fs.promises.realpath(os.tmpdir());` fails.
image

https://github.com/rust-analyzer/rust-analyzer/blob/dceb81856eebc35856081587fac6339374c6e177/editors/code/src/net.ts#L141

### PR DESCRIPTION
**Pull request by Veetaha**
Temp dirs are messy. Dealing with them requires handling quite a bunch of
edge cases. As proposed by lnicola this seems better to just put the temp files
in the extension dir and not care much about suddenly leaving garbage.
Instead we get shorter and less platform-caveat-y code.
We will also assume users don't try to issue a download in different vscode windows simultaneously.

Fixes #5019

### CODE REVIEW

File: editors/code/src/net.ts [hunk 1]
```diff
@@ -68,32 +66,31 @@ interface DownloadOpts {
...
-                    const newPercentage = (readBytes / totalBytes) * 100;
-                    progress.report({
-                        message: newPercentage.toFixed(0) + "%",
-                        increment: newPercentage - lastPercentage
-                    });
-
-                    lastPercentage = newPercentage;
+    // Put artifact into a temporary file (in the same dir for simplicity)
+    // to prevent partially downloaded files when user kills vscode
+    const tempFile = `${opts.dest}.tmp`;
```
Comment (matklad) [inline editors/code/src/net.ts:71]: Should we perhaps add a random suffix as well? Just to make sure that there's no sudden interfernce somewhere. 

Otherwise, bors d+

Comment (Veetaha) [reply editors/code/src/net.ts:71]: @lnicola what do you think, having the fixed filename will prevent us from creating unlimited amount of garbage :)

Comment (lnicola) [reply editors/code/src/net.ts:71]: I suppose it's fine to use a suffix. Hard-drives are large these days :-).

**Comment by Veetaha** [comment]
Added 10 random hex characters to the temporary file name
bors r+
