### PR TITLE
Fix mbe composited token bug

### LINKED ISSUE #3436: MBE failed to parse single composited token
```rust
macro_rules! m {
    ( -> ) => { "->" };
    ( $first:tt $($tail:tt)+ ) => {
        m!($first)
    }
}

fn main() {
    let a = m!(-> a b c);  // a is unknown 
}
```

We should make `$var:tt` meta variable respect to composited token.

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fix #3436

### CODE REVIEW

File: crates/ra_hir_expand/src/db.rs [hunk 1]
```diff
@@ -181,6 +181,11 @@ pub(crate) fn parse_macro(
                         err,
                         node.value
                     );
+                    let mut parent = loc.kind.file_id().call_node(db);
+                    while let Some(node) = parent.clone() {
+                        log::warn!("parent: macro_call: {:#})", node.value);
+                        parent = node.file_id.call_node(db);
+                    }
```
Comment (matklad) [inline crates/ra_hir_expand/src/db.rs]: Hm, I am not sure what this while loop should be doing? Perhaps a comment would be helpful?

Comment (edwin0cheng) [reply crates/ra_hir_expand/src/db.rs]: Sure and fixed! It is used for printing out the parents of the failed expansion.
