### PR TITLE
Don't crash when recieving unkown file for cargo diagnostic.

### LINKED ISSUE #3014: Repeated crashes with Error: "unknown file"
I have updated to the newest version of rust-analyzer, and now I get the following error in 
project which worked without problems before:

```
Error: "unknown file: /home/dominik/Coding/probe-rs/target/debug/build/probe-rs-1e9a8f9372b29b3b/out/targets.rs"
[Info  - 10:40:59 PM] Connection to server got closed. Server will restart.
Error: "unknown file: /home/dominik/Coding/probe-rs/target/debug/build/probe-rs-1e9a8f9372b29b3b/out/targets.rs"
[Info  - 10:41:03 PM] Connection to server got closed. Server will restart.
Error: "unknown file: /home/dominik/Coding/probe-rs/target/debug/build/probe-rs-1e9a8f9372b29b3b/out/targets.rs"
[Info  - 10:41:06 PM] Connection to server got closed. Server will restart.
Error: "unknown file: /home/dominik/Coding/probe-rs/target/debug/build/probe-rs-1e9a8f9372b29b3b/out/targets.rs"
[Info  - 10:41:08 PM] Connection to server got closed. Server will restart.
Error: "unknown file: /home/dominik/Coding/probe-rs/target/debug/build/probe-rs-1e9a8f9372b29b3b/out/targets.rs"
[Error - 10:41:11 PM] Connection to server got closed. Server will not be restarted.
```

The file which it is complaining about is auto-generated by a build.rs, and the file does exist on the filesystem. 

The code for the project is here: https://github.com/probe-rs/probe-rs , I see this problem with the current master.

### PR DESCRIPTION
**Pull request by kiljacken**
Fixes #3014

### CODE REVIEW

File: crates/ra_lsp_server/src/main_loop.rs [hunk 1]
```diff
@@ -635,12 +635,16 @@ fn on_check_task(
...
-                .read()
-                .path2file(&path)
-                .map(|it| FileId(it.0))
-                .ok_or_else(|| format!("unknown file: {}", path.to_string_lossy()))?;
+            let file_id = match world_state.vfs.read().path2file(&path) {
+                Some(file) => FileId(file.0),
+                None => {
+                    log::error!(
+                        "File with cargo diagnostic not found in VFS: {}",
+                        path.to_string_lossy()
```
Comment (matklad) [inline crates/ra_lsp_server/src/main_loop.rs]:
```suggestion
                        path.display()
```

Comment (kiljacken) [reply crates/ra_lsp_server/src/main_loop.rs]: Done!
