### PR TITLE
Fix: Select correct insert position for disabled group import

### LINKED ISSUE #11585: Import type code action leads to invalid code if used inside an inline module
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 4e72700e3 2022-02-28 stable
I tested some older versions up to 0.2.792 and could reproduce it in any of them.

**rustc version**: (eg. output of `rustc -V`)
rustc 1.61.0-nightly (4b043faba 2022-02-24)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
```json
"rust-analyzer.assist.importGroup": false
```
This is the only setting I need to change in VS Code to trigger the bug.

Executing the `` Import `std::collections::HashMap` `` code action on `HashMap` results in invalid code. I can only reproduce this by setting `importGroup`. The default value does not trigger this bug.

Before:
```rust
mod foobar {
    fn create_map() -> HashMap<i32, i32> {
        todo!()
    }
}
```

After:
```rust
mod foobar use std::collections::HashMap;

{
    fn create_map() -> HashMap<i32, i32> {
        todo!()
    }
}
```

### PR DESCRIPTION
**Pull request by jonasbb**
The logic for importing with and without `group_imports` differed
significantly when no previous group existed. This lead to the problem
of using the wrong position when importing inside a module (#11585) or
when inner attributes are involved.
The existing code for grouped imports is better and takes these things
into account.

This PR changes the flow to use the pre-existing code for adding a new
import group even for the non-grouped import settings.
Some coverage markers are updated and the `group` is removed, since they
are now invoked in both cases (grouping and no grouping).

Tests are updated and two tests (empty module and inner attribute) are
added.

Fixes #11585

### CODE REVIEW

File: crates/ide_db/src/imports/insert_use/tests.rs [hunk 1]
```diff
@@ -86,7 +86,7 @@ use external_crate2::bar::A;",
 
 #[test]
 fn insert_not_group_empty() {
-    cov_mark::check!(insert_no_grouping_last2);
+    cov_mark::check!(insert_empty_file);
```
Comment (Veykril) [inline crates/ide_db/src/imports/insert_use/tests.rs:89]: Reusing the same label is a bad idea, these tests can run in parallel so this could succeed without being hit by this test

Comment (jonasbb) [reply crates/ide_db/src/imports/insert_use/tests.rs:89]: @Veykril Is there a preferred way how the tests should be structured, if two tests execute the same code path and thus should hit the same points? Should I merge the two test functions `insert_not_group_empty` and `insert_empty_file` into one bigger one?

Comment (Veykril) [reply crates/ide_db/src/imports/insert_use/tests.rs:89]: Ye since they now hit the same path we can put those into the same test function

**Comment by jonasbb** [comment]
I merged the "not_group" with the normal tests, for the three cases where they execute the same code path. That is the solution @Veykril suggested. I hope the tests are acceptable now. If not, please provide me with some more guidance.

I am confused how checks should work if multiple tests want to check coverage of the same piece of code. All places which use the same marker multiple times, the uses are in at least two different functions. Just like in my first commit. This affects `destructure_tuple_no_tuple`, `move_guard_ifelse_in_block`, `your_stack_belongs_to_me`, `not_all_selected`, `added_wildcard_pattern`, and `not_applicable_if_sorted_or_empty_or_single`.

The use of `not_all_selected` is even weirder, since the same marker is used in the same scope. If I understand the `check!` macro correctly, then the test will succeed if the first `check_assist_not_applicable` will not hit the coverage marker, but only the second `check_assist_not_applicable`.
https://github.com/rust-analyzer/rust-analyzer/blob/ccad89a2db105acf5619fe9dbb9d837d4cb41b5f/crates/ide_assists/src/handlers/move_from_mod_rs.rs#L79-L100

**Review by Veykril — APPROVED** [review]
There is https://docs.rs/cov-mark/latest/cov_mark/macro.check_count.html assuming we have the feature enabled. So assuming we use that you can replace your scoping shenanigans (smart idea there nevertheless) with `check_count!(thing, 2)`.

And ye there are some cases that don't properly use the macros as they slipped through reviews :) We should maybe make a lint that checks for these misuses 🤔

bors d+
