### PR TITLE
Fix document symbols order

### LINKED ISSUE #5655: Document Symbols listed in reverse order within each scope
Using:
* [Sublime Text 3.2.2, Build 3211](https://www.sublimetext.com/3)
* [LSP 0.11.4](https://github.com/sublimelsp/LSP) (with only rust-analyzer client enabled)
* [Rust Enhanced 2.22.0](https://github.com/rust-lang/rust-enhanced)
* [rust-analyzer-mac e96bfd8](https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-08-03/rust-analyzer-mac)

When you have a Rust Enhanced document open in Sublime Text, and you choose **Tools > Command Palette**, type _LSP: Document Symbols_ and hit Enter, the symbols are listed in reverse order within each scope like this:
LSP Document Symbols - rust-analyzer

### PR DESCRIPTION
**Pull request by magurotuna**
Resolves #5655 
And adds tests for `handle_document_symbol`, both with `hierarchical_symbols` enabled and with it disabled.

Previously document symbols were displayed in reverse order  in sublime text with its LSP plugin, but this patch fixes it like this:

image

### CODE REVIEW

**Comment by kjeremy** [comment]
@magurotuna did you file a bug with sublime's LSP?

File: crates/rust-analyzer/src/handlers.rs [hunk 1]
```diff
@@ -273,19 +273,24 @@ pub(crate) fn handle_document_symbol(
         parents.push((doc_symbol, symbol.parent));
     }
     let mut document_symbols = Vec::new();
+    // Constructs `document_symbols` from `parents`, in order from the end.
     while let Some((node, parent)) = parents.pop() {
         match parent {
             None => document_symbols.push(node),
```
Comment (matklad) [inline crates/rust-analyzer/src/handlers.rs:279]:
```suggestion
            None => {
                if let Some(children) = &mut node.children {
                    children.reverse()
                }
                document_symbols.push(node)
            },
```

I think should do the trick without recursion.

File: crates/rust-analyzer/tests/heavy_tests/main.rs [hunk 2]
```diff
@@ -682,3 +685,313 @@ pub fn foo(_input: TokenStream) -> TokenStream {
     let value = res.get("contents").unwrap().get("value").unwrap().to_string();
     assert_eq!(value, r#""```rust\nfoo::Bar\n```\n\n```rust\nfn bar()\n```""#)
 }
+
+#[test]
+fn test_document_symbol_with_hierarchy() {
```
Comment (matklad) [inline crates/rust-analyzer/tests/heavy_tests/main.rs:690]: Let's remove this test -- heavy tests are very slow, and don't really test much, as the end result is determined by the client anyway.

Comment (kjeremy) [reply crates/rust-analyzer/tests/heavy_tests/main.rs:690]: > the end result is determined by the client anyway.

The motivator for this PR is that Sublime displays the results in the order received from the server and doesn't do any sorting on the client side.

Comment (matklad) [reply crates/rust-analyzer/tests/heavy_tests/main.rs:690]: Yeah, that's exactly my point: the property we want to check is that "client sensibly interprets the results", and we can't do that without the client. 

To put it another way, we could have had the similar test before, with reverse order, and it would not have helped us to find out that the feature is broken in sublime.

**Comment by magurotuna** [comment]
@kjeremy 
> did you file a bug with sublime's LSP?

No, I had not made a issue to it. I just made one: https://github.com/sublimelsp/LSP/issues/1253

File: crates/rust-analyzer/src/handlers.rs (hunk 1 above)
Comment (magurotuna) [reply crates/rust-analyzer/src/handlers.rs:279]: Thanks for the suggestion.
I tried your code, but it cannot deal with nested symbols.

```rust
mod a {
    mod b {
        struct B1;
        struct B2;
    }
}
```

We want this snippet to be output like:

```json
[
  {
    "children": [
      {
        "children": [
          {
            "kind": 23,
            "name": "B1"
          },
          {
            "kind": 23,
            "name": "B2"
          }
        ],
        "kind": 2,
        "name": "b"
      }
    ],
    "kind": 2,
    "name": "a"
  }
]
```

But actually we get:

```json
[
  {
    "children": [
      {
        "children": [
          {
            "kind": 23,
            "name": "B2"
          },
          {
            "kind": 23,
            "name": "B1"
          }
        ],
        "kind": 2,
        "name": "b"
      }
    ],
    "kind": 2,
    "name": "a"
  }
]
```

Recursion way works as we expect.

File: crates/rust-analyzer/tests/heavy_tests/main.rs (hunk 2 above)
Comment (magurotuna) [reply crates/rust-analyzer/tests/heavy_tests/main.rs]: Okay.  I have removed the tests.  :)
