### PR TITLE
Fix #1178

### LINKED ISSUE #1178: Stack overflow
When I hover my mouse over [`TransactionOutput` field](https://github.com/0x7CFE/substrate-node-template/blob/7817268ae84560ae94064a3c4604411635982548/runtime/src/utxo.rs#L28) rust analyzer crashes. Actually, it happens on almost any other entry.

Please note, that my code is using [Substrate](https://github.com/paritytech/substrate/) which is really macro heavy. May be a good stress test for RA, btw.

```
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
[Info  - 4:03:53 PM] Connection to server got closed. Server will restart.
[Error - 4:03:53 PM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 4:03:53 PM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 4:03:53 PM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 4:03:53 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 4:03:53 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.listen.readable.on (/home/korvin/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
```

RA's repo HEAD is 
```
$ git show
commit e4a58ee1f4ad51d15c5a3de60d5846ffec51b771 (HEAD -> master, origin/staging, origin/master, origin/HEAD)
Merge: 4ad2e4ce 82751f8a
Author: bors[bot] <bors[bot]@users.noreply.github.com>
Date:   Sat Apr 20 16:31:37 2019 +0000

    Merge #1176
    
    1176: Add a simple test for str method completion r=flodiebold a=flodiebold
    
    Somehow I forgot that we should add a test for this in #1154 until after it was already merging. So I'll just add one now :)
    
    Co-authored-by: Florian Diebold <flodiebold@gmail.com>
```

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR improves / fixes mbe :

1. Fixed a offest bug in `SourceTreeWalker`
2. Handle `*+` matcher properly
3. Add missing separator in rhs macro expansion.
4. Fixed bug in single token with empty delimiter subtree case. It is because the current `mbe_expander` will create an delimiter subtree for each expansion. But in `tt` case, all puncts expansion will be incorrect because of it. 
5. Fixed lifetime bug
6. Add more information on parse_macro fail
7. Add tests for above.

### CODE REVIEW

File: crates/ra_mbe/src/mbe_expander.rs [hunk 1]
```diff
@@ -221,11 +221,13 @@ fn match_lhs(pattern: &crate::Subtree, input: &mut TtCursor) -> Result<Bindings,
                 }
                 _ => return Err(ExpandError::UnexpectedToken),
             },
-            crate::TokenTree::Repeat(crate::Repeat { subtree, kind: _, separator }) => {
+            crate::TokenTree::Repeat(crate::Repeat { subtree, kind, separator }) => {
```
Comment (matklad) [inline crates/ra_mbe/src/mbe_expander.rs]: This bit of code should probably just be rewritten to handle repetition properly.

I haven't managed to understand how rustc determines when it should stop expanding repeats, so that's why I written this random code that handles at least some cases.

**Comment by matklad** [comment]
I think this looks reasonable, but, once macro expansion is generally in a working state, we really should do a thorough pass through all mbe code and refactor it. I bet we can reduce the amount hacks a lot!

**Comment by edwin0cheng** [comment]
Yeah, I just feel uncomfortable about the current state of the code quality of `mbe`.  But I would want to know all the "hidden" `mbe` `feature` by passing a fooddog test first. I already setup a method to allow me to find the macro parsing bugs very easy. (I just found that `vis` matcher is optional :( )

**Comment by matklad** [comment]
>Yeah, I just feel uncomfortable about the current state of the code quality of mbe

I think it's OK, **for know**: for exploratory coding, it's really helpful to come with quick & dirty solution that handles most of the things and a basic test suite.

With tests, the second design/rewrite goes much more easily. 

In contrast, if you have neither tests, no solid understanding how the thing should work, trying to do the right design from the first try usually brings sadness
