### PR TITLE
internal: Simplify extract_function assist

### LINKED ISSUE #7839: Extract into function assist fails to add a trailing comma
Example input:

```rust
let x = match Ok(()) {
    Ok(()) => {
        let y = 0;
        y
    }
    Err(()) => 1,
};
```

Selecting the righthand side of the first `=>` from `{` up to and including `}` and running "extract into function"

* creates unneeded extra braces inside the generated function (doesn't break anything but is ugly):
  ```rust
  fn fun_name() -> i32 {
      {
          let y = 0;
          y
      }
  }
  ```
* updates the branch to `Ok(()) => fun_name()` without a trailing comma, breaking the code

### PR DESCRIPTION
**Pull request by Veykril**
also fixes #7839(blocked on #9728)

### CODE REVIEW

File: crates/syntax/src/ast/expr_ext.rs [hunk 1]
```diff
@@ -34,6 +36,122 @@ impl ast::Expr {
...
+                        preorder.skip_subtree();
+                    } else if let Some(expr) = ast::Expr::cast(node.clone()) {
+                        let is_different_context = match &expr {
+                            ast::Expr::EffectExpr(effect) => {
+                                matches!(
+                                    effect.effect(),
+                                    ast::Effect::Async(_)
+                                        | ast::Effect::Try(_)
+                                        | ast::Effect::Const(_)
+                                )
```
Comment (matklad) [inline crates/syntax/src/ast/expr_ext.rs:139]: (sorry, I am re-writing a bunch of code, so doing belated code reviews :0) )

This would be more readable if written as 

```rust
match effect.effect() {
ast::Effect::Async(_) | ast::Effect::Try(_) l| ast::Effect::Const(_) => true,
ast::Effect::Unsafe(_) | ast::Effect::Label => false,
}
```

`matches!` hides `_`, and often it's better to spell those out to see what *are* other cases.

Comment (matklad) [reply crates/syntax/src/ast/expr_ext.rs:139]: Also, I'd *probably* leave such walking functions to some utils in assists -- I think it might be a bit too hard to give *exact* semantics to such things, especially given that you might actually want to look at the semantic info for expression walking.
