### PR TITLE
Add quick fix to sort impl methods by trait definition

### LINKED ISSUE #6110: Add quick fix to sort methods
It would be nice to add a quick fix to sort methods in an `impl`. It should support both:

1. Sort methods alphabetically, and
2. Sort methods in the same order as trait declaration.

The second one would match the order of the methods to the order they are declared in in the trait, when doing `impl Trait for Type`.

### PR DESCRIPTION
**Pull request by fisherdarling**
Closes  #6110

### CODE REVIEW

File: crates/assists/src/handlers/reorder_impl.rs [hunk 1]
```diff
@@ -0,0 +1,263 @@
...
+        })
+        .filter(|f| f.name().is_some())
+        .collect()
+}
+
+// trait Foo<T> {}
+
+// struct Bar;
+
+// impl Foo<usize> for Bar {}
```
Comment (Veykril) [inline crates/assists/src/handlers/reorder_impl.rs:134]: You forgot to remove these

File: crates/assists/src/handlers/reorder_impl.rs [hunk 2]
```diff
@@ -0,0 +1,263 @@
...
+
+    #[test]
+    fn not_applicable_if_trait_empty() {
+        check_assist_not_applicable(
+            reorder_impl,
+            r#"
+        trait Bar {};
+        struct Foo;
+        <|>impl Bar for Foo {}
+        "#,
```
Comment (Veykril) [inline crates/assists/src/handlers/reorder_impl.rs:189]:
```suggestion
trait Bar {};
struct Foo;
<|>impl Bar for Foo {}
"#,
```
Ideally unindent the test fixtures, see https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#minimal-tests

Comment (fisherdarling) [reply crates/assists/src/handlers/reorder_impl.rs:189]: I indented these test fixtures since I was copying the style / flow of `reorder_fields.rs`. Should I also remove the test indentation in `reorder_fields.rs`?

Comment (Veykril) [reply crates/assists/src/handlers/reorder_impl.rs:189]: Ah ye some tests are still indented, I'd say leave them as is as to not make the diff of this PR too big and keep it in scope. Unindenting the tests in `reorder_fields.rs` can be done in a separate PR.

Comment (fisherdarling) [reply crates/assists/src/handlers/reorder_impl.rs]: Sound good

**Comment by fisherdarling** [comment]
I'll squash once y'all are happy with it

File: crates/assists/src/handlers/reorder_impl.rs [hunk 3]
```diff
@@ -0,0 +1,249 @@
...
+        .iter()
+        .cloned()
+        .sorted_by_key(|f| {
+            f.name().and_then(|n| ranks.get(&n.to_string()).copied()).unwrap_or(usize::max_value())
+        })
+        .collect();
+
+    // Don't edit already sorted methods:
+    if methods == sorted {
+        return None;
```
Comment (matklad) [inline crates/assists/src/handlers/reorder_impl.rs:59]: This can use a `mark::hit`:

https://github.com/rust-analyzer/rust-analyzer/blob/8cba4231092b0d9ca44ea1f545856239e2fb6eed/crates/test_utils/src/mark.rs#L21

File: crates/assists/src/handlers/reorder_impl.rs [hunk 4]
```diff
@@ -0,0 +1,249 @@
...
+    } else {
+        Some(
+            methods
+                .iter()
+                .flat_map(|f| f.name().map(|n| n.to_string()))
+                .sorted()
+                .enumerate()
+                .map(|(idx, name)| (name, idx))
+                .collect(),
+        )
```
Comment (matklad) [inline crates/assists/src/handlers/reorder_impl.rs:100]: Let's maybe remove the case for alphabetic sorting alrogether? 

I feel it's something which you almost never want, but it'll be almost always available.

File: crates/assists/src/handlers/reorder_impl.rs (hunk 3 above)
Comment (fisherdarling) [reply crates/assists/src/handlers/reorder_impl.rs:75]: I think I added is correctly?

**Review by matklad — COMMENTED** [review]
Nice!

bors r+

**Comment by matklad** [comment]
bors d+

**Comment by Veykril** [comment]
@fisherdarling in case you are confused why bors fails, a recent PR changed the test cursors from `<|>` to `$0` which is causing problems here. You will have to rebase your PR and change your tests to use the new cursor.

**Comment by fisherdarling** [comment]
bors merge
