### PR TITLE
Don't panic on crates depending on themselves

### LINKED ISSUE #3883: Crash on "Internal error, cycle detected:"
Rust analyzer crashes on `rust-analyzer analysis-stats .` with:

```
thread 'main' panicked at 'Internal error, cycle detected:

__SalsaDatabaseKey { kind: DefDatabaseStorage(crate_def_map_query(CrateId(221))) }
', <::std::macros::panic macros>:5:6
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
   9: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  10: ra_hir_def::nameres::collector::collect_defs
  11: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  12: salsa::runtime::Runtime<DB>::execute_query_implementation
  13: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  14: salsa::derived::slot::Slot<DB,Q,MP>::read
  15: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  16: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
  17: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  18: ra_hir_def::nameres::collector::collect_defs
  19: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  20: salsa::runtime::Runtime<DB>::execute_query_implementation
  21: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  22: salsa::derived::slot::Slot<DB,Q,MP>::read
  23: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  24: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
  25: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  26: ra_hir_def::nameres::collector::collect_defs
  27: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  28: salsa::runtime::Runtime<DB>::execute_query_implementation
  29: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  30: salsa::derived::slot::Slot<DB,Q,MP>::read
  31: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  32: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
  33: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  34: ra_hir_def::nameres::collector::collect_defs
  35: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  36: salsa::runtime::Runtime<DB>::execute_query_implementation
  37: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<DB,Q,MP>::read
  39: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  40: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
  41: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  42: ra_hir_def::nameres::collector::collect_defs
  43: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  44: salsa::runtime::Runtime<DB>::execute_query_implementation
  45: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  46: salsa::derived::slot::Slot<DB,Q,MP>::read
  47: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  48: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
  49: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  50: ra_hir::code_model::Crate::root_module
  51: rust_analyzer::cli::analysis_stats::analysis_stats
  52: rust_analyzer::main
  53: std::rt::lang_start::{{closure}}
  54: std::panicking::try::do_call
  55: __rust_maybe_catch_panic
  56: std::rt::lang_start_internal
  57: main
  58: __libc_start_main
  59: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Repository: https://github.com/paritytech/substrate

### PR DESCRIPTION
**Pull request by flodiebold**
Fixes #3883.

### CODE REVIEW

File: crates/ra_db/src/input.rs [hunk 1]
```diff
@@ -403,6 +403,31 @@ mod tests {
         assert!(graph.add_dep(crate3, CrateName::new("crate1").unwrap(), crate1).is_err());
     }
 
+    #[test]
+    fn it_should_panic_because_of_direct_cycle() {
```
Comment (bjorn3) [inline crates/ra_db/src/input.rs:407]:
```suggestion
    fn it_should_not_panic_because_of_direct_cycle() {
```

Comment (flodiebold) [reply crates/ra_db/src/input.rs:407]: Hm yeah I was just copying the other test name, not sure if that's the intended interpretation but I guess I'll just give both better names...

File: crates/ra_db/src/input.rs [hunk 2]
```diff
@@ -254,12 +254,12 @@ impl CrateGraph {
             return false;
         }
 
+        if target == from {
+            return true;
+        }
```
Comment (matklad) [inline crates/ra_db/src/input.rs:259]: Yeah, when writing dfses it always make sense to check conditions on entry, not before the recursive calls.... It bugs me a bit that a problem is known (as I've been bitten by this oh so many times), but that it slipped through code review... I guess, there's nothing actionable process-wise we can make better here :(

also cc @gfreezy for a "check condition on dfs *entry*" rule-of-thumb :) 

bors r+
