### PR TITLE
internal: calculate pattern adjustments

### LINKED ISSUE #9095: Panic in match checking
Version 71117e681 2021-06-01 nightly

Found this in my minimal reproducible examples repo:
```rust
enum Foo<T> { A(T) }
match &Foo::A(true) {
    _ => {}
    Foo::A(_) => {}
}
```

<details>
<summary>log</summary>

```
Panic context:
> 
version: 71117e681 2021-06-01 nightly
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/tmp/match-panic/src/extracted.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 132,
            character: 9,
        },
        end: Position {
            line: 132,
            character: 9,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Forgot to remove debug-print?', crates/hir_ty/src/diagnostics/expr.rs:365:25
stack backtrace:
   0: std::panicking::begin_panic
   1: hir_ty::diagnostics::expr::ExprValidator::validate_match::{{closure}}
   2: hir_ty::diagnostics::match_check::usefulness::MatchCheckCtx::bug
   3: hir_ty::diagnostics::match_check::usefulness::is_useful
   4: hir_ty::diagnostics::match_check::usefulness::compute_match_usefulness
   5: hir_ty::diagnostics::expr::ExprValidator::validate_body
   6: hir_ty::diagnostics::validate_body
   7: hir::Function::diagnostics
   8: hir::Module::diagnostics
   9: hir::Module::diagnostics
  10: ide::diagnostics::diagnostics
  11: ide::Analysis::assists_with_fixes::{{closure}}
  12: std::panicking::try
  13: rust_analyzer::handlers::handle_code_action
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

The example may appear while expanding nested or-patterns.

(Also seems like I shouldn't use debug-print when panicking)

### PR DESCRIPTION
**Pull request by iDawer**
This extends `InferenceResult` with `pub pat_adjustments: FxHashMap<PatId, Vec<Ty>>`.

Fixes #9095

### CODE REVIEW

File: crates/hir_ty/src/diagnostics/match_check/usefulness.rs [hunk 1]
```diff
@@ -331,8 +331,7 @@ impl<'a> MatchCheckCtx<'a> {
 
     #[track_caller]
     pub(super) fn bug(&self, info: &str) -> ! {
```
Comment (flodiebold) [inline crates/hir_ty/src/diagnostics/match_check/usefulness.rs:333]: (note: I haven't checked where this is called, but in general we want to be a bit more resilient about panicking on errors than rustc: Showing some inaccurate information in the IDE is often better than breaking completely. Hence the `always!` macro etc. that panic on debug assertions, but only log and continue in release builds.)

**Review by flodiebold — COMMENTED** [review]
bors r+

File: crates/hir_ty/src/diagnostics/match_check/usefulness.rs (hunk 1 above)
Comment (iDawer) [reply crates/hir_ty/src/diagnostics/match_check/usefulness.rs:333]: Interesting. This is worth some experimenting with fallible implementation then including it into future libraryfied match checking.
For now it just relies on correct lowering and filtering out erroneous input in `match_check::PatCtxt::lower_pattern`. But in case of bugs, yeah.. that's bad.

Comment (flodiebold) [reply crates/hir_ty/src/diagnostics/match_check/usefulness.rs:333]: Note, it's not worth making functions return results to avoid assertions. It's just, *if* there's a straightforward way to e.g. return no errors instead of panicking on an assertion, we should do that.
