### PR TITLE
Fix generic arguments being incorrectly offset in qualified trait casts

### LINKED ISSUE #5886: The return of `.await` is not typed as the `Output` of a BoxFuture, but as a `Future::Output<...>`
I have a fn that returns a `BoxFuture<'static, String>`, which RA is telling me expands out to:

Screen Shot 2020-08-25 at 6 01 35 PM

After calling await:  `let bar = foo.await;`, I'm seeing:

`Future::Output<Pin<Box<dyn Future<Output = String> + Send>>>`
Screen Shot 2020-08-25 at 6 01 47 PM

Instead of just `String`.

sample playground that uses the compiler for inspecting the type before/after the await:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=68afe0b35861d41fc9286cce1529276d

### PR DESCRIPTION
**Pull request by Veykril**
We reverse the segments and generic args of the lowered path after building it, this wasn't accounted for when inserting the self parameter in `Type as Trait` segments.

Fixes #5886

### CODE REVIEW

File: crates/hir_ty/src/tests/simple.rs [hunk 1]
```diff
@@ -2564,3 +2564,46 @@ fn f() {
     "#,
     )
 }
+
+#[test]
+fn qualified_as_trait_cast() {
```
Comment (Veykril) [inline crates/hir_ty/src/tests/simple.rs:2569]: Does this test belong here or in regressions? or maybe somewhere else?

Comment (matklad) [reply crates/hir_ty/src/tests/simple.rs:2569]: I guess it doesn’t matter if you add a cov-mark here.

Comment (Veykril) [reply crates/hir_ty/src/tests/simple.rs:2569]: Do cov-marks not work across crates? The test(check) is in `hir_ty` but the fix(hit) is in `hir_def`

Comment (matklad) [reply crates/hir_ty/src/tests/simple.rs]: Oups, indeed, cov-marks work only within a single crate. That's because they rely on `cfg(test)` to emit the code, and that is set only for the leaf crate.

Comment (Veykril) [reply crates/hir_ty/src/tests/simple.rs]: Ah that makes sense, figured it had to be something like that.

**Comment by lnicola** [comment]
Looks like this turned type mismatches into unknown types in `diesel` :smile::

image

**Comment by lnicola** [comment]
changelog fix fix generic argument lowering in qualified trait casts (helps with `.await`).
