### PR TITLE
Lower the precedence of the `as` operator.

### LINKED ISSUE #1851: Wrong precedence between `as` and `&[mut]`
A common example:
```rust
fn main() {
    let a = 1;
    let _ = &a as *const _;
}
```

Will be parsed as:
```
<... omitted ...>
          REF_EXPR@[39; 53)
            AMP@[39; 40) "&"
            CAST_EXPR@[40; 53)
              PATH_EXPR@[40; 41)
                PATH@[40; 41)
                  PATH_SEGMENT@[40; 41)
                    NAME_REF@[40; 41)
                      IDENT@[40; 41) "a"
              WHITESPACE@[41; 42) " "
              AS_KW@[42; 44) "as"
              WHITESPACE@[44; 45) " "
              POINTER_TYPE@[45; 53)
                STAR@[45; 46) "*"
                CONST_KW@[46; 51) "const"
                WHITESPACE@[51; 52) " "
                PLACEHOLDER_TYPE@[52; 53)
                  UNDERSCORE@[52; 53) "_"
<... omitted ...>
```

The `&[mut]` operator should have higher precedence than `as`.

Related issue: #279 (closed)

### PR DESCRIPTION
**Pull request by goffrie**
Previously, the `as` operator was being parsed like a postfix expression, and
therefore being given the highest possible precedence. That caused it to bind
more tightly than prefix operators, which it should not. Instead, parse it
somewhat like a normal binary expression with some special-casing.

Fixes #1851.

### CODE REVIEW

File: crates/ra_parser/src/grammar/expressions.rs [hunk 1]
```diff
@@ -296,6 +301,7 @@ fn lhs(p: &mut Parser, r: Restrictions) -> Option<(CompletedMarker, BlockLike)>
         // fn foo() {
         //     let _ = &1;
         //     let _ = &mut &f();
+        //     let _ = &1 as *const i32;
```
Comment (matklad) [inline crates/ra_parser/src/grammar/expressions.rs]: Let's move this test to the `if p.at(T![as]) {` line

File: crates/ra_parser/src/grammar/expressions.rs [hunk 2]
```diff
@@ -305,9 +311,13 @@ fn lhs(p: &mut Parser, r: Restrictions) -> Option<(CompletedMarker, BlockLike)>
...
         // test unary_expr
         // fn foo() {
-        //     **&1;
+        //     **&1 + 1;
         //     !!true;
         //     --1;
+        //     *&1 as u64;
+        //     *x(1);
+        //     &x[1];
+        //     -1..2;
```
Comment (matklad) [inline crates/ra_parser/src/grammar/expressions.rs]: Let's move these additional cases to an out-of-line test somewhere in test-data/parser/ok. The purpose of the inline tests is not to exhaustively check everything, but to explain what the code immediately after them does, and, for that purposes, simple cases are more useful.

**Comment by goffrie** [comment]
Done :)
