### PR TITLE
fix: Keep doc comments and outer attrs on "Move module to file" assist

### LINKED ISSUE #8804: "Move module to file" assist loses doc comments and attributes
```rust
/// doc comment
#[attribute]
mod module {
    pub struct Inside;
}
```

=>

```rust
mod module;
```

and

```rust
pub struct Inside;
```

### PR DESCRIPTION
**Pull request by Jesse-Bakker**
Fixes #8804

### CODE REVIEW

**Comment by Jesse-Bakker** [comment]
Might want to have a `first_nontrivia_child` on `SyntaxNode`, as that is a common query

File: crates/ide_assists/src/handlers/move_module_to_file.rs [hunk 1]
```diff
@@ -65,7 +65,25 @@ pub(crate) fn move_module_to_file(acc: &mut Assists, ctx: &AssistContext) -> Opt
...
+                    !matches!(
+                        child.kind(),
+                        syntax::SyntaxKind::COMMENT
+                            | syntax::SyntaxKind::ATTR
+                            | syntax::SyntaxKind::WHITESPACE
+                    )
+                })
+                .unwrap_or_else(|| syntax::SyntaxElement::Node(module_ast.syntax().clone()))
+                .text_range()
+                .start();
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/move_module_to_file.rs:81]: It would probably be simpler to just take the start of the `mod` token's syntax range

**Comment by Veykril** [comment]
> Might want to have a first_nontrivia_child() on SyntaxNode, as that is a common query

We already have https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/syntax/src/algo.rs#L58 so adding that would make sense if that pattern is used a few times. But note that we don't consider attributes to be trivia tokens, merely comments and whitespace so this wouldn't really apply I guess

**Comment by Jesse-Bakker** [comment]
Ran into it in https://github.com/rust-analyzer/rust-analyzer/pull/8742 as well. I think it might be useful in most edits that want to preserve comments and attrs. As attrs are not trivia we'd need a different name for it though :)

File: crates/ide_assists/src/handlers/move_module_to_file.rs (hunk 1 above)
Comment (Jesse-Bakker) [reply crates/ide_assists/src/handlers/move_module_to_file.rs:81]: Yeah, you are right. I thought it didn't work, because of visibility modifiers, but those are just a special case that can be removed when using the mod token, actually simplifying the code
