### PR TITLE
internal: Explicitly check for reference locals or fields in Name classification

### LINKED ISSUE #7524: Variables in destructing patterns are highlighted incorrectly
In code like
```rust
        let Meta { stamp, build_llvm_config, out_dir, root } = unimplemented!();
        t!(stamp.remove());
```
putting your cursor on `stamp,` does not highlight the use on the line below.

image

Strangely, putting the cursor on `stamp.` works correctly (it highlights `stamp` on both lines):

image

Reproduction steps: https://github.com/rust-lang/rust/blob/e13786548f6313dd931a63932a802f6bdf7facc9/src/bootstrap/native.rs#L185

### PR DESCRIPTION
**Pull request by Veykril**
Closes #7524
Inlines all the calls to reference related name classification as well as emits both goto definition targets for field shorthands.

### CODE REVIEW

**Comment by Veykril** [comment]
Guess I'll rebase on top of #9567 once its merged

File: crates/ide_db/src/defs.rs [hunk 1]
```diff
@@ -302,17 +312,25 @@ impl NameClass {
...
     Definition(Definition),
-    FieldShorthand { local_ref: Local, field_ref: Definition },
+    FieldShorthand { local_ref: Local, field_ref: Field },
 }
 
 impl NameRefClass {
-    /// `Definition`, which this name refers to.
-    pub fn referenced(self) -> Definition {
+    /// `Definition`, which this name refers to with a preference for the field reference in case of a field shorthand.
+    pub fn referenced_field(self) -> Definition {
```
Comment (matklad) [inline crates/ide_db/src/defs.rs:320]: Hm, not sure if that's the best API: `or_field` feels too specific. I wonder if the best solution here is maybe not to have any methods at all, and just write explicit matches at every call-site? That's more code, but it makes it clear when we ignore some cases...

File: crates/ide/src/goto_definition.rs [hunk 2]
```diff
@@ -878,10 +877,11 @@ fn main() {
             r#"
 enum Foo {
     Bar { x: i32 }
-}       //^
+}
 fn baz(foo: Foo) {
     match foo {
         Foo::Bar { x$0 } => x
```
Comment (matklad) [inline crates/ide/src/goto_definition.rs:883]: Hm, think we shouldn't change the test, the previous behavior feels more helpful.

Comment (Veykril) [reply crates/ide/src/goto_definition.rs:883]: But that would be inconsistent in my eyes.
If you were to use `goto_defintion` on a reference to a local you would go to the pattern definition here, invoking it on there again I would expect to see all references of the local instead of going to the field definiton.

Comment (matklad) [reply crates/ide/src/goto_definition.rs:883]: Yeah, it seems like this actually regresses behavior, let's try avoid breaking this

bors r-

Comment (matklad) [reply crates/ide/src/goto_definition.rs:883]: am, missed the commet.

File: crates/ide_db/src/defs.rs (hunk 1 above)
Comment (Veykril) [reply crates/ide_db/src/defs.rs:320]: Ye the main reason I didn't feel like doing that was due to the extern crate variant which you conveniently got rid of now. So inling all of these might be fine now.

File: crates/ide/src/goto_definition.rs (hunk 2 above)
Comment (Veykril) [reply crates/ide/src/goto_definition.rs:883]: What I was considering though would be to have `goto_declaration` instead to go to the field definition in that case while having `goto_definiton` stick to the local.

Comment (matklad) [reply crates/ide/src/goto_definition.rs:883]: Hm, good point about find references... 

I guess, there are two different IDE actions: gotodef and findref. If gotodef is invoked, then I think it is clear that it's more helpful to show field definition. If findref is invoked, then it's more helpful to look for usages of local items. 

However, the editor also implements a fallback behavior, where invoking gotodef on the def iteslf then invokes findref (i guess the editor just checkst that nav-target range intersects with current cursor position to detect this?). 

If we implement gotodef in the more helpful way, than we break editor's fallback. 

Seems like fundamentally  we just have two different things at the same cursor position, and it's impossible to cover all cases 100% correctly without showing some kind of multiresolve dialog to the user :thinking: 

Hm, it seems that LSP actually allows us to return both definitions in this case? 

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition

If that's the case, I think the ideal behavior here is to return two locatins for gotodef, and, for findref, look only for local variables.

Comment (Veykril) [reply crates/ide/src/goto_definition.rs:883]: Ye if we can return multiple definitions for `goto_def` that seems like the correct solution then.
