### PR TITLE
fix check of the toolchain's path

### LINKED ISSUE #9907: Toolchain checks in path never works
https://github.com/rust-analyzer/rust-analyzer/blob/b641a66078ce2f2363e9a3b050ba448b93fb7cb6/editors/code/src/toolchain.ts#L170-L193

`candidates.some(isFileAtPath)` always returns true, because isFileAtPath is an *async* function which return a promise which always evaluates to true.

```js
a = [1, 3]

function isEven(s) {
	return s % 2 === 0;
}

async function asyncIsEven(s) {
	return s % 2 === 0;
}

console.log("sync version should print false: ", a.some(isEven));
console.log("async version always print true: ", a.some(asyncIsEven));
```

### PR DESCRIPTION
**Pull request by gfreezy**
fixed #9907

### CODE REVIEW

File: editors/code/src/toolchain.ts [hunk 1]
```diff
@@ -180,13 +181,11 @@ function lookupInPath(exec: string): boolean {
     return candidates.some(isFileAtPath);
 }
 
-async function isFileAtPath(path: string): Promise<boolean> {
-    return isFileAtUri(vscode.Uri.file(path));
-}
-
-async function isFileAtUri(uri: vscode.Uri): Promise<boolean> {
+function isFileAtPath(suspectPath: string): boolean {
+    // It is not mentionned in docs, but `statSync()` throws an error when
```
Comment (bjorn3) [inline editors/code/src/toolchain.ts:185]: *mentioned

File: editors/code/src/toolchain.ts [hunk 2]
```diff
@@ -180,13 +181,11 @@ function lookupInPath(exec: string): boolean {
...
+    // the path doesn't exist
     try {
-        return ((await vscode.workspace.fs.stat(uri)).type & vscode.FileType.File) !== 0;
+        return fs.statSync(suspectPath).isFile();
```
Comment (bjorn3) [inline editors/code/src/toolchain.ts:188]: I think this shouldn't switch from `vscode.workspace.fs` to `fs`. I think something like `Promise.all(candidates.map(isFileAtPath)).some((isFile) => isFile)` instead of `candidates.some(isFileAtPath)` would work.

Comment (gfreezy) [reply editors/code/src/toolchain.ts:188]: `Promise.all` still need an async execution context thus `getPathForExecutable` must be made async and a lot of public functions depending on `getPathForExecutable` must be made async.

Comment (gfreezy) [reply editors/code/src/toolchain.ts]: I have changed all the calling functions to async.

**Comment by bjorn3** [comment]
Removing my review request as I don't consider myself good enough in javascript/typescript to be able to do a good review.

File: editors/code/src/toolchain.ts [hunk 3]
```diff
@@ -139,35 +140,36 @@ export async function getRustcId(dir: string): Promise<string> {
...
+        if (await lookupInPath(executableName)) return executableName;
 
         try {
             // hmm, `os.homedir()` seems to be infallible
             // it is not mentioned in docs and cannot be infered by the type signature...
             const standardPath = vscode.Uri.joinPath(vscode.Uri.file(os.homedir()), ".cargo", "bin", executableName);
 
-            if (isFileAtUri(standardPath)) return standardPath.fsPath;
+            const exist = await isFileAtUri(standardPath);
+            if (exist) return standardPath.fsPath;
```
Comment (wxb1ank) [inline editors/code/src/toolchain.ts:164]: Personally, I think this is a little verbose, and it's inconsistent with line 156.

File: editors/code/src/toolchain.ts [hunk 4]
```diff
@@ -3,7 +3,7 @@ import * as os from 'os';
 import * as path from 'path';
 import * as readline from 'readline';
 import * as vscode from 'vscode';
-import { execute, log, memoize } from './util';
+import { execute, log, memoize, memoizeAsync } from './util';
```
Comment (wxb1ank) [inline editors/code/src/toolchain.ts]: Remove the nonexistent `memoize` import. I'm not sure how this didn't get caught by tests. (?)

**Comment by wxb1ank** [comment]
LGTM (although I introduced the bug...).
I can test this. If `cargo`, `rustc`, and`rustup` aren't in my PATH, then RA shouldn't attempt to invoke them (from their unqualifed paths), correct?

**Comment by gfreezy** [comment]
RA should invoke them from `~/.rustup/bin`.

File: editors/code/src/toolchain.ts (hunk 3 above)
Comment (gfreezy) [reply editors/code/src/toolchain.ts]: done

**Comment by wxb1ank** [comment]
Apologies for the delay. I can confirm it works for me. When executing the "Debug" command (which invokes `rustc`) with `.cargo/bin` removed from my PATH and tool-specific environment variables (e.g., `RUSTC`) unset, `rust-analyzer` invokes the full path at `.cargo/bin/rustc`.

**Comment by lnicola** [comment]
This is pretty and we should probably collapse some of the code together (e.g. `getSysroot` and `getRustcId`) so that `memoizeAsync` wouldn't be needed, but we can leave that for another time.

bors r+
