### PR TITLE
Move roots_to_scan to LoopState

### LINKED ISSUE #3760: Arithmetic underflow on project load
thread 'main' panicked at 'attempt to subtract with overflow', crates/rust-analyzer/src/main_loop.rs:720:20

Seen with a debug build on the `rust-analyzer` repository.

### PR DESCRIPTION
**Pull request by edwin0cheng**
closes #3760

cc @lnicola

### CODE REVIEW

File: crates/rust-analyzer/src/main_loop.rs [hunk 1]
```diff
@@ -427,8 +434,11 @@ fn loop_turn(
         });
     }
 
+    let show_progress = !loop_state.workspace_loaded
```
Comment (Veetaha) [inline crates/rust-analyzer/src/main_loop.rs]: Maybe move this closer to usage?

Comment (edwin0cheng) [reply crates/rust-analyzer/src/main_loop.rs]: The problem to move closer here is `loop_state.workspace_loaded` will be changed to the following code.

File: crates/rust-analyzer/src/main_loop.rs [hunk 2]
```diff
@@ -706,18 +717,10 @@ fn on_diagnostic_task(task: DiagnosticTask, msg_sender: &Sender<Message>, state:
...
-    if !world_state.feature_flags.get("notifications.workspace-loaded") {
-        return;
-    }
-
-    let total: usize = world_state.workspaces.iter().map(|it| it.n_packages()).sum();
+fn send_startup_progress(sender: &Sender<Message>, loop_state: &mut LoopState) {
+    let total: usize = loop_state.roots_total;
     let prev_progress = loop_state.roots_scanned_progress;
-    let progress = total - world_state.roots_to_scan;
+    let progress = total - loop_state.roots_to_scan;
```
Comment (lnicola) [inline crates/rust-analyzer/src/main_loop.rs]: This seems a bit convoluted, maybe we could change `roots_to_scan` to `roots_scanned`?

File: crates/rust-analyzer/src/main_loop.rs [hunk 3]
```diff
@@ -706,18 +717,10 @@ fn on_diagnostic_task(task: DiagnosticTask, msg_sender: &Sender<Message>, state:
...
     loop_state.roots_scanned_progress = Some(progress);
 
     match (prev_progress, loop_state.workspace_loaded) {
```
Comment (lnicola) [inline crates/rust-analyzer/src/main_loop.rs]: It's not clear to me, but isn't `roots_to_scan` monotonically decreasing here? It feels like we shouldn't need the `progress != prev` check, nor the `None` value for the first call.

File: crates/rust-analyzer/src/main_loop.rs (hunk 2 above)
Comment (edwin0cheng) [reply crates/rust-analyzer/src/main_loop.rs]: Good idea.

File: crates/rust-analyzer/src/main_loop.rs (hunk 3 above)
Comment (edwin0cheng) [reply crates/rust-analyzer/src/main_loop.rs]: It is monotonically decreasing / (or increasing if we changed to `roots_scanned`). But we still want to  keep check whether the progress is reported to client side and the first time of the progress reporting. So I think the `Option<usize>` and the `progress != prev` check is unavoidable ??

Comment (lnicola) [reply crates/rust-analyzer/src/main_loop.rs]: I was thinking we could use `0` instead of `None`. If it's monotonic, the `progress != prev` test is always true?

Comment (edwin0cheng) [reply crates/rust-analyzer/src/main_loop.rs]: It is monotonic, but not strictly monotone such that that comparison will be equal occasionally. And note that the `prev`  is set like this :

```rust
let prev_progress = loop_state.roots_scanned_progress;
let progress = total - loop_state.roots_to_scan;
loop_state.roots_scanned_progress = Some(progress);
```

We changed roots_scanned_progress after we get the value so it will be different sometimes. (i.e. the ` loop_state.roots_to_scan` was changed in the loop)

Comment (edwin0cheng) [reply crates/rust-analyzer/src/main_loop.rs]: And one more thing, we can't guarantee `progress` will be zero when the first call of this function. So we have to use another variable to store that state. Anyway, I will rename it to `roots_progress_reported`.

**Comment by matklad** [comment]
I think this actually might be https://github.com/rust-analyzer/rust-analyzer/pull/3754

let's try again!

bors r+

**Comment by edwin0cheng** [comment]
bors retry
