### PR TITLE
Fix wrong substitution code

### LINKED ISSUE #4053: New weekly build crashs reproducily
I've doing some work on [diesel](https://github.com/diesel-rs/diesel). Pointing with the cursor to [this line](https://github.com/diesel-rs/diesel/blob/be0854094c79ae99ba3c893242a4be358ac0b0c5/diesel/src/query_builder/select_statement/dsl_impls.rs#L359) reproducibly crashes rust-analyzer with the attached backtrace.

Version: rust-analyzer 90f8378
OS: Ubuntu 20.04
IDE: Emacs

```
Backtrace: 
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 7', /home/runner/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/28cef6f/chalk-ir/src/fold/subst.rs:56:19
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: <unknown>
  67: <unknown>
  68: <unknown>
  69: <unknown>
  70: <unknown>
  71: <unknown>
  72: <unknown>
  73: <unknown>
  74: <unknown>
  75: <unknown>
  76: <unknown>
  77: <unknown>
  78: <unknown>
  79: <unknown>
  80: <unknown>
  81: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by flodiebold**
We need to shift in when we're substituting inside a binder.

This should fix #4053 (it doesn't fix the occasional overflow that also occurs on the Diesel codebase though).

### CODE REVIEW

File: crates/ra_hir_ty/src/lib.rs [hunk 1]
```diff
@@ -863,7 +863,7 @@ pub trait TypeWalk {
             &mut |ty, binders| {
                 if let &mut Ty::Bound(bound) = ty {
                     if bound.debruijn >= binders {
-                        *ty = substs.0[bound.index].clone();
+                        *ty = substs.0[bound.index].clone().shift_bound_vars(binders);
```
Comment (matklad) [inline crates/ra_hir_ty/src/lib.rs:866]: Is there perhaps some way we could similar wrong code crash on all examples, and only just on the bad ones?

File: crates/ra_hir_ty/src/tests/regression.rs [hunk 2]
```diff
@@ -533,3 +533,45 @@ fn foo(b: Bar) {
     "###
     );
 }
+
+#[test]
+fn issue_4053_diesel_where_clauses() {
+    std::env::set_var("CHALK_DEBUG", "1");
```
Comment (matklad) [inline crates/ra_hir_ty/src/tests/regression.rs:539]: Should this be removed? It won't be scoped to a single test.

Comment (flodiebold) [reply crates/ra_hir_ty/src/tests/regression.rs:539]: oh, yeah

File: crates/ra_hir_ty/src/lib.rs (hunk 1 above)
Comment (matklad) [reply crates/ra_hir_ty/src/lib.rs:866]: Like, if this happens to work most of the time, b/c binders is `0`, can we remember a number which tells the nesting/how many times we should shift, and than assert everywhere that nesting levels match?

Comment (flodiebold) [reply crates/ra_hir_ty/src/lib.rs:866]: I don't see how -- if I remember to assert, I can just do it correctly in that place. We could validate types to check that the binders are correct, but that will also only crash if we try to bind to indexes that don't exist.
