### PR TITLE
fix: derive attr path handling in `replace_derive_with_manual_impl`

### LINKED ISSUE #10666: replace_derive_with_manual_impl / Convert to manual `...` does not handle paths correctly
```rust
// cursor on clone, trigger `replace_derive_with_manual_impl`
#[derive(std::fmt::Debug, Clone)]
pub struct Foo;
```
becomes
```rust
// `::` became `,`
#[derive(std, fmt, Debug)]
pub struct Foo;

impl Clone for Foo {
    fn clone(&self) -> Self {
        Self {  }
    }
}

```

`rust-analyzer version: 3ad83cc08 dev`

### PR DESCRIPTION
**Pull request by rainy-me**
partially fixes #10666

renaming issues mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/10666#issuecomment-955671021 doesn't seem to be fixable at this moment since it's not searchable?(not recorded?) by name.

<del>I'm not sure if it's appropriate to move `parse_comma_sep_paths` function to a method in `ast/node_ext`, maybe `ide_db::helpers` also make sense.</del> put into `ide_db::` instead.

### CODE REVIEW

File: crates/syntax/src/ast/node_ext.rs [hunk 1]
```diff
@@ -725,6 +725,23 @@ impl ast::TokenTree {
...
+            .take_while(|it| it.as_token() != Some(&r_paren));
+        let input_expressions = tokens.into_iter().group_by(|tok| tok.kind() == T![,]);
+        Some(
+            input_expressions
+                .into_iter()
+                .filter_map(|(is_sep, group)| (!is_sep).then(|| group))
+                .filter_map(|mut tokens| ast::Path::parse(&tokens.join("")).ok())
+                .collect::<Vec<ast::Path>>(),
+        )
+    }
```
Comment (Veykril) [inline crates/syntax/src/ast/node_ext.rs:744]: You already correctly pointed out, this should go into `ide_db` somewhere instead. We try to not do any transformations in `node_ext`.

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs [hunk 2]
```diff
@@ -52,18 +53,34 @@ pub(crate) fn replace_derive_with_manual_impl(
         return None;
     }
 
-    let trait_token = args.syntax().token_at_offset(ctx.offset()).find(|t| t.kind() == IDENT)?;
-    let trait_name = trait_token.text();
-
+    let current_derives = args.clone().as_comma_sep_paths()?;
+    // found the related path of current focused token
+    // I don't know how to keep the original range for tokens while transforming and parsing as new ast
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs:58]: You could iterate through the token tree of the attribute and count the number of commas until you find the node of the cursor in it. That number of commas is then the index into `current_derives`. This should always work unless the user screwed up the derive syntax at which point its fine for this to not work properly.

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs [hunk 3]
```diff
@@ -52,18 +53,34 @@ pub(crate) fn replace_derive_with_manual_impl(
...
     let adt = attr.syntax().parent().and_then(ast::Adt::cast)?;
 
     let current_module = ctx.sema.scope(adt.syntax()).module()?;
     let current_crate = current_module.krate();
-
     let found_traits = items_locator::items_with_name(
         &ctx.sema,
         current_crate,
-        NameToImport::Exact(trait_name.to_string()),
+        NameToImport::Exact(trait_path.segments().last()?.to_string()),
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs:83]: An aside(not relevant for current PR): it would be interesting to have this assist search through the derive attribute's expansion for trait impls to figure out which trait import to show.

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs [hunk 4]
```diff
@@ -94,15 +119,16 @@ fn add_assist(
     acc: &mut Assists,
     ctx: &AssistContext,
     attr: &ast::Attr,
-    input: &ast::TokenTree,
-    trait_path: &ast::Path,
+    old_derives: &Vec<ast::Path>,
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs:122]:
```suggestion
    old_derives: &[ast::Path],
```

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs (hunk 2 above)
Comment (rainy-me) [reply crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs]: I think only counting commas count possibly result in the assist applicable in extra white space? I decided to reuse part of the logic in https://github.com/rust-analyzer/rust-analyzer/pull/10847/files#diff-0e0e5f4792d3e8922d28bb09e751cecc255acc261d4a62e126fd9bcdf00980f8R56-R69

Comment (rainy-me) [reply crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs]: sorry I think I missed up the rebasing.. fixing it now..

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs [hunk 5]
```diff
@@ -47,23 +49,23 @@ pub(crate) fn replace_derive_with_manual_impl(
         return None;
     }
 
-    if !args.syntax().text_range().contains(ctx.offset()) {
+    if !(args.l_paren_token()?.text_range().end() <= ctx.offset()
+        && ctx.offset() <= args.r_paren_token()?.text_range().start())
+    {
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs:54]: This shouldn't need to change

File: crates/ide_db/src/helpers.rs [hunk 6]
```diff
@@ -51,7 +50,11 @@ pub fn get_path_in_derive_attr(
     if PathResolution::Macro(derive) != resolved_attr {
         return None;
     }
+    get_path_at_cursor(cursor)
+}
 
+pub fn get_path_at_cursor(cursor: &Ident) -> Option<ast::Path> {
```
Comment (Veykril) [inline crates/ide_db/src/helpers.rs:56]:
```suggestion
/// Parses the path the identifier is part of inside a token tree.
pub fn get_path_at_cursor_in_tt(cursor: &Ident) -> Option<ast::Path> {
```
As this is specifically for TokenTrees(macro input) we should clarify that with a more fitting name + comment.
Same for `parse_comma_sep_paths` below.

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs (hunk 2 above)
Comment (Veykril) [reply crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs]: Oh nice find, I forgot about us doing something similar there already 👍

**Comment by Veykril** [comment]
bors d+

File: crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs (hunk 5 above)
Comment (rainy-me) [reply crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs]: I changed this last time because it suddenly failed to work after some refactoring. After debugging this a while it turns out it was originally guarded by the code following

```rust
args.syntax().token_at_offset(ctx.offset()).find(|t| t.kind() == IDENT)?
```

which gives the `(` token at `ctx.offset()` inside the `args` is an ident, comparatively, `ctx.find_token_at_offset()` will give the `derive` token which will fail the `test_ignore_if_cursor_on_param` test.
