### PR TITLE
Fixed syntax highlighting not refreshing on windows.

### LINKED ISSUE #1690: Syntax Highlighting doesn't update properly
Syntax Highlighting in the current tab fails to update properly with changes.

A workaround is to switch to another tab and then back, which I guess makes it recompute highlighting, but thats not very practical when writing code.

Examples:

Normal: 
image

After typing a comment:
image

Even weirder, *some* parts of the line actually have updated, the `=`, `:`, `;`, `(`, and `)` characters are green. But `/` is blue?

----

Using VSCode 1.37.1 and rust-analyzer master, commit c7d37e424f1e04f87982233f97e1e9385191b7f1

Not using `rust-analyzer.rainbowHighlightingOn`

### PR DESCRIPTION
**Pull request by omerbenamram**
I was encoutering the same probelm described in #1690.

It seems that events initiated by the frontend with `rust-analyzer/decorationsRequest` would go through.
So whenever a user switches tabs, highlighting will update.

However, when decorations are initiated by a notification with `rust-analyzer/publishDecorations`, it would fail on this check here https://github.com/rust-analyzer/rust-analyzer/blob/6cbd8a4a4bbca8a7656df9f3ef849acebbf9ef9b/editors/code/src/notifications/publish_decorations.ts#L15 (`targetEditor` will always be `undefined`).

This is because it's trying to match the uri `rust-analyzer` sends (which uses an uppercase drive letter) to the uri provided at `editor.document.uri.toString()`, which is both escaped (uses `%3a` for `:`), and uses a lowercase letter drive.

Aparrently this was an issue for some other extensions aswell - https://github.com/Microsoft/vscode/issues/68325.

But this is the defined behavior - https://github.com/microsoft/vscode/blob/c110d84460b3e45842a8fe753562341003595e1d/src/vs/vscode.d.ts#L1304

This fix is only relevant for windows.
I've opted for a server-side fix, since rust will always return uppercase letters for drives, there seems to be no other easy solution than manipulating the Url string before sending it to the frontend.

Closes #1690.

### CODE REVIEW

File: crates/ra_lsp_server/src/world.rs [hunk 1]
```diff
@@ -279,3 +282,35 @@ impl WorldSnapshot {
         self.analysis.feature_flags()
     }
 }
+
+#[cfg(target_os = "windows")]
+fn lowercase_drive_letter(url: &Url) -> Url {
+    use std::str::FromStr;
+
+    let s = url.to_string();
+    let drive_partition: Vec<&str> = s.rsplitn(2, ':').collect::<Vec<&str>>();
```
Comment (matklad) [inline crates/ra_lsp_server/src/world.rs]: I am slightly worried that we apply a blanket transform to all URIs. Should we check that the scheme is `file`? 

I think I would also prefer it this funciton weren't `cfg(windows)` -- part of the appeal of URIs is that they allow represent various weired paths, like a paths from something like wsl, or a path on the remote machine, so I think it might be the case that we see a windows path here even if the host machine is linux.

Comment (omerbenamram) [reply crates/ra_lsp_server/src/world.rs]: I've pushed a change that will now do a quick scan to check if there are any `Drive` components in the path, and would otherwise fallback to the default `Url` constructor.

When using WSL, you can only access windows paths from `/mnt/c` (when going from wsl->windows), I've checked the wierder case, which is code stored on UNC shares.

which is something like `\\localhost\c$\my_dir`.

rust will not treat this as a drive (even though it is technically local), so it will simply pass through.

I'm not entierly sure what vscode will do when accessing code stored on shares like this, but I would guess it would simply pass it through similarly.

File: crates/ra_lsp_server/src/world.rs [hunk 2]
```diff
@@ -279,3 +281,65 @@ impl WorldSnapshot {
...
+        let url = Url::from_str(&joined).expect("This came from a valid `Url`");
+
+        Ok(url)
+    } else {
+        Ok(Url::from_file_path(&path)
+            .map_err(|_| format!("can't convert path to url: {}", path.as_ref().display()))?)
+    }
+}
+
+// `Url` is not able to parse windows paths on unix machines.
```
Comment (matklad) [inline crates/ra_lsp_server/src/world.rs]: Ouch, this is not at all pretty. I don't really understand why an `URL` is a platform-specific thing, but maybe there's a good reason for this...

**Comment by matklad** [comment]
bors r+

Thanks!

**Comment by ice1000** [comment]
\o/ \o/ \o/ \o/ \o/ \o/ \o/

┗:smiley:┛ ┏:smiley:┓ ┗:smiley:┛ ┏:smiley:┓ ┗:smiley:┛ ┏:smiley:┓ ┗:smiley:┛

Confirmed to fix the issue!!
