### PR TITLE
Fix rename of enum variant visible from module

### LINKED ISSUE #4237: Enum variant rename should rename all usages
```rust
mod foo {
    pub enum Bar {
        Baz<|>,
    }
}

fn func(f: foo::Bar) {
    match f {
        foo::Bar::Baz => {}
    }
}

```

renaming to `Foo` currently gives

```rust
mod foo {
    pub enum Bar {
        Foo,
    }
}

fn func(f: foo::Bar) {
    match f {
        foo::Bar::Baz => {}
    }
}
```
while the usage of `foo::Bar::Baz` remains unchanged.

### PR DESCRIPTION
**Pull request by montekki**
Probably fixes #4237 

It looks like the ref is found correctly in this case but it's visibility is not correctly determined. I took a stab at fixing that by adding an implementation of `HasVisibility` for `EnumVariant` so it works more or less the same way it does for struct fields.

In other words, the `search_range` here does not contain the ref since it's not considered visible:

https://github.com/rust-analyzer/rust-analyzer/blob/efd8e34c396f1524623a495e47111f1047cf2879/crates/ra_ide_db/src/search.rs#L209-L214

Before that I tried to populate `ItemScope` with visible enum variants but that ended up with breaking tests all over the place and also it looked illogical in the end: `ItemScope` is not populated with, say, public struct fields and the same should be true for `enum` variants.

I've added two more or less identical tests: one for the case with a struct field rename and one for enum variant rename; the test for struct should probably be removed and the names should be changed.

### CODE REVIEW

**Comment by flodiebold** [comment]
Hmm, the fact that items don't implement `HasVisibility` is quite intentional, since the visibility is really a property of the specific name / reexport. OTOH for the purposes of determining the search range, looking at the declared visibility of the enum might actually be enough, since you're not allowed to reexport an item to a wider visibility than what it's declared with :thinking:

File: crates/ra_ide_db/src/defs.rs [hunk 1]
```diff
@@ -47,7 +47,10 @@ impl Definition {
         match self {
             Definition::Macro(_) => None,
             Definition::Field(sf) => Some(sf.visibility(db)),
-            Definition::ModuleDef(def) => module?.visibility_of(db, def),
+            Definition::ModuleDef(def) => match def {
+                ModuleDef::EnumVariant(id) => Some(id.visibility(db)),
```
Comment (flodiebold) [inline crates/ra_ide_db/src/defs.rs:51]: On the other other hand, you would already get that by just looking up the visibility of the containing enum here, no need to implement `HasVisibility` or change `EnumData`.

Comment (montekki) [reply crates/ra_ide_db/src/defs.rs]: right, thanks, this makes more sense
