### PR TITLE
Look for `cargo`, `rustc`, and `rustup` in standard installation path

### LINKED ISSUE #3118: "cargo metadata failed: No such file or directory (os error 2)"
I'm trying to work on a project that the RLS extension has no problem handling but I'm getting an odd error from rust-analyzer that is pretty unhelpful:
```
rust-analyzer failed to load workspace: cargo metadata failed: No such file or directory (os error 2)
```
What file or directory could not be found? Why couldn't it be found even though RLS works without a hitch?

I'm running the VSCode extension remotely (Docker) with VSCode Insiders and rust-analyzer at commit 759100fb0dcb41518f2a593dae5de5bbedd07776.

### PR DESCRIPTION
**Pull request by cdisselkoen**
Discussed in #3118.  This is approximately a 90% fix for the issue described there.

This PR creates a new crate `ra_env` with a function `get_path_for_executable()`; see docs there.  `get_path_for_executable()` improves and generalizes the function `cargo_binary()` which was previously duplicated in the `ra_project_model` and `ra_flycheck` crates.  (Both of those crates now depend on the new `ra_env` crate.)  The new function checks (e.g.) `$CARGO` and `$PATH`, but also falls back on `~/.cargo/bin` manually before erroring out.  This should allow most users to not have to worry about setting the `$CARGO` or `$PATH` variables for VSCode, which can be difficult e.g. on macOS as discussed in #3118.

I've attempted to replace all calls to `cargo`, `rustc`, and `rustup` in rust-analyzer with appropriate invocations of `get_path_for_executable()`; I don't think I've missed any in Rust code, but there is at least one invocation in TypeScript code which I haven't fixed.  (I'm not sure whether it's affected by the same problem or not.) https://github.com/rust-analyzer/rust-analyzer/blob/a4778ddb7a00f552a8e653bbf56ae9fd69cfe1d3/editors/code/src/cargo.ts#L79

I'm sure this PR could be improved a bunch, so I'm happy to take feedback/suggestions on how to solve this problem better, or just bikeshedding variable/function/crate names etc.

cc @Veetaha 

Fixes #3118.

### CODE REVIEW

**Comment by Veetaha** [comment]
@cdisselkoen I added a PR to your branch to add TS part of the fix, see https://github.com/cdisselkoen/rust-analyzer/pull/1

**Comment by Veetaha** [comment]
I think it is reasonable to link this PR with the source issue by adding "fixes: #3118" to the description

File: crates/ra_env/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+                path.push(executable_name);
+                if is_valid_executable(&path) {
+                    Some(path.into_os_string().into_string().expect("Invalid Unicode in path"))
+                } else {
+                    None
+                }
+            } else {
+                None
+            }
+        };
```
Comment (Veetaha) [inline crates/ra_env/src/lib.rs:51]: I think this code can benefit from early returns to simplify it.

Comment (cdisselkoen) [reply crates/ra_env/src/lib.rs:51]: Will make the change.  I know some prefer not to use early returns, but if people are fine with them here I agree that they will simplify this.

Comment (cdisselkoen) [reply crates/ra_env/src/lib.rs]: Fixed in f64740b

File: crates/ra_env/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+use std::env;
+use std::path::Path;
+use std::process::Command;
+
+/// Return a `String` to use for the given executable.
+///
+/// E.g., `get_path_for_executable("cargo")` may return just `cargo` if that
+/// gives a valid Cargo executable; or it may return a full path to a valid
+/// Cargo.
+pub fn get_path_for_executable(executable_name: impl AsRef<str>) -> Result<String> {
```
Comment (matklad) [inline crates/ra_env/src/lib.rs:15]:
```suggestion
pub fn get_path_for_executable(executable_name: impl AsRef<str>) -> Result<PathBuf> {
```

File: crates/ra_env/Cargo.toml [hunk 3]
```diff
@@ -0,0 +1,9 @@
+[package]
+edition = "2018"
+name = "ra_env"
+version = "0.1.0"
+authors = ["rust-analyzer developers"]
+
+[dependencies]
+anyhow = "1.0.26"
+dirs = "2.0"
```
Comment (matklad) [inline crates/ra_env/Cargo.toml:9]: I feel it's better to keep this as a module in `rust-analyzer` crate rather than a separate crate.

Comment (matklad) [reply crates/ra_env/Cargo.toml:9]: Ah, we use it in more than one crate.... let me thing about where is it best to put this then...

**Comment by Veetaha** [comment]
I found [a deny](https://github.com/hyperium/tonic/blob/68d2ab3339f1cc8bf4cf90c6c9fb37dbae251425/deny.toml#L7-L9) in `tonic` repo for `dirs` crate. I am not sure whether we should listen to it anyway...

**Comment by cdisselkoen** [comment]
I chose the `dirs` crate based on the deprecation message in the official stdlib docs: https://doc.rust-lang.org/std/env/fn.home_dir.html

File: crates/ra_env/src/lib.rs (hunk 2 above)
Comment (cdisselkoen) [reply crates/ra_env/src/lib.rs]: Fixed in 44b01ccff

File: crates/ra_env/Cargo.toml (hunk 3 above)
Comment (cdisselkoen) [reply crates/ra_env/Cargo.toml:9]: Maybe we should actually pull additional functionality into this new crate.  For instance, sysroot.rs has a function `run_command_in_cargo_dir`:
https://github.com/rust-analyzer/rust-analyzer/blob/9cb55966fe0fee791072f275ac55b90b8ee13e32/crates/ra_project_model/src/sysroot.rs#L91
which maybe the other callsites could benefit from, I'm not sure.

**Comment by matklad** [comment]
>I chose the dirs crate based on the deprecation message 

Hm, looks like I forgot to submit a comment? We should do what cargo does here, cargo uses home crate

https://github.com/rust-lang/cargo/blob/master/src/cargo/util/config/mod.rs#L1554-L1556


https://github.com/rust-lang/cargo/blob/c719a05a81339ec6626965871fb93dcc6be8c14c/src/cargo/util/paths.rs#L87-L111

**Comment by cdisselkoen** [comment]
Updated to use `home` crate instead of `dirs`

**Comment by matklad** [comment]
bors r+

Thanks!
