### PR TITLE
fix(completions): improve fn_param

### LINKED ISSUE #11085: Parameter completions should insert a `,` if followed by another parameter
```rs
fn foo(bar: ()) {}
fn foo2(ba$0 baz: ()) {}
```
Selecting the `bar: ()` completion here should insert `bar: (), ` instead of just `bar: ()`

### PR DESCRIPTION
**Pull request by dbofmmbt**
- insert commas around when necessary
- only suggest `self` completions when param list is empty
- stop suggesting completions for identifiers which are already on the param list

Closes #11085

### CODE REVIEW

File: crates/ide_completion/src/completions/fn_param.rs [hunk 1]
```diff
@@ -44,32 +42,86 @@ pub(crate) fn complete_fn_param(acc: &mut Completions, ctx: &CompletionContext)
...
+    fn_params.try_for_each(|param| {
+        let whole_param = param.syntax().text().to_string();
+        file_params.remove(&whole_param);
+
+        let binding = param.pat()?.syntax().text().to_string();
+
+        file_params.retain(|_, v| v != &binding);
+        Some(())
+    })
+}
```
Comment (Veykril) [inline crates/ide_completion/src/completions/fn_param.rs:91]: We shouldn't break out of everything if we find a param with a missing pattern, and instead just ignore this one faulty param

File: crates/ide_completion/src/completions/fn_param.rs [hunk 2]
```diff
@@ -44,32 +42,86 @@ pub(crate) fn complete_fn_param(acc: &mut Completions, ctx: &CompletionContext)
...
+    if should_add_self_completions(ctx, param_list) {
         self_completion_items.into_iter().for_each(|self_item| {
             add_new_item_to_acc(ctx, acc, self_item.to_string(), self_item.to_string())
         });
     }
 
-    params.into_iter().for_each(|(label, lookup)| add_new_item_to_acc(ctx, acc, label, lookup));
+    file_params.into_iter().try_for_each(|(whole_param, binding)| {
+        Some(add_new_item_to_acc(ctx, acc, surround_with_commas(ctx, whole_param)?, binding))
+    })?;
```
Comment (Veykril) [inline crates/ide_completion/src/completions/fn_param.rs:73]: No need to exit on None here either, though technically speaking this shouldn't ever happen anyways I think(unless macros could expand into params with they can't to my knowledge)

File: crates/ide_completion/src/completions/fn_param.rs [hunk 3]
```diff
@@ -44,32 +42,86 @@ pub(crate) fn complete_fn_param(acc: &mut Completions, ctx: &CompletionContext)
...
+}
+
+fn surround_with_commas(ctx: &CompletionContext, param: String) -> Option<String> {
+    let next_token = {
+        let t = ctx.token.next_token()?;
+        if !matches!(t.kind(), SyntaxKind::WHITESPACE) {
+            t
+        } else {
+            t.next_token()?
+        }
```
Comment (Veykril) [inline crates/ide_completion/src/completions/fn_param.rs:107]:
```suggestion
        match t.kind() {
            SyntaxKind::WHITESPACE => 
            _ => t.next_token()?
        }
```

**Review by Veykril — COMMENTED** [review]
Some great QoL changes for params, thanks!
bors d+

File: crates/ide_completion/src/completions/fn_param.rs (hunk 1 above)
Comment (dbofmmbt) [reply crates/ide_completion/src/completions/fn_param.rs]: Thank you for the observation, I'm used to work on projects which almost never ignore errors, so that was somewhat automatic :laughing:

File: crates/ide_completion/src/completions/fn_param.rs (hunk 2 above)
Comment (dbofmmbt) [reply crates/ide_completion/src/completions/fn_param.rs]: I see... :thinking:  I added a fallback for the original parameter itself instead of bubbling the Option up, so even if it ever happens, it'll be alright.
