### PR TITLE
More correct method resolution

### LINKED ISSUE #2435: Wrong inference for `clone()`
image

```rust
#[derive(Clone)]
struct Test();
fn test() {
    let t = &Test();
    let t = t.clone();
}
```

### PR DESCRIPTION
**Pull request by flodiebold**
This should fix the order in which candidates for method resolution are considered, i.e. `(&Foo).clone()` should now be of type `Foo` instead of `&Foo`. It also checks for inherent candidates that the self type unifies properly with the self type in the impl (i.e. `impl Foo<u32>` methods will only be considered for `Foo<u32>`).

To be able to get the correct receiver type to check in the method resolution, I needed the unification logic, so I extracted it to the `unify.rs` module.

Should fix #2435.

### CODE REVIEW

File: crates/ra_hir_ty/src/infer/unify.rs [hunk 1]
```diff
@@ -153,10 +159,268 @@ impl<T> Canonicalized<T> {
...
+            // Unifying MaybeNeverTypeVar and TypeVar will let the latter become MaybeNeverTypeVar.
+            // Unifying MaybeNeverTypeVar and other concrete type will let the former become it.
+            (Ty::Infer(InferTy::TypeVar(tv)), other)
+            | (other, Ty::Infer(InferTy::TypeVar(tv)))
+            | (Ty::Infer(InferTy::MaybeNeverTypeVar(tv)), other)
+            | (other, Ty::Infer(InferTy::MaybeNeverTypeVar(tv)))
+            | (Ty::Infer(InferTy::IntVar(tv)), other @ ty_app!(TypeCtor::Int(_)))
+            | (other @ ty_app!(TypeCtor::Int(_)), Ty::Infer(InferTy::IntVar(tv)))
+            | (Ty::Infer(InferTy::FloatVar(tv)), other @ ty_app!(TypeCtor::Float(_)))
+            | (other @ ty_app!(TypeCtor::Float(_)), Ty::Infer(InferTy::FloatVar(tv))) => {
```
Comment (kjeremy) [inline crates/ra_hir_ty/src/infer/unify.rs]: This is hard to read but I'm not sure how I would clean it up.

File: crates/ra_hir_ty/src/infer.rs [hunk 2]
```diff
@@ -36,11 +36,13 @@ use ra_prof::profile;
...
     primitive::{FloatTy, IntTy},
     traits::{Guidance, Obligation, ProjectionPredicate, Solution},
-    ApplicationTy, InEnvironment, ProjectionTy, TraitEnvironment, TraitRef, Ty, TypeCtor,
-    TypeWalk, Uncertain,
+    ApplicationTy, InEnvironment, ProjectionTy, TraitEnvironment, TraitRef, Ty, TypeCtor, TypeWalk,
+    Uncertain,
 };
 use crate::{db::HirDatabase, infer::diagnostics::InferenceDiagnostic};
 
+pub use unify::unify;
```
Comment (matklad) [inline crates/ra_hir_ty/src/infer.rs]: Can this be `pub(crate)`?

File: crates/ra_hir_ty/src/method_resolution.rs [hunk 3]
```diff
@@ -381,7 +412,31 @@ fn is_valid_candidate(
...
+                        .push(self_ty.value.clone())
+                        .fill_with_unknown()
+                        .build(),
+                    hir_def::ContainerId::ImplId(impl_id) => {
+                        let vars =
+                            Substs::build_for_def(db, impl_id).fill_with_bound_vars(0).build();
+                        let self_ty_with_vars = db.impl_self_ty(impl_id).subst(&vars);
+                        let self_ty_with_vars =
+                            Canonical { num_vars: vars.len(), value: &self_ty_with_vars };
+                        if let Some(substs) = super::infer::unify(self_ty_with_vars, &self_ty.value)
```
Comment (matklad) [inline crates/ra_hir_ty/src/method_resolution.rs]: match might read better here

File: crates/ra_hir_ty/src/infer/unify.rs (hunk 1 above)
Comment (matklad) [reply crates/ra_hir_ty/src/infer/unify.rs]: Yeah. I feel that type inference is that sort of code where the essential complexity is pretty high, and the only way to make sure that code is maintainable is thorough test coverage.

**Comment by matklad** [comment]
LGTM!

File: crates/ra_hir_ty/src/infer.rs (hunk 2 above)
Comment (flodiebold) [reply crates/ra_hir_ty/src/infer.rs]: done

File: crates/ra_hir_ty/src/method_resolution.rs (hunk 3 above)
Comment (flodiebold) [reply crates/ra_hir_ty/src/method_resolution.rs]: that's refactored away :slightly_smiling_face:
