### PR TITLE
Automatically detect the rustc-src directory (fixes #3517)

### LINKED ISSUE #3517: rust-analyzer can't get data on rustc internals
When using rust-analyzer on clippy for example, it seems to fail to get a lot of info on functions/types that come from rustc, for example:
````rust
#![feature(rustc_private)]
extern crate rustc_lint;

pub fn register_pre_expansion_lints(_store: &mut rustc_lint::LintStore) {}

fn main() {}
````
Hovering `rustc_lint::LintStore` did not provide any type information.

I tried the same with the clippy submodule inside the rustc-repo hoping that could solve it but to no avail.

### PR DESCRIPTION
**Pull request by bnjbvr**
If the configured rustcSource was not set, then try to automatically
detect a source for the sysroot rustc directory.

I wasn't sure how to do it in the case of the project.json file, though.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Fwiw, this is blocked by https://github.com/rust-lang/rust/pull/81997 so it works properly.

**Comment by matklad** [comment]
`rustcSource` is intentionally not auto-discovered. This is needed only when you work with `#![rusc_private]`, which is not an officially supported use case.

**Comment by bnjbvr** [comment]
I didn't know this, ok then. May I add that it can be useful in some cases, e.g. when a rustc version is pinned to a specific nightly, as may be done in alternative rustc compiler backends? (it's the case for rust-gpu right now)
Or would you advise having a project-specific LSP settings.json in this specific case?

**Comment by matklad** [comment]
Yeah, I'd probably advice to commint settings.json to git. What we might do as well is so have opt-in auto-discovery. Ie, if the settings explicitly contain `"rustSrc": "discover"`, we run this logic. What we need to avoid is adding `rustSrc` to all the users.

**Comment by bnjbvr** [comment]
Cool idea; do you mean `rustcSource` could be set to `discover`? I'm happy to try it here.

**Comment by bnjbvr** [comment]
I've now implemented this. It's a bit convoluted so that we're able to keep feature parity, namely the possibility to indicate a path relative to the root path; please let me know what you think of it!

File: crates/project_model/src/sysroot.rs [hunk 1]
```diff
@@ -15,6 +15,7 @@ use crate::utf8_stdout;
 #[derive(Default, Debug, Clone, Eq, PartialEq)]
 pub struct Sysroot {
     crates: Arena<SysrootCrateData>,
+    pub rustc_src_dir: Option<AbsPathBuf>,
```
Comment (matklad) [inline crates/project_model/src/sysroot.rs:18]: I don't think we need this field here. We can run discovery logic in the `if path_to_rustc_src == "discover" {` branch.

File: crates/project_model/src/cargo_workspace.rs [hunk 2]
```diff
@@ -63,8 +63,10 @@ pub struct CargoConfig {
     /// when debugging isolated issues.
     pub no_sysroot: bool,
 
-    /// rustc private crate source
-    pub rustc_source: Option<AbsPathBuf>,
+    /// Text-form path to the rustc's private crates source, or "discover" to find them
+    /// automatically.
+    /// Keep the root path around so we can reference relative paths to the private crates source.
+    pub rustc_source: Option<(AbsPathBuf, String)>,
```
Comment (matklad) [inline crates/project_model/src/cargo_workspace.rs:69]: Year, this feels pretty awkward, especially because this puts `String -> PathBuf` conversion at the wrong layer. It should happen when we read config, not when we try to use the data. Let's introduce a proper enum here

```
enum RustcSource {
    Path(AbsPathBuf),
    Discover,
}
```

**Comment by bnjbvr** [comment]
Thanks for the review! The new version is much simpler :+1:
