### PR TITLE
fix: Make fill_match_arms assist handle doc(hidden) and non_exhaustive

### LINKED ISSUE #11499: Fill match arms assist adds arms for doc(hidden) enum variants
```
let foo: std::io::ErrorKind = todo!();
match foo {} // Fill match arms
```

results in a long list of match arms, the last of which is

```
std::io::ErrorKind::Uncategorized => todo!(),
```

even though that variant is `#[doc(hidden)]` (and unstable).

**rust-analyzer version**: `02904e99a 2022-02-14 stable`  
**rustc version**: `rustc 1.60.0-nightly (498eeb72f 2022-01-31)`  
**relevant settings**: -

### LINKED ISSUE #11500: Fill match arms assist fails to add a wildcard arm for non-exhaustive enums
```
let foo: std::io::ErrorKind = todo!();
match foo {} // Fill match arms
```

results in a long list of match arms (the last of which is invalid, see #11499), but fails to include a match arm like

```
_ => todo!(),
```

which is needed because `ErrorKind` is `#[non_exhaustive]`.

**rust-analyzer version**: `02904e99a 2022-02-14 stable`  
**rustc version**: `rustc 1.60.0-nightly (498eeb72f 2022-01-31)`  
**relevant settings**: -

### PR DESCRIPTION
**Pull request by OleStrohm**
Fixes #11499
Fixes #11500
This keeps track of the relevant attributes and adds in a wildcard pat at the end of the match when necessary.

I decided to do them in the same PR since they both needed the ability to add a wildcard arm, and so their changes would overlap if done separately, but I'll split them up if that seems better.

This is my first PR to rust-analyzer, so all feedback is greatly appreciated!

### CODE REVIEW

**Review by Veykril — COMMENTED** [review]
Looks good to me, with one possible improvement.
If the match arms we add are of an enum that is defined in the same crate as the source we are in we should ignore the attributes.

You can get the current crate we in from the module variable fetched via `sema.scope`

File: crates/ide_assists/src/handlers/add_missing_match_arms.rs [hunk 1]
```diff
@@ -86,7 +85,10 @@ pub(crate) fn add_missing_match_arms(acc: &mut Assists, ctx: &AssistContext) ->
         let missing_pats = variants
             .into_iter()
             .filter_map(|variant| {
-                Some((build_pat(ctx.db(), module, variant)?, variant.has_doc_hidden(ctx.db())))
+                Some((
+                    build_pat(ctx.db(), module, variant)?,
+                    variant.should_be_hidden(ctx.db(), module.krate()),
+                ))
```
Comment (Veykril) [inline crates/ide_assists/src/handlers/add_missing_match_arms.rs:91]: Fetching the crate of the variants looks a bit wrong to me, it would make more sense in my eyes to fetch enum's crate once, compare that and then skip the should_be_hidden checks.
So something like
```rs
let different_krate = module.krate() != enum_def.krate();
```

```suggestion
                Some((
                    build_pat(ctx.db(), module, variant)?,
                    different_crate && variant.should_be_hidden(ctx.db()),
                ))
```

Comment (OleStrohm) [reply crates/ide_assists/src/handlers/add_missing_match_arms.rs:91]: I agree that this would be better, but this isn't as easily extended to the tuple case, as the enum_def isn't available where I would need it to be

Comment (Veykril) [reply crates/ide_assists/src/handlers/add_missing_match_arms.rs:91]: Ah ye okay I see, then that's fine.

**Comment by Veykril** [comment]
Thanks!
bors r+

**Comment by jplatte** [comment]
Thanks! ❤️
