### PR TITLE
Fix panic in split/merge import assists

### LINKED ISSUE #4368: "called `Option::unwrap()` on a `None` value" in src/ast/make.rs:303:16
I'm debugging the hang/crash I saw while hacking on rustc's MIR transforms with rust-analyzer enabled, and this backtrace shows up quite a few times in the output (I don't think it's what causes the hang/crash though):

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/ra_syntax/src/ast/make.rs:303:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: ra_syntax::ast::make::path_from_text
  15: ra_syntax::ast::make::path_unqualified
  16: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix::split_path_prefix
  17: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix
  18: ra_assists::handlers::merge_imports::try_merge_trees
  19: <core::iter::adapters::Copied<I> as core::iter::traits::iterator::Iterator>::try_fold
  20: ra_assists::handlers::merge_imports::merge_imports
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: ra_assists::resolved_assists
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  25: ra_ide::Analysis::assists
  26: rust_analyzer::main_loop::handlers::handle_code_action
  27: <F as threadpool::FnBox>::call_box
```

I did not try to use the merge imports assist here.

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #4368 #4905

Not sure if this is the best solution here. Maybe the `make` functions should be fallible? We generally seem to be playing whack-a-mole with panics in assists, although most of them are `unwrap`s in the assist code.

### CODE REVIEW

**Comment by matklad** [comment]
Can we add a test here? `if segment.syntax().text_range().is_empty()` sounds like a bug in the parser actually -- the only node that is allowed to be empty is the top-level `SourceFile` (we need to tighten our parsing invariants some day...).

>Not sure if this is the best solution here. Maybe the make functions should be fallible?

Yup, I have been thinking about this for a while... Not sure what's the best short-term solution here. 

I don't want to make `make::*` failable, as that would mean that you have to effectively construct edit *before* resolving assists. One solution is to rewrite `make::*` to *not* rely on reparsing from text. That way, we can always construct *some* syntax tree, whatever bogus arguments we receive. 

But doing that is a bunch of work which I'd prefer to defer.

**Comment by lnicola** [comment]
Added a test. Two actually, but the `merge_imports` one works even without the fix, so dunno.

**Comment by matklad** [comment]
Yup, we get an empty node from the parser:

```
parent = Path {
    syntax: PATH@5..11
      PATH@5..8
        PATH_SEGMENT@5..8
          NAME_REF@5..8
            IDENT@5..8 "std"
      COLON2@8..10 "::"
      WHITESPACE@10..11 "\n"
      PATH_SEGMENT@11..11
    ,
}
```

I think we need to abondon the in-progress node (If we haven't eaten the `::`) here:

https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_parser/src/grammar/paths.rs#L87-L90

**Comment by lnicola** [comment]
Think we should close this and fix the parser instead? I'm not sure how to do that.

**Comment by matklad** [comment]
I think we should both fix the parser and add a regression tests.

This should fix the parser, but it might regress other things

```diff
diff --git a/crates/ra_parser/src/grammar/paths.rs b/crates/ra_parser/src/grammar/paths.rs
index 428aa711e..4ab33d3d6 100644
--- a/crates/ra_parser/src/grammar/paths.rs
+++ b/crates/ra_parser/src/grammar/paths.rs
@@ -73,7 +73,9 @@ fn path_segment(p: &mut Parser, mode: Mode, first: bool) {
         }
         p.expect(T![>]);
     } else {
+        let mut empty = true;
         if first {
+            empty = false;
             p.eat(T![::]);
         }
         match p.current() {
@@ -85,6 +87,9 @@ fn path_segment(p: &mut Parser, mode: Mode, first: bool) {
             // use crate::foo;
             T![self] | T![super] | T![crate] => p.bump_any(),
             _ => {
+                if empty {
+                    m.abandon(p);
+                }
                 p.err_recover("expected identifier", items::ITEM_RECOVERY_SET);
             }
         };
```

**Comment by matklad** [comment]
>This should fix the parser, but it might regress other things

Bonus points for surveying other calls to abandon and cheking if something like `m.abandon_if_empty()` makes sense.

**Comment by lnicola** [comment]
How do I make a `.rast` from an inline parser test? I tried `cargo xtask codegen`, then `UPDATE_EXPECTATIONS=1 cargo qt`, but only got the `.rs`.

File: crates/ra_parser/src/grammar/paths.rs [hunk 1]
```diff
@@ -85,6 +87,12 @@ fn path_segment(p: &mut Parser, mode: Mode, first: bool) {
             // use crate::foo;
             T![self] | T![super] | T![crate] => p.bump_any(),
             _ => {
+                if empty {
+                    // test empty_segment
```
Comment (matklad) [inline crates/ra_parser/src/grammar/paths.rs:91]: I think this should be `test_err`

File: docs/dev/README.md [hunk 2]
```diff
@@ -348,6 +348,8 @@ To update test data, run with `UPDATE_EXPECTATIONS` variable:
 env UPDATE_EXPECTATIONS=1 cargo qt
 ```
 
+After adding a new inline test you need to run `cargo xtest codegen` and also update the test data as described above.
```
Comment (matklad) [inline docs/dev/README.md:351]: :heart: :heart: :heart:

File: crates/ra_parser/src/grammar/paths.rs (hunk 1 above)
Comment (matklad) [reply crates/ra_parser/src/grammar/paths.rs:91]: Right, it works becase we don't produce an error message here, but we should do this. It's a bug that it works with test and not test_err

Comment (lnicola) [reply crates/ra_parser/src/grammar/paths.rs:91]: Thing is, it fails with `test_err` because we don't produce an error. I see that `err_recover` calls `m.complete` so I'm not sure...

**Comment by flodiebold** [comment]
> I don't want to make make::* failable, as that would mean that you have to effectively construct edit before resolving assists. One solution is to rewrite make::* to not rely on reparsing from text. That way, we can always construct some syntax tree, whatever bogus arguments we receive.

> But doing that is a bunch of work which I'd prefer to defer.

Maybe we could do something intermediate like parse an 'example' from text and then replace nodes in that with the ones we want? E.g. instead of creating a qualified path from text by parsing `{}::{}`, parse `a::b` and then replace `a` and `b` afterwards.

File: crates/ra_parser/src/grammar/paths.rs (hunk 1 above)
Comment (matklad) [reply crates/ra_parser/src/grammar/paths.rs:91]: You don't produce error because you `return` before producing an error :-) I think you can just move the `if` after the next line?

Comment (lnicola) [reply crates/ra_parser/src/grammar/paths.rs:91]: But `err_recover` calls `m.complete`, so we can't call `abandon`? Or can we?

Comment (matklad) [reply crates/ra_parser/src/grammar/paths.rs:91]: `err_recover` doesn't use `m` at all?

File: crates/ra_syntax/test_data/parser/err/0004_use_path_bad_segment.rast [hunk 3]
```diff
@@ -9,8 +9,7 @@ SOURCE_FILE@0..12
             NAME_REF@4..7
               IDENT@4..7 "foo"
         COLON2@7..9 "::"
-        PATH_SEGMENT@9..11
-          ERROR@9..11
-            INT_NUMBER@9..11 "92"
+        ERROR@9..11
```
Comment (lnicola) [inline crates/ra_syntax/test_data/parser/err/0004_use_path_bad_segment.rast:12]: Not sure if this is fine...

File: crates/ra_parser/src/grammar/paths.rs (hunk 1 above)
Comment (lnicola) [reply crates/ra_parser/src/grammar/paths.rs]: I was looking at the following snippet from that method:

```rust
        let m = self.start();
        self.error(message);
        self.bump_any();
        m.complete(self, ERROR);
```

But it works, I guess, with a parsing difference in one of the existing tests.

**Comment by lnicola** [comment]
I think this is ready now.

File: crates/ra_syntax/test_data/parser/err/0004_use_path_bad_segment.rast (hunk 3 above)
Comment (matklad) [reply crates/ra_syntax/test_data/parser/err/0004_use_path_bad_segment.rast:12]: I think it is OK, though the old version was better.  Should be a part of #5006  really, in a sense that we probably should pass-in the parent marker into `err_recover` and let it chose whether to abandon or not. 

bors r+

Thanks!
