### PR TITLE
Include extra targets when the pkg_root is not the same as the target root.

### LINKED ISSUE #7715: unresolved-module in rapier repository
Hi, and thanks for an amazing tool!

I'm using rust-analyzer in VS code and am currently doing some work on this project: <https://github.com/dimforge/rapier/>

The problem is that rust-analyzer doesn't seem to work at all for that repository. I get no type annotations, and things like rename doesn't work.

rust-analyzer reports the problem `unresolved-module` for these lines: https://github.com/dimforge/rapier/blob/12c5dd4caa6af5750b682ba17229601e3a418155/src/lib.rs#L131:L136 despite the modules seemingly being in the normal place (e.g. https://github.com/dimforge/rapier/blob/12c5dd4caa6af5750b682ba17229601e3a418155/src/data/mod.rs).

Hopefully reproducing this problem will be as easy as checking out the above repository (not exactly a minimal reproduce though).

### PR DESCRIPTION
**Pull request by rezural**
Fixes #7715 

For example, if a sub-crate includes sets the path='../somewhere-else/lib.rs', the files will not be in pkg_root , but in the target root's parent.

It may actually be in root.parent().parent(), I'm not sure about that.

At the moment it is just a fix, are there any relevant tests that this could go in? I've got about 1 brain cell left... but im happy to add tests where appropriate.

### CODE REVIEW

File: crates/project_model/src/workspace.rs [hunk 1]
```diff
@@ -227,6 +227,25 @@ impl ProjectWorkspace {
...
+                                    .unwrap()
+                                    .parent()
+                                    .unwrap()
+                                    .to_path_buf()
+                                    .normalize()
+                                    != pkg_root
+                        })
+                        .map(|&tgt| cargo[tgt].root.parent().unwrap().to_path_buf())
+                        .collect();
+                    include.extend(extra_targets);
```
Comment (matklad) [inline crates/project_model/src/workspace.rs:247]:
```suggestion
                    // In case target's path is manually set in Cargo.toml to be
                    // outside the package root, at its parent as an extra include.
                    // An example of this situation would look like this:
                    //
                    // ```toml
                    // [lib]
                    // path = "../../src/lib.rs"
                    // ```
                    let extra_targets = cargo[pkg]
                        .targets
                        .iter()
                        .filter(|&&tgt| cargo[tgt].kind == TargetKind::Lib)
                        .filter_map(|&tgt| cargo[tgt].root.parent())
                        .filter(|path| !path.starts_with(pkg_root));
                    include.extend(extra_targets);
```

Rather than manually checking equality, let's check if a target's path is within the package. Would this work?

Comment (rezural) [reply crates/project_model/src/workspace.rs]: Almost worked, much cleaner. thanks.

**Comment by rezural** [comment]
Rebased on master.

I'll have a look if there is anywhere obvious to put a unit test, this was a little tricky to get right.

Thanks

File: crates/project_model/src/workspace.rs [hunk 2]
```diff
@@ -234,6 +234,23 @@ impl ProjectWorkspace {
...
+                        // ```toml
+                        // [lib]
+                        // path = "../../src/lib.rs"
+                        // ```
+                        let extra_targets = cargo[pkg]
+                            .targets
+                            .iter()
+                            .filter(|&&tgt| cargo[tgt].kind == TargetKind::Lib)
+                            .filter_map(|&tgt| cargo[tgt].root.parent())
+                            .map(|tgt| tgt.normalize().to_path_buf())
```
Comment (rezural) [inline crates/project_model/src/workspace.rs:250]: FYI, path.starts_with(pkg_root.clone()) always returned true, unless we normalized.

**Comment by rezural** [comment]
Did I say unit test? More integration test. Tricky to do for now, it would need fixtures (i.e. a crate), and I dont see any of those in rust-analyzer yet.

perhaps if the vfs could be arbitrarily populated with paths & data, but I don't believe the vfs is there yet.

I'm willing to have a look into this if you guys see a benefit.

Also, it was very helpful to debug straight from the existing integration_test.rs, which is for profiling I believe. I was getting nowhere until I took a step back & went down that route. This would probably be helpful to be documented in the debugging documentation. I'll put up a PR.

Hopefully you are happy with this, I believe it is ready & wants a review.

Thanks

**Comment by matklad** [comment]
bors r+

Thanks!

Yeah, sadly, the testing story here is TBA. Our general philosophy is that we don’t test code which integrates different processes together (ra<->cargo, ra<->vscode) — such tests are annoying, slow, and brittle, and the actual problems are often outside of what’s tested.

But, at this point,  I think it’s clear that this module contains too much of an actual logic, so its insane that this has zero tests. My plan is to shake this module a bit and externalize all IO, such that we can write reasonable tests based on cargo metadata jsons committed as test data.

File: crates/project_model/src/workspace.rs [hunk 3]
```diff
@@ -234,6 +234,23 @@ impl ProjectWorkspace {
...
+                            .filter(|path| !path.starts_with(pkg_root.clone()));
```
Comment (lnicola) [inline crates/project_model/src/workspace.rs:251]: Nit: #9415
