### PR TITLE
Fix inference of function pointer return types

### LINKED ISSUE #3852: {unknown} type deduced for a function pointer with omitted return type stored in a struct
rust-analyzer version: nightly (e300e1e)

Reporduction:
```rust
struct Vtable {
    method: fn()
}

fn main() {
    let vtable = Vtable {
        method: || {}
    };
    let m = vtable.method;
}

```
<details>
<summary>Screen</summary>

image

</details>

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #3852.

r? @flodiebold

### CODE REVIEW

File: crates/ra_hir_def/src/type_ref.rs [hunk 1]
```diff
@@ -93,7 +93,11 @@ impl TypeRef {
...
             ast::TypeRef::PlaceholderType(_inner) => TypeRef::Placeholder,
             ast::TypeRef::FnPointerType(inner) => {
-                let ret_ty = TypeRef::from_ast_opt(inner.ret_type().and_then(|rt| rt.type_ref()));
+                let ret_ty = inner
+                    .ret_type()
+                    .and_then(|rt| rt.type_ref())
+                    .map(TypeRef::from_ast)
+                    .unwrap_or_else(|| TypeRef::Tuple(Vec::new()));
                 let mut params = if let Some(pl) = inner.param_list() {
                     pl.params().map(|p| p.ascribed_type()).map(TypeRef::from_ast_opt).collect()
```
Comment (lnicola) [inline crates/ra_hir_def/src/type_ref.rs:102]: Is the `from_ast_opt` fine? I couldn't get it to show up as unknown in my tests.

Comment (flodiebold) [reply crates/ra_hir_def/src/type_ref.rs:102]: Yeah, I think this can only happen with parse errors, if at all.
