### PR TITLE
vscode: fix binary is not functional on windows

### LINKED ISSUE #3087: "Downloaded language server binary is not funtional" error on Windows
After trying to install the language server binary through the popup today, the following error occurred:

Screenshot 2020-02-10 17 43 21

This occurs on Rust 1.41 on Windows 10. Possibly related to https://github.com/rust-analyzer/rust-analyzer/issues/3073

### LINKED ISSUE #3090: Automatic downloading language server with multiple VS Code windows open causes failure
Hi, 

Great extension, thanks! I've just been through the install process (adding the extension - not building from source) and, unfortunately, I had multiple VS Code windows open at the same time. This caused the language server not to download properly on some of the VS Code windows. I don't know if the language server is scoped to the project or the entire VS Code installation. If the latter is the case then I guess there should be some sort of global mutex to protect the installation.

Windows 10, VS Code v1.42

David

### PR DESCRIPTION
**Pull request by Veetaha**
This is my first approach to fix this error, need to double-check this on windows still...
Fixes #3087
Fixes #3090

### CODE REVIEW

**Comment by matklad** [comment]
Seems reasonable!

**Comment by Veetaha** [comment]
Switched to `stream.pipeline`, this should prevent us from making this kind of errors at all

**Comment by Veetaha** [comment]
Wait, rechecked on windows, and this pipeline api doesn't actually work ...

**Comment by Veetaha** [comment]
God, I love Node's API. Will revert to the first impl, since it does work...

**Comment by Veetaha** [comment]
Now we are ready to merge

**Comment by marcogroppo** [comment]
Just trying to understand: what happens if there is a **write** error? Is there the possibility that the promise will stay in the pending status forever?

**Comment by Veetaha** [comment]
This would be unfortunate, though yes, I thought about it and handling double reject would bring some amount of "who-knows-what-it-is-doing" code. For this reason I tried to switch to stream.pipeline() API, but it doesn't resolve when the write-stream is closed either. I'll try to come up with better error handling here, but in a separate PR, let leave this one as one particular fix an nothing more

**Comment by Veetaha** [comment]
@marcogroppo , I've just checked [ECAMScript specs](https://tc39.es/ecma262/#sec-promise-reject-functions). And found that we do can call `reject()` more than 1 time, so yes, we can omit the code that ensures that `reject` is not called repeatedly. just `on("close", resolve).on("error", reject)` will work. I'll create a PR for that today.

File: editors/code/src/installation/download_file.ts [hunk 1]
```diff
@@ -27,8 +27,7 @@ export async function downloadFile(
             readBytes += chunk.length;
             onProgress(readBytes, totalBytes);
         })
-        .on("end", resolve)
         .on("error", reject)
-        .pipe(fs.createWriteStream(destFilePath))
+        .pipe(fs.createWriteStream(destFilePath).on("close", resolve))
```
Comment (yoshuawuyts) [inline editors/code/src/installation/download_file.ts]: It's recommended to use [`stream.pipeline`](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) in all cases over `stream.pipe`. Formerly this functionality was only available in the [`pump`](https://github.com/mafintosh/pump) and `pumpify` packages, but was added two years ago to fix the problems around `pipe` (in particular: error handling, and correctly detecting close events). Also when used with `util.promisify` it allows simplifying Promise construction for the pipeline:

```rust
const pipeline = util.promisify(stream.pipeline);

let bs = response.body;
  .on("data", (chunk: Buffer) => {
    readBytes += chunk.length;
    onProgress(readBytes, totalBytes);
  });
await pipeline(bs, fs.createWriteStream(destFilePath);
```
_nb:_ I used to be on the node streams wg up until a few years ago 😅

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: @yoshuawuyts , thank you for the suggestion, I did look into `stream.pipeline()`, but then reverted back, since it doesn't resolve the promise when the write-stream is closed. You can see my comments about truing trying to incorporate it in this MR, but still it didn't fix the error, but my initial approach with `.on("close")` did, anyway... Maybe this is a bug in NodeJS?

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: Though, no, I cannot reproduce that again with `stream.pipeline()`... I need to recheck it on my home laptop where I did saw it was not working. Or maybe I just was overwhelmed by the bug and somehow was running the wrong code? I am not sure... Thank you for the pointer anyway, I'll double-recheck that `stream.pipeline()` does resolve the promise when the write-stream is closed today!

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: Though, no, here is a [gist of the reproduction](https://gist.github.com/Veetaha/21c6bcab38cde97445364eaa9c0ff89b).
When I run it, I get `RESOLVED` printed before `CLOSED`, though there is no `EBUSY` error on my current PC...
image

Comment (yoshuawuyts) [reply editors/code/src/installation/download_file.ts]: Okay, so this turned out to be a fun one.

In the example you're listening for the `"close"` event, which you would rightfully assume is called "at the end of the pipeline". However that's not what it does: it's emitted when the underlying file descriptor is closed. Which because Node.js doesn't have destructors it's emitted when the program is closed: which means it's last.

However if you listen for the `"finish"` event instead, it will trigger when you expect it to: namely when the writing to the writer has finished. The reason this doesn't also close the file descriptor is because it's possible to reuse the same write stream in multiple pipelines and the descriptor should be kept open.

If you want to close the file descriptor after the pipeline has finished, call `.destroy()` on the stream. The docs don't mention this, but it's the standard way of doing it and [I checked the source to double check](https://github.com/nodejs/node/blob/master/lib/internal/fs/streams.js#L415).

Either way: this is definitely harder than it should be, but at least with `pipeline` it's harder to get wrong.

## Example

I believe the downloadFile function should be defined like this to correctly wait for it to finish, and then close the fd:
```js
async function downloadFile(url, destFilePath) {
    let source = await fetch(url).body;
    let sink = fs.createWriteStream(destFilePath, { mode: 0o755 });
    await pipeline(source, sink);
    sink.destroy()
}
```

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: Thank you for the explanations. I did recheck that the first vairant without explicit `.destroy()` still yields `EBUSY`

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: But the second variant yields `EBUSY` too...

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: Here is the output on my home laptop. [Here is the code I ran and output I got](https://gist.github.com/Veetaha/37dcb5ca433ef319dcdc369b345aaece)

Comment (Fishrock123) [reply editors/code/src/installation/download_file.ts]: I am unsure, but if the issue is that the fd is not yet closed at the end of that code snippit, you may also want to promisify `sink.destroy()`.

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: @matklad, I did double-rechecked the pipeline API, even with an explicit `destroy()` call and it still doesn't work on my laptop on Windows. 
Tried to call `.end()` ([which moreover ensures that the stream is flushed](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_writable_end_chunk_encoding_callback)) instead of `.destroy()`, but that didn't change the day.
I get `EBUSY` error as originally. I do wish we could use this API and tried to switch to it while fixing the original bug, but anyway, it somehow doesn't work properly.
I'll create an issue under nodejs repo and if we are doing something wrong they should help, otherwise I propose to leave explicit `pipe()` calls and to merge #3092, since it does work now. Once we figure out what is going one I'll gladly switch to `stream.pipeline()`

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: We cannot promisify neither `.destroy()`, neither `.end()`, they are synchronous and don't accept any callbacks. One thing we can do is do the same 
```ts
const destFileStream = fs.createWriteStream(path, { mode });
await stream.pipeline(response.body, destFileStream);
stream.end();
return new Promise((resolve) => destFileStream.on("close", resolve));
```
This looks quite hacky...

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: Hmm, wait, `stream.end()` does accept an optional callback...

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: No `stream.end()` accepts a callback that is just attached to `'finish'` event...

I suppose we can use the snippet I wrote higher for now...

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: I've switched to `stream.pipeline()` with `.on("close")` in #3116. Let's leave it like that for now...
@matklad ?

Comment (Veetaha) [reply editors/code/src/installation/download_file.ts]: FYI: I have created an issue on `nodejs` repo regarding `stream.destroy()` not releasing the file handle immediatly.
https://github.com/nodejs/node/issues/31776
