### PR TITLE
Downgrade notify and use `RecommendedWatcher`

### LINKED ISSUE #9769: Fails to build on `x86_64-unknown-netbsd`
since #9686, because `notify` doesn't build.

Spotted in https://github.com/rust-lang/rust/pull/87719#issuecomment-891625996.

CC https://github.com/notify-rs/notify/issues/344

### PR DESCRIPTION
**Pull request by lnicola**
Closes #9769

bors r+

### CODE REVIEW

File: crates/vfs-notify/src/lib.rs [hunk 1]
```diff
@@ -83,9 +83,10 @@ impl NotifyActor {
                         self.watcher = None;
                         if !config.watch.is_empty() {
                             let (watcher_sender, watcher_receiver) = unbounded();
-                            let watcher = log_notify_error(RecommendedWatcher::new(move |event| {
-                                watcher_sender.send(event).unwrap()
-                            }));
+                            let watcher =
```
Comment (lnicola) [inline crates/vfs-notify/src/lib.rs:86]: This used to say `Watcher::new_immediate`, TBH I'm not even sure how that works :sweat_smile:.
