### PR TITLE
Fix syntax highlighting of recursive macros

### LINKED ISSUE #4694: "macro" exclamation point isn't highlighted within macros
I made macros italic to distinguish them from function calls:

```json
"editor.semanticTokenColorCustomizations": {
    "enabled": true,
    "rules": {
        "macro": {
            "italic": true
        }
    }
}
```

macros

As you can see, the exclamation point is only affected, if the macro is not itself in a macro. The same applies to the color.

I use the nightly version of rust-analyzer for VS Code.

### PR DESCRIPTION
**Pull request by ltentrup**
Add syntax highlighting for the BANG (`!`) token if the parent is `MACRO_CALL`.

Before:
before

After:
recursive-macro

Fixes #4694.

### CODE REVIEW

File: crates/ra_ide/src/syntax_highlighting/tests.rs [hunk 1]
```diff
@@ -325,6 +325,43 @@ impl Foo {
...
+                }
+            }
+        }
+    });
+}
+
+fn main() {
+    assert_eq!("1", format!("{}", 1));
+}
+"##
```
Comment (matklad) [inline crates/ra_ide/src/syntax_highlighting/tests.rs:358]: Let's minimize this test, and maybe fold it into the main highlighting test?  I'd love to avoid ballooning the amount of test data :)

Comment (ltentrup) [reply crates/ra_ide/src/syntax_highlighting/tests.rs]: I integrated a minimal example into the main highlighting test
