### PR TITLE
Don't block onEnter if request fails

### LINKED ISSUE #3286: Editing a rust file from outside the current workspace entirely blocked by RA.
I had one particular folder open which contains a rust project. Then a beginner sent me a `main.rs` file of their attempt at a Rust version of some C++ code. I opened the single file from my downloads folder and I was unable to edit the file.

To be clear, I don't mean that RA failed to provide help and I had to continue without it (which would be acceptable). I mean that I couldn't even press "enter" and add a newline to the file because every single input triggered a new "Rust file outside current workspace is not supported yet." error. I had to disable the plugin entirely and reload the program with the plugin off just to be able to edit the `main.rs` file.

Please, in the mean time, at least make keyboard edits pass through to the file normally so that a person can at least edit the file they have open (even if RA can't provide any help while they do it).

### PR DESCRIPTION
**Pull request by matklad**
closes #3286

bors r+
🤖

### CODE REVIEW

File: editors/code/src/commands/on_enter.ts [hunk 1]
```diff
@@ -19,6 +19,12 @@ async function handleKeypress(ctx: Ctx) {
     const change = await client.sendRequest<undefined | SourceChange>(
         'rust-analyzer/onEnter',
         request,
+    ).catch(
+        (_error: any) => {
+            // FIXME: switch to the more modern (?) typed request infrastructure
```
Comment (Veetaha) [inline editors/code/src/commands/on_enter.ts]: @matklad, yes, this is possible, we should abstract `client.sendRequest()` to 
```ts
function trySendRequest<T extends OurAPITypeInfo>(
    param: T["method"][["param"]
): Promise<T["return-type"]>
```
and encode the type information about our custom LSP api in `OurAPITypeInfo` interface.
I planned to do that refactor after tackling enhanced typing issues...

Comment (Veetaha) [reply editors/code/src/commands/on_enter.ts]: Or use separate functions:
```
function requestInlayHintsWithRetry(client, param: InlayHintsOpts): Promise<InlayHint[]>;
function requestOnEnter(param: OnEnterOpts): Promise<OnEnterResponse>;
```

Comment (Veetaha) [reply editors/code/src/commands/on_enter.ts]: @matklad which do you like most?

Comment (Veetaha) [reply editors/code/src/commands/on_enter.ts]: Taking the first approach we may abstract the type info in an npm package and share it with other ts plugins ( coc.nvim for example), though this may be too much overhead since our custom API is not so big

Comment (matklad) [reply editors/code/src/commands/on_enter.ts]: We don't need `OurAPITypeInfo`, we should use existing RPCMethodType: https://github.com/microsoft/vscode-languageserver-node/blob/f425af9de46a0187adb78ec8a46b9b2ce80c5412/client/src/client.ts#L99

Comment (Veetaha) [reply editors/code/src/commands/on_enter.ts]: @matklad , yeah but it doesn't contain types for our custom methods like `inlayHints` and `onEnter` , right? Might I ask you to show an example how you would make it this way?

**Comment by matklad** [comment]
Haven't looked into it, but I would be surprised if we can't create our
request types the same way the build-in request types are created

**Comment by Veetaha** [comment]
Okay, let me look into it.

Anyway their `sendRequest<T>(param: any)` already uses `any` which is annoys me a bit, so in my proposals we wrap this with our own types, do you have something against any of them?

**Comment by matklad** [comment]
I wouldn't be try to be more clever than the folks who build
vscode-languageserver-node. I almost completely trust their knowledge of
TypeScript and VS Code APIs. I definitely trust them more than myself.

**Comment by Veetaha** [comment]
Trust me.......

**Comment by Veetaha** [comment]
Please...

**Comment by Veetaha** [comment]
@matklad Though, no, don't trust me, just estimate the proposals rationally, please...

**Comment by matklad** [comment]
My main assumption here is that TypeScript part is not the core of the project, and so, when adding code to TypeScript, my two main concerns are:

* it should expos functionality of the server
* it should not slow down the development of the server

I explicitly don't want to spend effort on designing & developing the perfect VS Code plugin. I have only so many design cycles to spare, and I prefer to use them for the server part. For this reason, the two things I would value most in TypeScript code is:

* keeping it as small as possible (which includes minimizing dependencies)
* keeping it as boring as possible (which includes copy-pasted approaches, tried and testing in VS Code itself).

This is very different from the style of code in the server part, where I do want to engage in different API experiments to try things out. 

So, for me, just doing literally what `vscode-languageserver-node` does have a **huge** advantage: I don't need to *think* if the design is sound, because I know that it already works in production in a context, identical to what we have here.

**Comment by Veetaha** [comment]
I do understand this. If we do follow this principles, our current approach should be fine already, so that fixme is not very relevant, i.e. I don't see what kind of improvement you meant there @matklad
