### PR TITLE
Expand statements for macros in lowering

### LINKED ISSUE #6811: "Failed to parse macro invocation" when using puffin (regression)
Puffin is a nice little instrumented profiling library by @emilk .

It used to work well with rust-analyzer, but doesn't anymore since 0.2.408 or a very nearby version. 

image

## Complete repro

cargo.toml:
```toml
[package]
name = "repro"
[dependencies]
puffin = "0.3.1"
```

main.rs
```rust
fn main() {
    puffin::profile_function!();
}
```

The offending macro looks like this:
```rust
#[macro_export]
macro_rules! profile_function {
    () => {
        let _profiler_scope = if $crate::are_scopes_on() {
            Some($crate::ProfilerScope::new(
                $crate::current_function_name!(),
                $crate::current_file_name!(),
                "",
            ))
        } else {
            None
        };
    };
}
```

which doesn't look all that complicated but does call other macros from the macro - related to #6788 ? (EDIT: no, doesn't seem to be)

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fixes #6811

### CODE REVIEW

File: crates/hir_expand/src/db.rs [hunk 1]
```diff
@@ -395,7 +395,8 @@ fn to_fragment_kind(db: &dyn AstDatabase, id: MacroCallId) -> FragmentKind {
             FragmentKind::Expr
         }
         // FIXME: Expand to statements in appropriate positions; HIR lowering needs to handle that
```
Comment (matklad) [inline crates/hir_expand/src/db.rs:397]: should we remove the fixme?

Comment (edwin0cheng) [reply crates/hir_expand/src/db.rs]: fixed
