### PR TITLE
fix: Fix cases where `Merge Imports` would drop imports.

### LINKED ISSUE #11466: Merge imports with self and existing nested items gets rid of the latter
**rust-analyzer version**: rust-analyzer version: ba3305480 2022-02-07 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

Initial code:
```rust
use nest::p::{self, B};
use nest::{
    p::{A, C},
    q,
};

pub mod nest {
    pub mod p {
        pub struct A;
        pub struct B;
        pub struct C;
    }

    pub mod q {}
}
```

Expected:
```rust
use nest::{
    p::{self, B, A, C},
    q,
};
```

Actual:
```rust
use nest::{
    p::{self, B},
    q,
};
```

### PR DESCRIPTION
**Pull request by DropDemBits**
Fixes #11466

### CODE REVIEW

File: crates/ide_db/src/helpers/merge_imports.rs [hunk 1]
```diff
@@ -115,11 +115,13 @@ fn recursive_merge(lhs: &ast::UseTree, rhs: &ast::UseTree, merge: MergeBehavior)
                     let tree_contains_self = |tree: &ast::UseTree| {
                         tree.use_tree_list()
                             .map(|tree_list| tree_list.use_trees().any(|it| tree_is_self(&it)))
-                            .unwrap_or(false)
+                            // Glob imports aren't part of the use-tree lists,
+                            // so they need to be handled explicitly
+                            .or_else(|| tree.star_token().is_some().then(|| false))
```
Comment (Veykril) [inline crates/ide_db/src/helpers/merge_imports.rs:120]:
```suggestion
                            .or_else(|| tree.star_token().map(|_| false))
```
bors d+
