### PR TITLE
Fix extract_function with await

### LINKED ISSUE #9287: Extract into function assist fails to add `.await` when extracting an `async fn`
Since #8766, extracting some code into a function generates an `async fn` if that code includes a `.await` point. However, the call to the generated function is not `.await`ed, leading to the code not compiling in many cases, or even the code still compiling but the async task not being executed. For example, when extracting

```rust
tokio::time::sleep(Duration::from_millis(50)).await;
```

as `sleep50ms`, the call ends up as just

```rust
sleep50ms();
```

when it should be

```rust
sleep50ms().await;
```

### PR DESCRIPTION
**Pull request by sasurau4**
Fix #9287

### CODE REVIEW

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 1]
```diff
@@ -994,6 +994,9 @@ fn format_replacement(ctx: &AssistContext, fun: &Function, indent: IndentLevel)
         }
     }
     format_to!(buf, "{}", expr);
+    if body_contains_await(&fun.body) {
```
Comment (lnicola) [inline crates/ide_assists/src/handlers/extract_function.rs:997]: It doesn't matter too much, but we could pull this check up to avoid doing it twice.

**Comment by Veykril** [comment]
Just as a headsup CI failure is due to the new rust version and is already fixed on master

File: crates/ide_assists/src/handlers/extract_function.rs [hunk 2]
```diff
@@ -109,10 +109,15 @@ pub(crate) fn extract_function(acc: &mut Assists, ctx: &AssistContext) -> Option
 
             let new_indent = IndentLevel::from_node(&insert_after);
             let old_indent = fun.body.indent_level();
+            let is_body_contains_await = body_contains_await(&fun.body);
```
Comment (lnicola) [inline crates/ide_assists/src/handlers/extract_function.rs:112]: Let's call this body_has_await or something like that. I don't know if it can have the same name as the function.

**Comment by lnicola** [comment]
I'm on my phone, but I don't see anything off.

bors d+
