### PR TITLE
ide: dedupe or merge hover actions

### LINKED ISSUE #10780: Hovers with multiple messages incorrectly merge hover actions
```rs
struct Bar;
struct Foo { bar: Bar }

fn foo(Foo { bar }: &Foo) {}
```
Hovering the `bar` field in the pattern here gives an odd looking hover
image

The hover actions actually do not support repeated entries, which can happen currently if an ident maps to multiple definitions.
For type link hover actions this is no problem as we can merge them but, the other three actions do not allow this. In these cases we probably just want to drop any additional ones, as even if we enabled showing multiple ones of them it would probably confuse the reader if anything.

problematic line: https://github.com/rust-analyzer/rust-analyzer/blob/1c49667c5658e0f8f0fb496786071e2f9b6cd43c/crates/ide/src/hover.rs#L140

### PR DESCRIPTION
**Pull request by jhgg**
fixes #10780

### CODE REVIEW

File: crates/ide/src/hover.rs [hunk 1]
```diff
@@ -136,11 +136,12 @@ pub(crate) fn hover(
         .flatten()
         .unique_by(|&(def, _)| def)
         .filter_map(|(def, node)| hover_for_definition(sema, file_id, def, &node, config))
-        .reduce(|mut acc, HoverResult { markup, actions }| {
+        .reduce(|mut acc: HoverResult, HoverResult { markup, actions }| {
```
Comment (jhgg) [inline crates/ide/src/hover.rs:139]: I added this type annotation here because I noticed r-a was not able to infer the type of `acc` without it :(
