### PR TITLE
fix missing match arm false positive for enum with no variants

### LINKED ISSUE #3974: Incorrectly shows an error for matching an enum without variants
hyper contains a type `enum Never {}`. When this is matched against, RA (0.2.135) shows an error:

Screen Shot 2020-04-14 at 09 32 37

In contrast, rustc does not show an error.

### PR DESCRIPTION
**Pull request by JoshMcguigan**
fixes #3974

### CODE REVIEW

**Comment by JoshMcguigan** [comment]
I think the solution in this PR should work, but `cx.infer.variant_resolution_for_expr(cx.match_expr)` returns `None` in the following case:

```rust
enum Never {}

fn test_fn(never: Never) {
	match never {}
}
```

I think this is an inference issue related to the match expression coming from a function argument. Any thoughts on this @flodiebold? Places I should start looking? 

Note that in the IDE I do see `Never` as the type when I hover over the match expression, so perhaps this is some issue which only affects `variant_resolution_for_expr`?

File: crates/ra_hir_ty/src/_match.rs [hunk 1]
```diff
@@ -530,6 +532,16 @@ pub(crate) fn is_useful(
     matrix: &Matrix,
     v: &PatStack,
 ) -> MatchCheckResult<Usefulness> {
+    // Handle the special case of enums with no variants. In that case, no match
+    // arm is useful.
+    if let Some(enum_variant) = cx.infer.variant_resolution_for_expr(cx.match_expr) {
+        if let VariantId::EnumVariantId(enum_variant_id) = enum_variant {
+            if cx.db.enum_data(enum_variant_id.parent).variants.len() == 0 {
```
Comment (flodiebold) [inline crates/ra_hir_ty/src/_match.rs:539]: this can never be true, since you got the enum ID from one of its variants ;)

The problem here is that `variant_resolution_for_expr` is not the thing you need. It records the specific variant apreferred to by e.g. a path or record literal. If you have something like `Ok()`, the type of that is just `Result`, so we need to record the information that it was the `Ok` variant somewhere, and that's this field. But here you don't want the variant, you want the type, which you get through `cx.infer[cx.match_expr]`. To get the enum def ID, you could then use `ty.as_adt()` and match the `AdtId` (though we might need to unwrap references -- still not sure what the best way to deal with that is, maybe we should just generally strip all references from types in match checking...)

Comment (JoshMcguigan) [reply crates/ra_hir_ty/src/_match.rs]: Ah, this makes sense. Thanks for setting me on the right track!

**Comment by JoshMcguigan** [comment]
Sorry for the noise here. Converting back to draft because I have not yet covered the reference case (i.e. `&Never`).

**Comment by flodiebold** [comment]
> This seems a bit tricky, since TypeCtor::Ref seems to not contain any information about the type of the underlying thing being referenced.

The referenced type is a type parameter (`&'x T` is basically no different from `Ref<'x, T>`). There's actually `ty.as_reference()` for this purpose already.

**Comment by JoshMcguigan** [comment]
I've added a `deref` method on `Ty`, which recursively derences types until it gets a non-reference. This makes the test pass which was matching on a reference to the `Never` enum.

Let me know if there is a more appropriate name for this method. Or if it should go somewhere else. I thought about putting it in an `impl` block on `ApplicationTy`, but in that case I wasn't sure what the return type should be, since `parameters.as_single()` would still return a `Ty` and I wasn't sure if it was safe to assume that `Ty` would be an `ApplicationTy` in all cases. 

Also, I think this method could be useful when [comparing the type of the match expression to the pattern arms](https://github.com/rust-analyzer/rust-analyzer/blob/f1a07dbf5559e882f46e79ed2a299cf151b99498/crates/ra_hir_ty/src/expr.rs#L175)? But I'd like to do this in a follow up MR, because that change should come with some additional tests as well.

File: crates/ra_hir_ty/src/lib.rs [hunk 2]
```diff
@@ -680,6 +680,21 @@ impl Ty {
         }
     }
 
+    pub fn deref(&self) -> &Ty {
```
Comment (flodiebold) [inline crates/ra_hir_ty/src/lib.rs:683]: for the name, how about `strip_references`? I'd expect a `deref` to also handle the `Deref` trait, and deref just one layer.

File: crates/ra_hir_ty/src/lib.rs [hunk 3]
```diff
@@ -680,6 +680,21 @@ impl Ty {
...
+        let mut t: &Ty = self;
+
+        loop {
+            match t {
```
Comment (flodiebold) [inline crates/ra_hir_ty/src/lib.rs:687]: this could probably be a `while let`

File: crates/ra_hir_ty/src/_match.rs [hunk 4]
```diff
@@ -530,6 +532,16 @@ pub(crate) fn is_useful(
...
 ) -> MatchCheckResult<Usefulness> {
+    // Handle the special case of enums with no variants. In that case, no match
+    // arm is useful.
+    if let Ty::Apply(ApplicationTy { ctor: TypeCtor::Adt(AdtId::EnumId(enum_id)), .. }) =
+        cx.infer[cx.match_expr].deref()
+    {
+        if cx.db.enum_data(*enum_id).variants.is_empty() {
+            return Ok(Usefulness::NotUseful);
+        }
+    }
```
Comment (flodiebold) [inline crates/ra_hir_ty/src/_match.rs:543]: I'd expect this special case to become unnecessary when we properly determine constructors based on the type, but for now it's fine

File: crates/ra_hir_ty/src/lib.rs (hunk 2 above)
Comment (JoshMcguigan) [reply crates/ra_hir_ty/src/lib.rs]: Renamed to `strip_references` as suggested.

File: crates/ra_hir_ty/src/lib.rs (hunk 3 above)
Comment (JoshMcguigan) [reply crates/ra_hir_ty/src/lib.rs]: `while let` cleaned this up a bit, thanks for the suggestion.

File: crates/ra_hir_ty/src/_match.rs (hunk 4 above)
Comment (JoshMcguigan) [reply crates/ra_hir_ty/src/_match.rs:543]: Agreed :+1: 

The issue with an enum with no variants is our current method relies on the existence of at least one match arm in order to determine the constructor, which is what makes this a special case. If we always used the match expr to determine the construtor we wouldn't have that problem.
