### PR TITLE
Chalk upgrade

### LINKED ISSUE #2534: Unable to inference a result type of an indexing operation
Hi everyone, I was under impression that type inference involving arrays should work, but it is behaving weirdly:
```rust
fn foo(bar: [usize; 2]) -> usize {
    let baz = bar[1];
    baz
}

fn foo2(bar: [usize; 2]) -> usize {
    let baz = bar[1];
    return baz;
}

fn foo3(bar: [usize; 2]) {
    let baz = bar[1];
    println!("{}", baz);
}

fn main() {
    let foo4 = |bar: [usize; 2]| -> usize {
        let baz = bar[1];
        baz
    };

    let foo5 = |bar: [usize; 2]| -> usize {
        let baz = bar[1];
        return baz;
    };

    println!(
        "{} {} {} {}",
        foo([1, 2]),
        foo2([1, 2]),
        foo4([1, 2]),
        foo5([1, 2])
    );
    foo3([1, 2]);
}
```

The type inferred for `baz` is `usize` for `foo1` and `foo2` (good), `{unknown}` for `foo3` and `foo4` (I would expect that type inference is not too hard there) and `()` for `foo5` (plain wrong!).

Tested with the latest master (https://github.com/rust-analyzer/rust-analyzer/commit/4444192b05c107a40a5a05ea3c9091ad8f8cbbcc)

Edit: there are two separate issues: type in foo3 and foo4 is not inferred because it is an indexing operation and is inferred incorrectly in foo5 because of the `return` statement in the closure (#2547 )

### LINKED ISSUE #4281: fn item output type is not normalized
```rust
    let file: Option<PathBuf> = None.unwrap();
    let dst =
        file.as_ref().and_then(|it| it.file_name()).map(Path::new).unwrap_or(Path::new("main"));
```

image

The hint is not wrong, but this would be better (wrapping`Path::new` into lambda):

image

### LINKED ISSUE #4374: Incorrect type inference on (ref to array).to_owned()
To reproduce, mouse hover over the variables `x` and `y` in the following snippet:
```rust
fn main() {
    let x = (&[65u8]).to_owned();
    let y = b"A".to_owned();
}
```
The tooltip shows `x: &[u8; _]` and `y: Vec<u8>`.

But according to the compiler, they both have the type `[u8; 1]`:
```rust
fn main() {
    let x: &[u8; 1] = (&[65u8]).to_owned();
    let y: Vec<u8> = b"A".to_owned();
}
```
```
error[E0308]: mismatched types
 --> src\main.rs:2:23
  |
2 |     let x: &[u8; 1] = (&[65u8]).to_owned();
  |            --------   ^^^^^^^^^^^^^^^^^^^^
  |            |          |
  |            |          expected `&[u8; 1]`, found array `[u8; 1]`
  |            |          help: consider borrowing here: `&(&[65u8]).to_owned()`
  |            expected due to this

error[E0308]: mismatched types
 --> src\main.rs:3:22
  |
3 |     let y: Vec<u8> = b"A".to_owned();
  |            -------   ^^^^^^^^^^^^^^^
  |            |         |
  |            |         expected struct `std::vec::Vec`, found array `[u8; 1]`
  |            |         help: try using a conversion method: `b"A".to_owned().to_vec()`
  |            expected due to this
  |
  = note: expected struct `std::vec::Vec<u8>`
              found array `[u8; 1]`
```

--------------

### Version info

```
rust-analyzer version: 2020-05-04 (6a48a94)

> rustc --version --verbose
rustc 1.45.0-nightly (fa51f810e 2020-04-29)
binary: rustc
commit-hash: fa51f810e5b9254904b92660e7280b7d6a46f112
commit-date: 2020-04-29
host: x86_64-pc-windows-msvc
release: 1.45.0-nightly
LLVM version: 9.0
```

### LINKED ISSUE #5057: Function trait objects output is not normalized
~~Normally when I use the ? operator, type inference is able to correctly see through it and mark variables with the Ok type of the Result. This seems to fall apart when used on a ref to a function trait object:~~
image

I would expect the type of r to be u8.

### PR DESCRIPTION
**Pull request by flodiebold**
- upgrade Chalk
 - make use of Chalk's `Unsize` impls, remove ours
 - use Chalk's built-in array type
 - search efficiently for impls for an int/float variable
 - output Chalk tracing logs in hir_ty tests

Fixes #2534.
Fixes #5057.
Fixes #4374.
Fixes #4281.

### CODE REVIEW

**Comment by flodiebold** [comment]
Finally!

2020-07-11-194459_560x108_scrot

```
> $ rust-analyzer analysis-stats -q .
Database loaded 773.315643ms
Crates in this dir: 36
Total modules found: 490
Total declarations: 9622
Total functions: 7486
Item Collection: 17.199864213s, 0b allocated 0b resident
Total expressions: 191235
Expressions of unknown type: 1593 (0%)
Expressions of partially unknown type: 973 (0%)
Type mismatches: 459
Inference: 27.639799388s, 0b allocated 0b resident
Total: 44.839675093s, 0b allocated 0b resident

> $ ./target/release/rust-analyzer analysis-stats .
Database loaded 271.666766ms
Crates in this dir: 36
Total modules found: 490
Total declarations: 9622
Total functions: 7486
Item Collection: 16.365877914s, 0b allocated 0b resident
Total expressions: 191235
Expressions of unknown type: 1468 (0%)
Expressions of partially unknown type: 805 (0%)
Type mismatches: 464
Inference: 30.854763824s, 0b allocated 0b resident
Total: 47.220653907s, 0b allocated 0b resident
```

File: crates/ra_hir_ty/src/tests.rs [hunk 1]
```diff
@@ -37,6 +37,14 @@ use crate::{
 // against snapshots of the expected results using insta. Use cargo-insta to
 // update the snapshots.
 
+fn with_tracing_logs<T>(action: impl FnOnce() -> T) -> T {
+    use tracing_subscriber::{layer::SubscriberExt, EnvFilter, Registry};
+    use tracing_tree::HierarchicalLayer;
+    let filter = EnvFilter::from_env("CHALK_DEBUG");
+    let subscriber = Registry::default().with(filter).with(HierarchicalLayer::new(2));
```
Comment (davidbarsky) [inline crates/ra_hir_ty/src/tests.rs:44]: If you'd like, you can try rendering the output with ASCII lines: https://docs.rs/tracing-tree/0.1.2/tracing_tree/struct.HierarchicalLayer.html#method.with_indent_lines

File: crates/ra_hir_ty/Cargo.toml [hunk 2]
```diff
@@ -27,9 +27,14 @@ test_utils = { path = "../test_utils" }
...
+chalk-solve = { version = "0.17.0-dev.0", git = "https://github.com/rust-lang/chalk.git" }
+chalk-ir = { version = "0.17.0-dev.0", git = "https://github.com/rust-lang/chalk.git" }
+chalk-recursive = { version = "0.17.0-dev.0", git = "https://github.com/rust-lang/chalk.git" }
 
 [dev-dependencies]
 insta = "0.16.0"
 expect = { path = "../expect" }
+
+tracing = "0.1"
+tracing-subscriber = { version = "0.2" }
```
Comment (davidbarsky) [inline crates/ra_hir_ty/Cargo.toml:39]: You might be able to disable _all_ default features and only enable the EnvFilter + the Registry to cut down on compile times, as you don't really need the formatters.

File: crates/ra_hir_ty/src/tests/traits.rs [hunk 3]
```diff
@@ -1991,6 +1991,29 @@ fn test() {
     );
 }
 
+#[test]
+fn fn_item_fn_trait() {
+    check_types(
+        r#"
+//- /main.rs
```
Comment (matklad) [inline crates/ra_hir_ty/src/tests/traits.rs:1998]: For sing-file fixtures, you now can omit the name of the file.

In general, we’ve got rid of single-file/multi-file fixture distinction, it’s now just fixture.

File: crates/ra_hir_ty/Cargo.toml (hunk 2 above)
Comment (matklad) [reply crates/ra_hir_ty/Cargo.toml:39]: I wonder if we can import only a single trait, like how we need only env_logger for logging. The problem with many crates is that you need to update several major versions sometimes.

File: crates/ra_hir_ty/src/tests.rs [hunk 4]
```diff
@@ -37,6 +37,14 @@ use crate::{
 // against snapshots of the expected results using insta. Use cargo-insta to
 // update the snapshots.
 
+fn with_tracing_logs<T>(action: impl FnOnce() -> T) -> T {
```
Comment (matklad) [inline crates/ra_hir_ty/src/tests.rs:40]: An alternative would be guard based api: let _tracing = with_tracing_logs. It would be a tad more rustic, and will also avoid impl vs dyn question.

File: crates/ra_hir_ty/Cargo.toml (hunk 2 above)
Comment (davidbarsky) [reply crates/ra_hir_ty/Cargo.toml:39]: I've been thinking about that—one thing that I can do is re-export the important stuff from `tracing-subscriber` via `tracing-tree`, which could reduce the amount of imports to just tracing and tracing-tree.

**Comment by davidbarsky** [comment]
I've released tracing-tree 0.1.3 that enables writing to arbitrary destinations, including `stderr`. Here are the release notes: https://github.com/davidbarsky/tracing-tree/releases/tag/v0.1.3)

File: crates/ra_hir_ty/src/tests.rs (hunk 1 above)
Comment (flodiebold) [reply crates/ra_hir_ty/src/tests.rs:44]: I tried it, but I like it a bit better without the lines...

File: crates/ra_hir_ty/Cargo.toml (hunk 2 above)
Comment (flodiebold) [reply crates/ra_hir_ty/Cargo.toml]: I set the features, but I'm not sure it made any difference :thinking:

**Comment by flodiebold** [comment]
The Chalk publish failed to publish chalk-recursive, so I think we'll need to merge this with the git dependency if we don't want to wait a week...

**Comment by flodiebold** [comment]
Actually apparently we might [get a release](https://github.com/rust-lang/chalk/pull/572#issuecomment-657250344)...

File: crates/ra_hir_ty/src/tests.rs (hunk 4 above)
Comment (flodiebold) [reply crates/ra_hir_ty/src/tests.rs]: Turns out tracing does have such an API!
