### PR TITLE
Fix TokenStream::from_str for input consisting of a single group with delimiter

### LINKED ISSUE #7810: proc-macro: Couldn't parse default expression `Trait`
## MWE

`Cargo.toml`:

```toml
[dependencies]
derive_builder = "0.9.0"
```

`main.rs`:

```rust
use derive_builder::Builder;
fn main() {}

#[derive(Debug, Default, Builder)]
#[builder(default)]
struct Test {}

```

`cargo check` reports that everything is ok:

```shell
$ cargo check 2>/dev/null && echo $?
0
```

`rust-analyzer` (VSCode) with `rust-analyzer.cargo.loadOutDirsFromCheck` and `rust-analyzer.procMacro.enable` options enabled reports:
```
proc macro returned error: proc-macro panicked: Couldn't parse default expression `Trait`: "expected curly braces"
```
and

```shell
$ rust-analyzer diagnostics --load-output-dirs --with-proc-macro ./
...
Diagnostic { message: "proc macro process is closed", range: 43..112, severity: Error, fix: None, unused: false, code: Some(DiagnosticCode("macro-error")) }

diagnostic scan complete

[ERROR rust_analyzer] Unexpected error: diagnostic error detected
diagnostic error detected

```

## Versions

- Rust version: `1.50.0 (cb75ad5db 2021-02-10)` (stable)
- rust-analyzer version: 14de9e5

### LINKED ISSUE #7875: Panic in proc macro expand, rust 1.5.0, analyzer 0.2.505
Using Fake crate to fake data

Example of problematic code:

``` rust
#[derive(Serialize, Deserialize, Dummy)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    #[dummy(faker = "UuidFaker")]
    pub id: Uuid,
    #[dummy(faker = "Word()")]
    pub name: String,
    #[dummy(faker = "LabelFaker")]
    pub label: String,
    pub ingestion_source: IngestionSource,
    pub risk_threshold_actions: Vec<RiskThresholdAction>,
    #[dummy(faker = "(Faker, 3..5)")]  // <<<< Problematic macro
    pub dependencies: Vec<Package>,
    pub risk_scores: RiskScores,
    pub total_risk_score_dynamics: ScoreDynamics,
    pub issues: IssuesList,
    pub issue_statuses: Vec<IssueStatusListItem>,
}
```

`Package` is another struct being included in this one.

code compiles/checks fine, I just get a warning about proc macro expansion failing in vscode and squiggles everywhere.

Log:
```
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/danieljoyce/.cargo/registry/src/github.com-1ecc6299db9ec823/uuid-0.8.2/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: cfg::dnf::Conjunction::new
   3: cfg::dnf::Conjunction::new
   4: cfg::dnf::Conjunction::new
   5: cfg::dnf::DnfExpr::new
   6: <hir_def::diagnostics::InactiveCode as hir_expand::diagnostics::Diagnostic>::message
   7: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   8: hir_expand::diagnostics::DiagnosticSink::_push
   9: hir_def::nameres::diagnostics::DefDiagnostic::add_to
  10: hir_def::nameres::DefMap::add_diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: ide::Analysis::diagnostics
  14: rust_analyzer::handlers::handle_code_action
  15: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/danieljoyce/.cargo/registry/src/github.com-1ecc6299db9ec823/uuid-0.8.2/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 260,
            character: 11,
        },
        end: Position {
            line: 260,
            character: 11,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: cfg::dnf::Conjunction::new
   3: cfg::dnf::Conjunction::new
   4: cfg::dnf::Conjunction::new
   5: cfg::dnf::DnfExpr::new
   6: <hir_def::diagnostics::InactiveCode as hir_expand::diagnostics::Diagnostic>::message
   7: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   8: hir_expand::diagnostics::DiagnosticSink::_push
   9: hir_def::nameres::diagnostics::DefDiagnostic::add_to
  10: hir_def::nameres::DefMap::add_diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: ide::Analysis::diagnostics
  14: rust_analyzer::handlers::handle_code_action
  15: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: cfg::dnf::Conjunction::new
   3: cfg::dnf::Conjunction::new
   4: cfg::dnf::Conjunction::new
   5: cfg::dnf::DnfExpr::new
   6: <hir_def::diagnostics::InactiveCode as hir_expand::diagnostics::Diagnostic>::message
   7: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   8: hir_expand::diagnostics::DiagnosticSink::_push
   9: hir_def::nameres::diagnostics::DefDiagnostic::add_to
  10: hir_def::nameres::DefMap::add_diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: ide::Analysis::diagnostics
  14: rust_analyzer::handlers::publish_diagnostics
  15: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  16: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  17: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by kevinmehall**
TokenStream holds a `tt::Subtree` but assumes its `delimiter` is always `None`. In particular, the iterator implementation iterates over the inner `token_trees` and ignores the `delimiter`.

However, `TokenStream::from_str` violated this assumption when the input consists of a single group by producing a Subtree with an outer delimiter, which was ignored as seen by a procedural macro.

`tt::Subtree` is just `pub delimiter: Option<Delimiter>, pub token_trees: Vec<TokenTree>`, so a Subtree that is statically guaranteed not to have a delimiter is just `Vec<TokenTree>`.

Fixes #7810
Fixes #7875

### CODE REVIEW

File: crates/proc_macro_srv/src/proc_macro/bridge/client.rs [hunk 1]
```diff
@@ -238,7 +238,7 @@ macro_rules! define_client_side {
         $(impl $name {
             #[allow(unused)]
             $(pub(crate) fn $method($($arg: $arg_ty),*) $(-> $ret_ty)* {
-                panic!("hello");
+                panic!("crates should be linked against the sysroot version of proc_macro, not this one from rust-analyzer");
```
Comment (edwin0cheng) [inline crates/proc_macro_srv/src/proc_macro/bridge/client.rs:241]: :+1:

File: crates/proc_macro_srv/src/rustc_server.rs [hunk 2]
```diff
@@ -185,38 +193,38 @@ pub mod token_stream {
...
     impl ToString for TokenStream {
         fn to_string(&self) -> String {
-            let tt = self.subtree.clone().into();
-            to_text(&tt)
+            tokentrees_to_text(&self.token_trees[..])
         }
     }
 
-    fn to_text(tkn: &tt::TokenTree) -> String {
+    fn tokentrees_to_text(tkns: &[tt::TokenTree]) -> String {
```
Comment (edwin0cheng) [inline crates/proc_macro_srv/src/rustc_server.rs:206]: Nit: we usuallyy put inner function at the end of a function.

**Review by edwin0cheng — APPROVED** [review]
LGTM, except a little nit, 

bors d+

File: crates/proc_macro_srv/src/rustc_server.rs (hunk 2 above)
Comment (kevinmehall) [reply crates/proc_macro_srv/src/rustc_server.rs]: Is https://github.com/rust-analyzer/rust-analyzer/pull/7892/commits/aea974939064b0f7b83de371a93ee4190c80e544 what you meant by this?

**Comment by edwin0cheng** [comment]
Thanks ! 

bors r+
