### PR TITLE
fix: splitting path of a glob import wrongly adds `self`

### LINKED ISSUE #11703: Wildcard module import glob is replaced with `use super::{self::*}`
If I have a `use super::*;` present, then adding a type that comes from say `super::another_module:AnotherType` results in
```rust
use super::{self::*, another_module::AnotherType};
```
which is invalid. 

I find it hard to name this issue. Please suggest a title.

### PR DESCRIPTION
**Pull request by iDawer**
Close  #11703 

`ast::UseTree::split_prefix` handles globs now.
Removed an extra branch for globs in `ide_db::imports::merge_imports::recursive_merge` (superseeded by split_prefix).

### CODE REVIEW

File: crates/syntax/src/ast/edit_in_place.rs [hunk 1]
```diff
@@ -302,16 +302,33 @@ impl ast::UseTree {
...
+                let self_suffix =
+                    make::path_unqualified(make::path_segment_self()).clone_for_update();
+                ted::replace(path.syntax(), self_suffix.syntax());
+            }
         } else if split_path_prefix(prefix).is_none() {
             return;
         }
-
+        // At this point, prefix path is detached; _self_ use tree has suffix path.
+        // Next, transoform 'suffix' use tree into 'prefix::{suffix}'
```
Comment (lnicola) [inline crates/syntax/src/ast/edit_in_place.rs:331]: Nit:

```suggestion
        // Next, transform 'suffix' use tree into 'prefix::{suffix}'
```

**Review by Veykril — COMMENTED** [review]
bors r+
