### PR TITLE
Fix panic during the expansion of `column!`

### LINKED ISSUE #2379: checking miri: thread 'main' panicked at 'byte index 183 is out of bounds
Running `ra_cli  analysis-stats .` in the miri repo (aeb218afa24b923f4188ae9f8cef1f9367ed0f59) crashes ra:
````
Database loaded, 111 roots, 290.288586ms
Crates in this dir: 9
Total modules found: 43
Total declarations: 1016
Total functions: 160
Item Collection: 6.586786772s, 0b allocated 0b resident
██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 7/160
processing: main
thread 'main' panicked at 'byte index 183 is out of bounds of `#[inline(never)]
pub fn main() {
    assert_eq!(fib(10), 55);
}

fn fib(n: usize) -> usize {
    if n <= 2 { 1 } else { fib(n - 1) + fib(n - 2) }
}
````
ra @ ea3124c12a52f28163a6375b6a5e3c79fc14312d

### PR DESCRIPTION
**Pull request by marcogroppo**
Fixes #2379. Well, this isn't the "proper" fix but it doesn't hurt, IMHO.

The problem is that `to_col_number`, called by `column_expand`, receives a position number that isn't included in the text range of the file. My (very limited) understanding is that the text is the one of the original file, while `pos` is relative to something else, probably the text of the macro. Notice that in this case the `column!` expansion seems to be triggered by `assert_eq!`, so we're in the middle of another expansion. This PR simply avoids the panic by checking the length of the text.

r? @edwin0cheng

### CODE REVIEW

**Comment by edwin0cheng** [comment]
Yes, I think your explanation is correct. Maybe we could use the new `Expansion` api the remap the pos to original file but it is a little tricky since `to_col_number` is live behind the `salsa DB` firewall. But I think at this moment your bound check is okay..

But would you mind to fix `to_line_number` too? It has the same problem.

File: crates/ra_hir_expand/src/builtin_macro.rs [hunk 1]
```diff
@@ -114,20 +114,25 @@ fn stringify_expand(
...
 
-fn to_col_number(db: &dyn AstDatabase, file: HirFileId, pos: TextUnit) -> usize {
+fn to_col_number(db: &dyn AstDatabase, file: HirFileId, pos: TextUnit) -> Option<usize> {
     // FIXME: Use expansion info
     let file_id = file.original_file(db);
     let text = db.file_text(file_id);
-    let mut col_num = 1;
 
-    for c in text[..pos.to_usize()].chars().rev() {
+    let pos = pos.to_usize();
```
Comment (edwin0cheng) [inline crates/ra_hir_expand/src/builtin_macro.rs]: Would you mind to add a `FIXME` which indicate this code is just a hot fix?

**Comment by marcogroppo** [comment]
> But would you mind to fix `to_line_number` too? It has the same problem.

I didn't fix it because it uses an iterator, so it shouldn't panic. It could have returned the wrong line number, tough... I've added the same check

**Comment by flodiebold** [comment]
I wonder, why are we even trying to expand this to the correct value? It doesn't make a difference, does it? Couldn't we just always put `0` there?

**Comment by marcogroppo** [comment]
@flodiebold mmm ok, so you think it would be better to just return 0 both for `column!` and `line!`?

**Comment by lnicola** [comment]
It's visible when using the new "expand macro" command, I guess.

**Comment by marcogroppo** [comment]
> It's visible when using the new "expand macro" command, I guess.

No, it isn't. I don't know why, but if you try to expand `assert_eq!` using the RA command you see `$crate::column!()` and `$crate::line!()`.
I've modified the PR so that both `line!` and `column!` just return `0` in case of errors and I've added a `FIXME`.

**Comment by kjeremy** [comment]
> 
> 
> It's still visible when using the new "expand macro" command, right?

If expanding `column!` it is. for `assert_eq!` there's some more work that needs to be done unrelated to `line!` and `column!`

**Comment by edwin0cheng** [comment]
> and for line!, isn't it even harmful towards incrementality?)

@flodiebold If I understand correctly,  it should be no difference. Even in normal macro call, If the line number changed, `MacroCallId` will be changed too (i.e `MacroCallId contains `ast::MacroCall` which related to file position).

**Comment by edwin0cheng** [comment]
> using the RA command you see $crate::column!() and $crate::line!()

Maybe we didn't handle `Hygiene` properly in `SourceAnalyser` yet ? I will investigate that later. :)

and LGTM now, thanks.
bors r+

**Comment by flodiebold** [comment]
> @flodiebold If I understand correctly, it should be no difference. Even in normal macro call, If the line number changed, `MacroCallId` will be changed too (i.e `MacroCallId contains `ast::MacroCall` which related to file position).

It'd still make a difference for later steps like type inference though :slightly_smiling_face:

**Comment by edwin0cheng** [comment]
Oh... you are right But I can imagine some "good" c++ programmer to use the following trick to generate a compile time random number:

```rust
// pre-generate a list of  data/hash[*].txt  of random number
macro_rules compile_time_random {
  () => ( include_str!(concat!("data/hash", line!(), ".txt"))  }
}
```
