### PR TITLE
"Insert explicit type " assist fix #2869, fix typo

### LINKED ISSUE #2869: "Insert explicit type " assist should trigger only on the binding
See this example:

image

Here, the intention will add type to `let ty`. This is clearly not desirable, as `ty` might be off screen. I think we should restrict the intention to only trigger if the cursor is on the `let foo =`, that is, before `=`.

The code for assist is here: https://github.com/rust-analyzer/rust-analyzer/blob/07dca1123dfaec527c6ba3164125309f5c4cc3db/crates/ra_assists/src/assists/add_explicit_type.rs

cc @TomasKralCZ

### PR DESCRIPTION
**Pull request by TomasKralCZ**
So this was quite straightforward. I basically looked at how the other assists work and tried doing something simillar. I also fixed a typo in the other assist.

### CODE REVIEW

File: crates/ra_assists/src/assists/add_explicit_type.rs [hunk 1]
```diff
@@ -34,6 +35,14 @@ pub(crate) fn add_explicit_type(ctx: AssistCtx<impl HirDatabase>) -> Option<Assi
     // The binding must have a name
     let name = pat.name()?;
     let name_range = name.syntax().text_range();
+    // Assist should only be applicable if cursor is between 'let' and '='
+    let stmt_range = stmt.syntax().text_range();
+    let eq_range = stmt.syntax().descendants_with_tokens().find(|t| t.kind() == EQ)?.text_range();
```
Comment (matklad) [inline crates/ra_assists/src/assists/add_explicit_type.rs]: Let’s add an eq_token method to ast::LetStmt, so that it can be used elsewhere. There’s extensions.rs module for that

Comment (matklad) [reply crates/ra_assists/src/assists/add_explicit_type.rs]: Other than this, looks good to me!

File: crates/ra_syntax/src/ast/extensions.rs [hunk 2]
```diff
@@ -234,6 +234,13 @@ impl ast::LetStmt {
             Some(node) => node.kind() == T![;],
         }
     }
+
+    pub fn eq_token(&self) -> Option<SyntaxToken> {
+        self.syntax()
+            .descendants_with_tokens()
```
Comment (matklad) [inline crates/ra_syntax/src/ast/extensions.rs]: Oh, we should also use children instead of descendants here: descendants is recursive, and so can be much slower. Everything is ok!

bors d+

Comment (TomasKralCZ) [reply crates/ra_syntax/src/ast/extensions.rs]: Oh, I see. Is there any documentation for Rowan ?

Comment (matklad) [reply crates/ra_syntax/src/ast/extensions.rs]: Nope :-( 

Though, the API is stable-ish now, so writing docs should be a good investment. There's api_walkthoruh test which might be helpful.
