### PR TITLE
Fix recursive macro statements expansion

### LINKED ISSUE #8171: "Failed to parse macro invocation" when using crate "proconio"
proconio is easy IO library for competitive programming.

Error occur when using `input!` macro.

I can compile and run it, but I get "Failed to parse macro invocation" in rust-analyzer.

This error was confirmed in both vim and vscode.

rust-analyzer is nightly version(0.3.528).

image

## Complete repro

cargo.toml:

```toml
[package]
name = "repro"
version = "0.1.0"
authors = ["hogehoge"]
edition = "2018"
[dependencies]
proconio = "0.4.2"
```

main.rs

```rust
use proconio::*;
fn main() {
    input! {
        _n: isize,
    }
}
```

Thank you.

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR attempts to properly handle macro statement expansion by implementing the following:

1.  Merge macro expanded statements to parent scope statements.
2.  Add a new hir `Expr::MacroStmts` for handle tail expression infer.

PS : The scope of macro expanded statements are so strange that it took more time than I thought to understand and implement it :(

Fixes  #8171

### CODE REVIEW

File: crates/hir_def/src/item_tree.rs [hunk 1]
```diff
@@ -110,11 +110,6 @@ impl ItemTree {
                     // still need to collect inner items.
                     ctx.lower_inner_items(e.syntax())
                 },
-                ast::ExprStmt(stmt) => {
-                    // Macros can expand to stmt. We return an empty item tree in this case, but
-                    // still need to collect inner items.
-                    ctx.lower_inner_items(stmt.syntax())
-                },
                 ast::Item(item) => {
                     // Macros can expand to stmt and other item, and we add it as top level item
```
Comment (kw-fn) [inline crates/hir_def/src/item_tree.rs:114]: unclear comment

File: crates/hir_expand/src/db.rs [hunk 2]
```diff
@@ -395,13 +426,13 @@ fn to_fragment_kind(db: &dyn AstDatabase, id: MacroCallId) -> FragmentKind {
             // If it is root, which means the parent HirFile
             // MacroKindFile must be non-items
             // return expr now.
```
Comment (kw-fn) [inline crates/hir_expand/src/db.rs:428]: unclear comment

File: crates/hir_expand/src/db.rs [hunk 3]
```diff
@@ -395,13 +426,13 @@ fn to_fragment_kind(db: &dyn AstDatabase, id: MacroCallId) -> FragmentKind {
...
         }
     };
 
     match parent.kind() {
         MACRO_ITEMS | SOURCE_FILE => FragmentKind::Items,
-        MACRO_STMTS => FragmentKind::Statement,
+        MACRO_STMTS => FragmentKind::Statements,
         ITEM_LIST => FragmentKind::Items,
         LET_STMT => {
             // FIXME: Handle Pattern
```
Comment (kw-fn) [inline crates/hir_expand/src/db.rs:438]:
```suggestion
            // FIXME: Handle FragmentKind::Pattern
```
or is something else being implied?

**Comment by lnicola** [comment]
changelog fix
