### PR TITLE
fix: Inline parameters in `inline_call` if possible

### LINKED ISSUE #9491: "Inline call" in impl produces broken code
This:

```rust
struct S;

impl S {
    fn answer(&self) -> i32 {
        42
    }

    fn f(&self) {
        let ans = self.answer();
    }
}
```

turns into:

```rust
impl S {
    fn answer(&self) -> i32 {
        42
    }

    fn f(&self) {
        let ans = {
            let ref this = this;
            42
        };
    }
}
```

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #9491

### CODE REVIEW

**Comment by Veykril** [comment]
Managed to make the whitespace work out in most situations(?), not much one can do about until we have our own formatter.

bors r+

**Comment by Veykril** [comment]
bors retry

**Comment by matklad** [comment]
Yeah, I remeber starting to look into whitespace here yesterday, but I don't remember where this ended.

I recall we have a similar logic for `USE` there already, and it seems that we want to maybe split out:

* figure whitespace within a single line
* figure linebreaks/indentation

**Comment by Veykril** [comment]
Ye I was trying to reuse that, but it didn't work, which was partially because of the insertion order being different here I think? This whitespace magic is really neat but something my head really doesnt like to think about it seems 😅

**Comment by matklad** [comment]
>but I don't remember where this ended

Ah, seems that I just refactored the existing code: https://github.com/rust-analyzer/rust-analyzer/pull/9490 :)

File: crates/ide_assists/src/handlers/inline_call.rs [hunk 1]
```diff
@@ -95,41 +102,94 @@ pub(crate) fn inline_(
...
+                    })
+                    .for_each(|it| {
+                        ted::replace(it, &this());
+                    })
+            }
+
+            // Inline parameter expressions or generate `let` statements depending on whether inlining works or not.
+            for ((pat, _), usages, expr) in izip!(params, param_use_nodes, arg_list).rev() {
+                match &*usages {
+                    // inline single use parameters
```
Comment (flodiebold) [inline crates/ide_assists/src/handlers/inline_call.rs:164]: this might be a problem if the parameter expression has a side effect?

Comment (Veykril) [reply crates/ide_assists/src/handlers/inline_call.rs:164]: oh dammit right, the evaluation could get skipped now due to early returns. I didn't think of that. Guess this has to be restricted to simple name_ref expressions as well. Though I guess there is also the problem with `drop` impls then?

Looks like we just cannot inline parameters at all then... ?

Comment (flodiebold) [reply crates/ide_assists/src/handlers/inline_call.rs:164]: I think inlining simple namerefs should be fine, I don't see how that could lead to problems even with drop? We could even extend it to things like `&name_ref`, probably. (Maybe that could lead to borrow checking problems? Not sure) We could also inline single-use parameters if their expression is the first in the body, but that might be too much of an edge case.

Comment (matklad) [reply crates/ide_assists/src/handlers/inline_call.rs:164]: I don't think we should try too hard to be semantics-preserving at this stage. 

Long term, it'd be cool to show some kind of UI indicator for cases where we are not sure if semantics is the same.

Comment (Veykril) [reply crates/ide_assists/src/handlers/inline_call.rs:164]: > I don't see how that could lead to problems even with drop? 

It *could* affect drop order I believe.

Though I agree, I don't think people will use this assist on functions where the args they supply will have side effects too often? I feel like you'd usually notice that as you normally dont wanna inline really big functions where you wouldn't notice the inlining happening.

Comment (flodiebold) [reply crates/ide_assists/src/handlers/inline_call.rs:164]: > I don't think we should try too hard to be semantics-preserving at this stage.
> 
> Long term, it'd be cool to show some kind of UI indicator for cases where we are not sure if semantics is the same.

I agree that not everything needs to be semantics-preserving, but I think for inlining arguments into the method body we should err on the side of not inlining, because it's easier to use the "inline variable" assist afterwards than to extract and move the variable to the right place.

Comment (Veykril) [reply crates/ide_assists/src/handlers/inline_call.rs:164]: Mm, being able to use `inline variable` is a strong point in favor of not eagerly inlining everything.
