### PR TITLE
Fix parsing of "postfix" range expressions.

### LINKED ISSUE #2242: Bugs parsing casts in range expressions
This code causes red underlining in VS Code, even though rustc accepts it:

```rust
&buf[cur.position() as usize..]
```

(`Syntax Error: expected expression`, underlining only from the closing bracket.)

### PR DESCRIPTION
**Pull request by goffrie**
Right now they are handled in `postfix_dot_expr`, but that doesn't allow it to
correctly handle precedence. Integrate it more tightly with the Pratt parser
instead.

Also includes a drive-by fix for parsing `match .. {}`.

Fixes #2242.

### CODE REVIEW

File: crates/ra_parser/src/grammar/expressions.rs [hunk 1]
```diff
@@ -290,6 +290,25 @@ fn expr_bp(p: &mut Parser, r: Restrictions, bp: u8) -> (Option<CompletedMarker>,
...
+            // fn foo() {
+            //     let x = 1..;
+            //     match 1.. { _ => () };
+            //     match a.b()..S { _ => () };
+            // }
+            let has_trailing_expression =
+                p.at_ts(EXPR_FIRST) && !(r.forbid_structs && p.at(T!['{']));
+            if !has_trailing_expression {
+                if op == T![..=] {
+                    p.error("expected expression to end inclusive range");
```
Comment (goffrie) [inline crates/ra_parser/src/grammar/expressions.rs]: another drive-by fix, `a..=` is illegal

**Comment by goffrie** [comment]
This is a bit hax at this point. I think it sort of works because all the remaining `postfix_expr` operators all bind as tightly as possible, which wasn't true of `..` (e.g. we were parsing `a + b ..` as `a + (b..)` instead of `(a + b)..`). But there's probably a nicer factoring of this.

File: crates/ra_parser/src/grammar/expressions.rs (hunk 1 above)
Comment (matklad) [reply crates/ra_parser/src/grammar/expressions.rs]: It is semantically illegal, but I think it's better to parse it just like `a..`, and instead handle the error during validation, similarly to how we handle [visibility on trait items](https://github.com/rust-analyzer/rust-analyzer/blob/31d01efb069065449e53cfd7d0935c4b9fecf1e3/crates/ra_syntax/src/validation.rs#L211-L229)

File: crates/ra_syntax/src/validation.rs [hunk 2]
```diff
@@ -227,3 +228,16 @@ fn validate_visibility(vis: ast::Visibility, errors: &mut Vec<SyntaxError>) {
             .push(SyntaxError::new(SyntaxErrorKind::VisibilityNotAllowed, vis.syntax.text_range()))
     }
 }
+
+fn validate_range_expr(expr: ast::RangeExpr, errors: &mut Vec<SyntaxError>) {
+    let last_child = match expr.syntax().last_child_or_token() {
```
Comment (goffrie) [inline crates/ra_syntax/src/validation.rs]: I found it surprisingly hard to work with the syntax tree :( This happened to turn out okayish since I only care if the operator is at the end, but I don't know how I would in general find the range operator in a `RangeExpr`.

Comment (matklad) [reply crates/ra_syntax/src/validation.rs]: That's because we don't have typed accesor yet for the range token. This should help

```diff
diff --git a/crates/ra_syntax/src/ast/expr_extensions.rs b/crates/ra_syntax/src/ast/expr_extensions.rs
index 25dbd0bed..b33d99b5a 100644
--- a/crates/ra_syntax/src/ast/expr_extensions.rs
+++ b/crates/ra_syntax/src/ast/expr_extensions.rs
@@ -189,6 +189,34 @@ impl ast::BinExpr {
     }
 }
 
+enum RangeOp {
+    /// `..`
+    Exclusive,
+    /// `..=`
+    Inclusive,
+}
+
+impl ast::RangeExpr {
+    fn op_details(&self) -> Option<(SyntaxToken, RangeOp)> {
+        self.syntax().children_with_tokens().filter_map(|it| it.into_token()).find_map(|c| {
+            let bin_op = match c.kind() {
+                T![..] => RangeOp::Exclusive,
+                T![..=] => RangeOp::Inclusive,
+                _ => return None,
+            };
+            Some((c, bin_op))
+        })
+    }
+
+    pub fn op_kind(&self) -> Option<RangeOp> {
+        self.op_details().map(|t| t.1)
+    }
+
+    pub fn op_token(&self) -> Option<SyntaxToken> {
+        self.op_details().map(|t| t.0)
+    }
+}
+
 impl ast::IndexExpr {
     pub fn base(&self) -> Option<ast::Expr> {
         children(self).nth(0)
```

Comment (matklad) [reply crates/ra_syntax/src/validation.rs]: Oh, and 

```rust
    pub fn lhs(&self) -> Option<ast::Expr> {
        children(self).nth(0)
    }

    pub fn rhs(&self) -> Option<ast::Expr> {
        children(self).nth(1)
    }

    pub fn sub_exprs(&self) -> (Option<ast::Expr>, Option<ast::Expr>) {
        let mut children = children(self);
        let first = children.next();
        let second = children.next();
        (first, second)
    }
```

would be useful as well.

Comment (matklad) [reply crates/ra_syntax/src/validation.rs]: Wait, no, there should be some additional logic to determine if a child is before or after the range token.

Basically, the AST API becomes bearable when all required typed accessors are added. We can't really use a more traditional enum approach, because everything is optional, and everything can contain whitespace.

Comment (matklad) [reply crates/ra_syntax/src/validation.rs]: If you like, I can implement validation myself :)

Comment (goffrie) [reply crates/ra_syntax/src/validation.rs]: I tried to implement something here but it's not really great. Feel free to change it if you want :p

**Comment by matklad** [comment]
bors r+

Thanks!

One day, we will generate type accessors from the grammar specification...
