### PR TITLE
Normalize line endings when formatting

### LINKED ISSUE #7166: Native newline style rustfmt configuration breaks formatting on Windows
Steps to reproduce:

1. Use `cargo new` to create a new project on Windows.
2. Create a `.rustfmt.toml` file with `newline_style = "Native"` inside.
3. Open project directory with Visual Studio Code with Rust Analyzer extension installed.
4. Format `src/main.rs` with Rust Analyzer.
5. Observe the document. There are extra newlines inserted between each line, like this:

   ```rust
   fn main() {

       println!("Hello, world!");

   }
   ```

   Notice the empty lines between each text line.

### PR DESCRIPTION
**Pull request by Jesse-Bakker**
Fixes #7166

### CODE REVIEW

File: crates/rust-analyzer/src/handlers.rs [hunk 1]
```diff
@@ -909,14 +910,25 @@ pub(crate) fn handle_formatting(
         }
     }
 
-    if *file == captured_stdout {
+    let (new_text, new_line_endings) = LineEndings::normalize(captured_stdout);
+
+    if file_line_endings != new_line_endings {
+        // If line endings are different,  send the entire file.
```
Comment (bjorn3) [inline crates/rust-analyzer/src/handlers.rs:916]:
```suggestion
        // If line endings are different, send the entire file.
```
