### PR TITLE
Favor types for record type struct in name resolution

### LINKED ISSUE #4235: Wrong infer when static item name conflicts
```rust
struct FOO {}
static FOO:FOO = FOO {};

impl FOO {
    fn foo(&self) {}
}

fn main() {
    let a = &FOO;    // infered to a : &FOO() -> FOO, but it should be &FOO
    a.foo();
}
```

This setup is used in `lazy_static` macro

[edit]

But this setup works: 
```rust
static FOO:FOO = FOO {};
struct FOO {}

impl FOO {
    fn foo(&self) {}
}

fn main() {
    let a = &FOO;    // a :&FOO
    a.foo();
}
```

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fixed #4235

### CODE REVIEW

File: crates/ra_hir_def/src/body/lower.rs [hunk 1]
```diff
@@ -575,9 +575,16 @@ impl ExprCollector<'_> {
             self.body.item_scope.define_def(def);
             if let Some(name) = name {
                 let vis = crate::visibility::Visibility::Public; // FIXME determine correctly
-                self.body
-                    .item_scope
-                    .push_res(name.as_name(), crate::per_ns::PerNs::from_def(def, vis));
+                let favor_types = match def {
```
Comment (flodiebold) [inline crates/ra_hir_def/src/body/lower.rs:578]: I think it'd be clearer to invert this and call it `has_constructor`. maybe even move this logic into `from_def`? It's not so much "favoring" types as whether the def exists in the value namespace at all.

File: crates/ra_hir_def/src/item_scope.rs [hunk 2]
```diff
@@ -151,13 +151,20 @@ impl ItemScope {
...
 
 impl PerNs {
-    pub(crate) fn from_def(def: ModuleDefId, v: Visibility) -> PerNs {
+    pub(crate) fn from_def(def: ModuleDefId, v: Visibility, favor_types: bool) -> PerNs {
         match def {
             ModuleDefId::ModuleId(_) => PerNs::types(def, v),
             ModuleDefId::FunctionId(_) => PerNs::values(def, v),
             ModuleDefId::AdtId(adt) => match adt {
-                AdtId::StructId(_) | AdtId::UnionId(_) => PerNs::both(def, def, v),
+                AdtId::UnionId(_) => PerNs::both(def, def, v),
```
Comment (flodiebold) [inline crates/ra_hir_def/src/item_scope.rs:159]: do unions actually exist as values? aren't they always like record structs?

Comment (edwin0cheng) [reply crates/ra_hir_def/src/item_scope.rs:159]: You are right !, https://doc.rust-lang.org/reference/items/unions.html

File: crates/ra_hir_def/src/body/lower.rs (hunk 1 above)
Comment (edwin0cheng) [reply crates/ra_hir_def/src/body/lower.rs:578]: Originally this logic is inside `from_def`, however, in collecting phase, I can't do the same as it will break the `no db change rules`.

+1 for `has_constructor`

Comment (edwin0cheng) [reply crates/ra_hir_def/src/body/lower.rs]: Fixed for `has_constructor`

File: crates/ra_hir_def/src/item_scope.rs (hunk 2 above)
Comment (edwin0cheng) [reply crates/ra_hir_def/src/item_scope.rs]: Fixed.

**Comment by flodiebold** [comment]
It's not very elegant, but I'd be ok with merging it -- @matklad what do you think?

File: crates/ra_hir_def/src/item_scope.rs [hunk 3]
```diff
@@ -151,13 +151,20 @@ impl ItemScope {
...
+    pub(crate) fn from_def(def: ModuleDefId, v: Visibility, has_constructor: bool) -> PerNs {
         match def {
             ModuleDefId::ModuleId(_) => PerNs::types(def, v),
             ModuleDefId::FunctionId(_) => PerNs::values(def, v),
             ModuleDefId::AdtId(adt) => match adt {
-                AdtId::StructId(_) | AdtId::UnionId(_) => PerNs::both(def, def, v),
+                AdtId::UnionId(_) => PerNs::types(def, v),
                 AdtId::EnumId(_) => PerNs::types(def, v),
+                AdtId::StructId(_) => {
+                    if !has_constructor {
```
Comment (matklad) [inline crates/ra_hir_def/src/item_scope.rs:162]: <kbd>ctrl+.</kbd>, **Invert If**

I wish one day I can just see a lightbulb on github :D

File: crates/ra_hir_def/src/item_scope.rs [hunk 4]
```diff
@@ -151,13 +151,20 @@ impl ItemScope {
 }
 
 impl PerNs {
-    pub(crate) fn from_def(def: ModuleDefId, v: Visibility) -> PerNs {
+    pub(crate) fn from_def(def: ModuleDefId, v: Visibility, has_constructor: bool) -> PerNs {
```
Comment (matklad) [inline crates/ra_hir_def/src/item_scope.rs:154]: That's a somewhat iffy API, because we have a boolean parameter *and* it only applies if `def` is of specific types, but I guess we can live with it. 

r=me

**Comment by edwin0cheng** [comment]
And other option here is we change [`StructID`][1] to store `RecordID` and `TupleID`, but it is quite a big changes for single PR I am afraid to do. 

[1]: https://github.com/rust-analyzer/rust-analyzer/blob/05981823bac91ba338110902fd435c6e3166f1d6/crates/ra_hir_def/src/lib.rs#L112

**Comment by flodiebold** [comment]
Yet another way would be to give constructors their own def, like rustc does (and we used to do).

**Comment by matklad** [comment]
I think, if we introduce explicit abstract IR for name res, we might be able to have both:

* at the IR level, there would be two separate defs, one in type, one in value ns (the IR should have a constraint that a def can belong to a single ns)
* at the lowering-to-IR level, both IDs would map to the same StructDef.
